-- Seed data for partners and partner testimonials
-- BlueJay Innovative Labs B2B Technology Partners

-- Insert Technology Partners
INSERT INTO partners (name, tier_id, logo_url, icon, website_url, description, display_order, is_active) VALUES
('Intel', (SELECT id FROM partner_tiers WHERE slug = 'technology-partners'), NULL, 'memory', 'https://www.intel.com', 'Strategic partnership leveraging Intel processors to power BlueJay''s interactive flat panels and OPS modules with cutting-edge performance and reliability.', 1, 1),
('Microsoft', (SELECT id FROM partner_tiers WHERE slug = 'technology-partners'), NULL, 'devices', 'https://www.microsoft.com', 'Collaboration on Windows-based solutions and Microsoft 365 integration for seamless productivity across BlueJay''s enterprise and education products.', 2, 1),
('Google', (SELECT id FROM partner_tiers WHERE slug = 'technology-partners'), NULL, 'cloud', 'https://www.google.com', 'Partnership delivering Chrome OS and Android-powered solutions, bringing cloud-first innovation to BlueJay''s interactive displays and kiosks.', 3, 1),
('Samsung Display', (SELECT id FROM partner_tiers WHERE slug = 'technology-partners'), NULL, 'display_settings', 'https://www.samsungdisplay.com', 'Premium display panel supplier providing high-resolution, durable screens that meet the demanding requirements of education and enterprise environments.', 4, 1),
('Qualcomm', (SELECT id FROM partner_tiers WHERE slug = 'technology-partners'), NULL, 'settings_input_antenna', 'https://www.qualcomm.com', 'Technology partner enabling advanced wireless connectivity and IoT capabilities in BlueJay''s smart displays and mobile computing solutions.', 5, 1),
('NVIDIA', (SELECT id FROM partner_tiers WHERE slug = 'technology-partners'), NULL, 'smart_toy', 'https://www.nvidia.com', 'GPU technology partnership powering AI-enhanced features and high-performance graphics rendering in BlueJay''s interactive display solutions.', 6, 1);

-- Insert Channel Partners
INSERT INTO partners (name, tier_id, logo_url, icon, website_url, description, display_order, is_active) VALUES
('CDW', (SELECT id FROM partner_tiers WHERE slug = 'channel-partners'), NULL, 'shopping_cart', 'https://www.cdw.com', 'Leading enterprise IT reseller providing comprehensive sales and support for BlueJay products across education and corporate sectors throughout North America.', 7, 1),
('Insight Enterprises', (SELECT id FROM partner_tiers WHERE slug = 'channel-partners'), NULL, 'store', 'https://www.insight.com', 'Global IT solutions provider delivering BlueJay''s interactive technology to businesses worldwide with expert integration and managed services.', 8, 1),
('SHI International', (SELECT id FROM partner_tiers WHERE slug = 'channel-partners'), NULL, 'business', 'https://www.shi.com', 'Premier IT solutions partner offering BlueJay products with procurement expertise, deployment services, and enterprise-level support.', 9, 1),
('Ingram Micro', (SELECT id FROM partner_tiers WHERE slug = 'channel-partners'), NULL, 'local_shipping', 'https://www.ingrammicro.com', 'Global distribution partner ensuring BlueJay products reach resellers and integrators efficiently with comprehensive logistics and supply chain management.', 10, 1),
('TD SYNNEX', (SELECT id FROM partner_tiers WHERE slug = 'channel-partners'), NULL, 'warehouse', 'https://www.tdsynnex.com', 'Distribution and technology solutions aggregator connecting BlueJay with thousands of resellers and providing value-added services across multiple regions.', 11, 1);

-- Insert Partner Testimonials
INSERT INTO partner_testimonials (partner_id, quote, author_name, author_title, display_order, is_active) VALUES
((SELECT id FROM partners WHERE name = 'Intel'), 'BlueJay has been an exceptional partner in bringing Intel-powered interactive displays to market. Their engineering team''s commitment to optimizing performance and thermal efficiency has resulted in products that truly showcase what our latest processor technology can deliver.', 'Sarah Mitchell', 'Director of Education Solutions, Intel', 1, 1),
((SELECT id FROM partners WHERE name = 'Microsoft'), 'The collaboration with BlueJay on Windows 11 integration and Teams Rooms certification has been outstanding. Their interactive panels provide an ideal platform for modern hybrid work and learning environments.', 'David Chen', 'Partner Development Manager, Microsoft Education', 2, 1),
((SELECT id FROM partners WHERE name = 'Samsung Display'), 'We''ve worked with many display manufacturers, but BlueJay''s attention to quality standards and their rigorous testing processes make them a standout partner. They push our panels to their full potential while ensuring durability for demanding classroom and boardroom use.', 'Kim Jae-Won', 'B2B Sales Director, Samsung Display', 3, 1),
((SELECT id FROM partners WHERE name = 'CDW'), 'BlueJay has become one of our most reliable partners in the interactive display category. Their products consistently meet our customers'' needs, and their partner support team is responsive and knowledgeable. Our sales team loves working with them.', 'Jennifer Rodriguez', 'Senior Category Manager, CDW', 4, 1),
((SELECT id FROM partners WHERE name = 'Insight Enterprises'), 'As we deploy large-scale classroom technology projects globally, BlueJay''s products and partnership approach have been instrumental. Their commitment to channel partner success, from pre-sales support to warranty service, sets them apart in this competitive market.', 'Michael Thompson', 'VP of Education Solutions, Insight Enterprises', 5, 1),
((SELECT id FROM partners WHERE name = 'Ingram Micro'), 'BlueJay understands the distribution model and makes it easy for our reseller network to succeed. Their product availability, competitive pricing programs, and streamlined ordering process have driven consistent growth in this category for us.', 'Patricia Lee', 'Director of Display Solutions, Ingram Micro', 6, 1);
