// Package models defines the domain data structures used throughout the Bluejay CMS application.
// These models serve as view models and data transfer objects (DTOs) for handlers and templates,
// representing aggregated data from multiple database tables. Unlike the sqlc-generated types in
// the database layer which map 1:1 to tables, these models combine related entities for efficient
// data presentation in the admin interface and public-facing pages.
package models

import (
	// database/sql provides nullable types (sql.NullString, sql.NullInt64, sql.NullTime)
	// used for optional database fields that may contain NULL values. These types ensure
	// proper handling of NULL in SQLite queries and prevent nil pointer errors.
	"database/sql"

	// time provides the Time type for timestamp fields (CreatedAt, UpdatedAt, PublishedAt).
	// All timestamps are stored in UTC and converted to local time zones when displayed.
	"time"
)

// ProductDetail represents the complete aggregated view of a product with all its related entities.
// This is the primary view model used when displaying a full product page or editing a product
// in the admin panel. It combines data from multiple database tables (products, categories,
// product_specs, product_images, product_features, product_certifications, product_downloads)
// into a single hierarchical structure for efficient template rendering.
//
// This model is typically constructed by service layer functions that execute multiple
// database queries and assemble the results into this composite structure.
type ProductDetail struct {
	// Product contains the core product information including name, SKU, description, and metadata.
	// This corresponds to a single row from the products table.
	Product ProductView

	// Category contains the product's category information, fetched via the CategoryID foreign key.
	// Each product belongs to exactly one category, used for navigation and filtering.
	Category CategoryView

	// Specs contains all technical specifications for the product, grouped by section.
	// Specifications are key-value pairs (e.g., "Power": "120W") organized into sections
	// (e.g., "Electrical", "Physical Dimensions") for structured display.
	Specs []SpecView

	// Images contains all product images including thumbnails, gallery images, and detail shots.
	// Images are ordered by DisplayOrder and include metadata like alt text and captions.
	// The IsThumbnail flag indicates which image(s) should be used in product listings.
	Images []ImageView

	// Features contains the bullet-point features or selling points for the product.
	// These are typically short phrases displayed prominently on product pages
	// (e.g., "Energy Star Certified", "5-year warranty").
	Features []FeatureView

	// Certifications contains industry certifications, compliance marks, and standards
	// that the product meets (e.g., UL, CE, RoHS). Each certification can have an icon
	// for visual display on product pages.
	Certifications []CertificationView

	// Downloads contains downloadable resources related to the product such as datasheets,
	// manuals, CAD files, and technical drawings. Each download tracks file size, version,
	// and download count for analytics.
	Downloads []DownloadView
}

// ProductView represents the core product entity with all its main attributes.
// This view model maps directly to the products table in the database and is used
// throughout the application for displaying product information in lists, detail pages,
// and admin forms. Field types match the sqlc-generated Product type but this model
// provides a stable interface independent of database schema changes.
//
// Status values: "draft", "published", "archived"
// IsFeatured values: 0 (not featured) or 1 (featured on homepage/category pages)
type ProductView struct {
	// ID is the primary key, auto-generated by SQLite on insert.
	// Used for all internal references and database joins.
	ID int64

	// SKU is the Stock Keeping Unit, a unique product identifier for inventory management.
	// Format is typically vendor-defined (e.g., "PUMP-2000-A", "VLV-3/4-BR").
	// Must be unique across all products in the database.
	SKU string

	// Slug is the URL-friendly version of the product name, used in public-facing URLs.
	// Example: "centrifugal-pump-model-2000" for URL /products/centrifugal-pump-model-2000
	// Must be unique and contain only lowercase letters, numbers, and hyphens.
	Slug string

	// Name is the display name of the product shown in titles, headings, and navigation.
	// This is the primary human-readable identifier for the product.
	Name string

	// Tagline is an optional short marketing phrase or subtitle for the product.
	// Typically displayed below the product name on detail pages (e.g., "Professional Grade Performance").
	Tagline sql.NullString

	// Description is the main content describing the product, stored as HTML.
	// Edited using the Trix WYSIWYG editor in the admin panel, this field contains
	// the full product description with formatting, lists, and embedded media.
	Description string

	// Overview is an optional plain-text summary or executive summary of the product.
	// Used for search snippets and quick previews before the full description.
	Overview sql.NullString

	// CategoryID is the foreign key reference to the categories table.
	// Every product must belong to exactly one category for organization and navigation.
	CategoryID int64

	// Status controls the publication state and visibility of the product.
	// Values: "draft" (not visible), "published" (visible on site), "archived" (hidden but preserved).
	Status string

	// IsFeatured indicates whether this product should be highlighted on the homepage
	// or category pages. SQLite boolean stored as integer: 0 = false, 1 = true.
	IsFeatured int64

	// FeaturedOrder determines the display order when multiple products are featured.
	// Lower numbers appear first. NULL values are sorted after numbered items.
	// Only relevant when IsFeatured = 1.
	FeaturedOrder sql.NullInt64

	// MetaTitle is the custom SEO title for the product page's <title> tag.
	// If NULL, the product Name is used as the default title.
	// Recommended length: 50-60 characters for optimal search engine display.
	MetaTitle sql.NullString

	// MetaDescription is the SEO meta description for search engine result pages.
	// If NULL, an excerpt from the Description or Overview is used.
	// Recommended length: 150-160 characters for optimal search engine display.
	MetaDescription sql.NullString

	// PrimaryImage is the file path to the main product image, relative to the public/ directory.
	// Example: "uploads/products/pump-2000-main.jpg"
	// If NULL, a default placeholder image is used.
	PrimaryImage sql.NullString

	// VideoURL is an optional external video URL (YouTube, Vimeo, etc.) for the product.
	// Displayed on the product detail page as an embedded player.
	// Example: "https://www.youtube.com/watch?v=abc123"
	VideoURL sql.NullString

	// CreatedAt is the timestamp when the product record was first created.
	// Set automatically by SQLite DEFAULT CURRENT_TIMESTAMP, stored in UTC.
	CreatedAt time.Time

	// UpdatedAt is the timestamp of the most recent modification to the product record.
	// Updated automatically by SQLite trigger on any UPDATE operation, stored in UTC.
	UpdatedAt time.Time

	// PublishedAt is the timestamp when the product status was changed to "published".
	// NULL for draft/archived products. Used for sorting by publication date and
	// displaying "New" badges on recently published products.
	PublishedAt sql.NullTime
}

// CategoryView represents a product category used for organizing and filtering products.
// Categories are displayed in navigation menus, sidebar filters, and breadcrumb trails.
// This model maps to the categories table and provides a hierarchical organization
// system for products (though the current schema supports only a flat structure).
//
// Example categories: "Pumps", "Valves", "Filters", "Sensors"
type CategoryView struct {
	// ID is the primary key, auto-generated by SQLite on insert.
	// Referenced by ProductView.CategoryID to establish the product-category relationship.
	ID int64

	// Name is the display name of the category shown in navigation and headings.
	// Example: "Centrifugal Pumps", "Ball Valves"
	Name string

	// Slug is the URL-friendly version of the category name, used in public-facing URLs.
	// Example: "centrifugal-pumps" for URL /categories/centrifugal-pumps
	// Must be unique and contain only lowercase letters, numbers, and hyphens.
	Slug string

	// Description is a text description of the category, displayed on category landing pages.
	// Provides context about what types of products are included in this category.
	// May contain plain text or simple HTML formatting.
	Description string

	// Icon is an identifier for the icon used to represent this category in the UI.
	// Typically references a CSS class name or icon library identifier (e.g., "icon-pump", "fa-valve").
	// Used in navigation menus, category cards, and product badges.
	Icon string

	// ImageUrl is an optional header/banner image for the category landing page.
	// File path relative to public/ directory (e.g., "uploads/categories/pumps-header.jpg").
	// If NULL, a default category image or no image is displayed.
	ImageUrl sql.NullString
}

// SpecView represents a single technical specification for a product.
// Specifications are organized into sections (e.g., "Electrical", "Physical Dimensions")
// and presented as key-value pairs (e.g., "Voltage": "120V AC", "Weight": "15 lbs").
// This model maps to the product_specs table and is used to build specification tables
// on product detail pages.
//
// Example: SectionName="Performance", SpecKey="Flow Rate", SpecValue="100 GPM"
type SpecView struct {
	// ID is the primary key for the specification record, auto-generated by SQLite.
	// Used for editing and deleting individual specifications.
	ID int64

	// ProductID is the foreign key reference to the products table.
	// Links this specification to its parent product. Multiple specs can share the same ProductID.
	ProductID int64

	// SectionName groups related specifications together for organized display.
	// Common sections: "General", "Electrical", "Physical Dimensions", "Performance",
	// "Environmental", "Certifications & Compliance".
	// Template rendering groups specs by this field to create tabbed or sectioned displays.
	SectionName string

	// SpecKey is the name or label of the specification (e.g., "Voltage", "Material", "Temperature Range").
	// Displayed in the left column of specification tables.
	SpecKey string

	// SpecValue is the value or measurement for the specification (e.g., "120V AC", "Stainless Steel", "-40°C to 85°C").
	// Displayed in the right column of specification tables, may include units of measurement.
	SpecValue string

	// DisplayOrder controls the sort order of specifications within their section.
	// Lower numbers appear first. Allows custom ordering of specs for optimal presentation
	// (e.g., showing most important specs at the top).
	DisplayOrder int64
}

// ImageView represents a product image with its associated metadata.
// Products can have multiple images for galleries, thumbnails, and detail views.
// This model maps to the product_images table and supports image management,
// accessibility (alt text), and SEO (captions). Images are stored in the file system
// with paths recorded in the database.
//
// IsThumbnail values: 0 (regular image) or 1 (used as thumbnail in product lists)
type ImageView struct {
	// ID is the primary key for the image record, auto-generated by SQLite.
	// Used for editing, deleting, and reordering images in the admin panel.
	ID int64

	// ProductID is the foreign key reference to the products table.
	// Links this image to its parent product. A product typically has 1-10 images.
	ProductID int64

	// ImagePath is the file path to the image file, relative to the public/ directory.
	// Example: "uploads/products/pump-2000-front.jpg"
	// Files are stored on disk; this field contains only the path reference.
	ImagePath string

	// AltText is the alternative text for the image, used for accessibility (screen readers)
	// and displayed when the image fails to load. Required for WCAG compliance.
	// Example: "Front view of Model 2000 centrifugal pump showing inlet and outlet ports"
	AltText sql.NullString

	// Caption is an optional visible text caption displayed below the image.
	// Used to provide context, credits, or additional information about the image.
	// Example: "Pump shown with optional pressure gauge accessory"
	Caption sql.NullString

	// DisplayOrder controls the sort order of images in galleries and carousels.
	// Lower numbers appear first. The first image (order 0 or 1) is typically the
	// primary product image shown in search results and category listings.
	DisplayOrder int64

	// IsThumbnail indicates whether this image should be used as the product thumbnail
	// in list views, search results, and category pages. SQLite boolean stored as integer:
	// 0 = regular gallery image, 1 = thumbnail image.
	// Multiple images can have IsThumbnail=1 for responsive image sets.
	IsThumbnail int64
}

// FeatureView represents a single product feature or selling point.
// Features are short, scannable bullet points highlighting key benefits and capabilities
// of the product. They are prominently displayed near the product title and image
// to quickly communicate value to potential customers. This model maps to the
// product_features table.
//
// Example features: "Energy Star Certified", "5-Year Warranty", "Made in USA",
// "Stainless Steel Construction", "Easy Installation"
type FeatureView struct {
	// ID is the primary key for the feature record, auto-generated by SQLite.
	// Used for editing, deleting, and reordering features in the admin panel.
	ID int64

	// ProductID is the foreign key reference to the products table.
	// Links this feature to its parent product. A product typically has 3-8 features.
	ProductID int64

	// FeatureText is the content of the feature, typically a short phrase or sentence.
	// Best practice: keep under 50 characters for optimal display in bullet lists.
	// Example: "Industry-leading 10 GPM flow rate"
	FeatureText string

	// DisplayOrder controls the sort order of features in the list.
	// Lower numbers appear first. Most important features should have lower order values
	// to appear at the top of the list where they are most visible.
	DisplayOrder int64
}

// CertificationView represents an industry certification, compliance mark, or quality standard
// that a product meets. Certifications build trust and are often required for sales in
// regulated industries or markets. Each certification can have an associated icon or logo
// displayed on product pages. This model maps to the product_certifications table.
//
// Example certifications: UL Listed, CE Mark, RoHS Compliant, ISO 9001, Energy Star,
// NSF Certified, ASME Code
type CertificationView struct {
	// ID is the primary key for the certification record, auto-generated by SQLite.
	// Used for editing and deleting certifications in the admin panel.
	ID int64

	// ProductID is the foreign key reference to the products table.
	// Links this certification to its parent product. A product may have 0-10 certifications.
	ProductID int64

	// CertificationName is the full name or title of the certification.
	// Example: "UL Listed", "CE Conformity", "ISO 9001:2015", "NSF/ANSI 61"
	// Displayed as text on product pages and in specification sheets.
	CertificationName string

	// CertificationCode is an optional reference number, code, or registration ID
	// for the certification. Some certifications include unique identifiers that can
	// be verified with the certifying body.
	// Example: "E123456" for UL file number, "CE-2023-12345" for CE declaration number
	CertificationCode sql.NullString

	// IconType specifies the source or type of the certification icon.
	// Values might include: "builtin" (predefined icon set), "custom" (uploaded file),
	// "svg" (inline SVG), or NULL (no icon).
	// Used to determine how to render the certification visually.
	IconType sql.NullString

	// IconPath is the file path or identifier for the certification icon/logo.
	// For custom icons: path relative to public/ directory (e.g., "uploads/certs/ul-listed.png")
	// For builtin icons: icon identifier (e.g., "ul", "ce", "rohs")
	// For SVG: may contain inline SVG code or path to SVG file
	IconPath sql.NullString

	// DisplayOrder controls the sort order of certifications when multiple are displayed.
	// Lower numbers appear first. Most important or prestigious certifications should
	// have lower order values to appear prominently.
	DisplayOrder int64
}

// DownloadView represents a downloadable file resource associated with a product.
// Common downloads include datasheets, user manuals, installation guides, CAD drawings,
// technical specifications, and software utilities. This model maps to the
// product_downloads table and tracks download analytics for business intelligence.
//
// Supported file types: PDF, ZIP, DWG, DXF, STEP, IGES, XLS, DOC, etc.
type DownloadView struct {
	// ID is the primary key for the download record, auto-generated by SQLite.
	// Used for editing, deleting, and tracking individual downloads.
	ID int64

	// ProductID is the foreign key reference to the products table.
	// Links this downloadable file to its parent product. A product may have 1-20 downloads.
	ProductID int64

	// Title is the display name for the download shown in the downloads list.
	// Should be descriptive and indicate the content type.
	// Example: "Installation Manual", "CAD Drawing - STEP Format", "Product Datasheet"
	Title string

	// Description is an optional longer explanation of the download contents.
	// Helps users understand what information the file contains before downloading.
	// Example: "Complete installation instructions including wiring diagrams and mounting templates"
	Description sql.NullString

	// FileType is the file extension or MIME type of the downloadable file.
	// Used to display appropriate icons and set Content-Type headers when serving downloads.
	// Example values: "pdf", "zip", "dwg", "application/pdf"
	// Stored in lowercase for consistent filtering and icon mapping.
	FileType string

	// FilePath is the file path to the downloadable file, relative to the public/ directory.
	// Example: "uploads/downloads/pump-2000-manual.pdf"
	// Files are stored on disk or in cloud storage; this field contains the path reference.
	FilePath string

	// FileSize is the size of the file in bytes, used to display human-readable file sizes
	// to users (e.g., "2.4 MB") before they download. NULL if file size is unknown or
	// not yet calculated (e.g., for newly uploaded files awaiting background processing).
	FileSize sql.NullInt64

	// Version is an optional version identifier for the file, useful for documents
	// that are updated over time (manuals, software, firmware).
	// Example: "Rev. 3.2", "2024-01", "v1.5"
	// Helps users identify whether they have the latest version.
	Version sql.NullString

	// DownloadCount tracks how many times this file has been downloaded.
	// Incremented each time a user successfully downloads the file, used for analytics
	// to understand which resources are most valuable to customers.
	// Initialized to 0 for new downloads.
	DownloadCount int64

	// DisplayOrder controls the sort order of downloads in the list.
	// Lower numbers appear first. Most important downloads (e.g., primary datasheet)
	// should have lower order values to appear at the top of the downloads section.
	DisplayOrder int64
}

// SpecSection groups specifications by their section name for organized template rendering.
// This is a helper model used to transform the flat list of SpecView items into a
// hierarchical structure that is easier to render in templates. For example, instead
// of looping through all specs and checking section names, the service layer can
// group specs and provide a []SpecSection to the template, where each section contains
// its related specs.
//
// Example: A product with 12 specs might be grouped into 3 SpecSections:
// - "Electrical" with 4 specs
// - "Physical Dimensions" with 5 specs
// - "Performance" with 3 specs
//
// This structure enables clean template code with nested loops:
// {{range .SpecSections}}
//
//	<h3>{{.Name}}</h3>
//	{{range .Specs}}...<{{end}}
//
// {{end}}
type SpecSection struct {
	// Name is the section heading (e.g., "General", "Electrical", "Performance").
	// Corresponds to SpecView.SectionName. Displayed as a subheading in spec tables.
	Name string

	// Specs contains all specifications that belong to this section, ordered by DisplayOrder.
	// This slice is populated by grouping SpecView items that share the same SectionName.
	Specs []SpecView
}
