// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: about.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCertification = `-- name: CreateCertification :one
INSERT INTO certifications (name, abbreviation, description, icon, display_order)
VALUES (?, ?, ?, ?, ?) RETURNING id, name, abbreviation, description, icon, display_order, created_at
`

type CreateCertificationParams struct {
	Name         string         `json:"name"`
	Abbreviation string         `json:"abbreviation"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	DisplayOrder int64          `json:"display_order"`
}

func (q *Queries) CreateCertification(ctx context.Context, arg CreateCertificationParams) (Certification, error) {
	row := q.db.QueryRowContext(ctx, createCertification,
		arg.Name,
		arg.Abbreviation,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createCoreValue = `-- name: CreateCoreValue :one
INSERT INTO core_values (title, description, icon, display_order)
VALUES (?, ?, ?, ?) RETURNING id, title, description, icon, display_order, created_at
`

type CreateCoreValueParams struct {
	Title        string `json:"title"`
	Description  string `json:"description"`
	Icon         string `json:"icon"`
	DisplayOrder int64  `json:"display_order"`
}

func (q *Queries) CreateCoreValue(ctx context.Context, arg CreateCoreValueParams) (CoreValue, error) {
	row := q.db.QueryRowContext(ctx, createCoreValue,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i CoreValue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (year, title, description, is_current, display_order)
VALUES (?, ?, ?, ?, ?) RETURNING id, year, title, description, is_current, display_order, created_at
`

type CreateMilestoneParams struct {
	Year         int64  `json:"year"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	IsCurrent    int64  `json:"is_current"`
	DisplayOrder int64  `json:"display_order"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, createMilestone,
		arg.Year,
		arg.Title,
		arg.Description,
		arg.IsCurrent,
		arg.DisplayOrder,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Title,
		&i.Description,
		&i.IsCurrent,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCertification = `-- name: DeleteCertification :exec
DELETE FROM certifications WHERE id = ?
`

func (q *Queries) DeleteCertification(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCertification, id)
	return err
}

const deleteCoreValue = `-- name: DeleteCoreValue :exec
DELETE FROM core_values WHERE id = ?
`

func (q *Queries) DeleteCoreValue(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoreValue, id)
	return err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones WHERE id = ?
`

func (q *Queries) DeleteMilestone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMilestone, id)
	return err
}

const getCertification = `-- name: GetCertification :one
SELECT id, name, abbreviation, description, icon, display_order, created_at FROM certifications WHERE id = ? LIMIT 1
`

func (q *Queries) GetCertification(ctx context.Context, id int64) (Certification, error) {
	row := q.db.QueryRowContext(ctx, getCertification, id)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getCompanyOverview = `-- name: GetCompanyOverview :one
SELECT id, headline, tagline, description_main, description_secondary, description_tertiary, hero_image_url, company_image_url, updated_at FROM company_overview ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetCompanyOverview(ctx context.Context) (CompanyOverview, error) {
	row := q.db.QueryRowContext(ctx, getCompanyOverview)
	var i CompanyOverview
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Tagline,
		&i.DescriptionMain,
		&i.DescriptionSecondary,
		&i.DescriptionTertiary,
		&i.HeroImageUrl,
		&i.CompanyImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoreValue = `-- name: GetCoreValue :one
SELECT id, title, description, icon, display_order, created_at FROM core_values WHERE id = ? LIMIT 1
`

func (q *Queries) GetCoreValue(ctx context.Context, id int64) (CoreValue, error) {
	row := q.db.QueryRowContext(ctx, getCoreValue, id)
	var i CoreValue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, year, title, description, is_current, display_order, created_at FROM milestones WHERE id = ? LIMIT 1
`

func (q *Queries) GetMilestone(ctx context.Context, id int64) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, getMilestone, id)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Title,
		&i.Description,
		&i.IsCurrent,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getMissionVisionValues = `-- name: GetMissionVisionValues :one
SELECT id, mission, vision, values_summary, mission_icon, vision_icon, values_icon, updated_at FROM mission_vision_values ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetMissionVisionValues(ctx context.Context) (MissionVisionValue, error) {
	row := q.db.QueryRowContext(ctx, getMissionVisionValues)
	var i MissionVisionValue
	err := row.Scan(
		&i.ID,
		&i.Mission,
		&i.Vision,
		&i.ValuesSummary,
		&i.MissionIcon,
		&i.VisionIcon,
		&i.ValuesIcon,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertifications = `-- name: ListCertifications :many
SELECT id, name, abbreviation, description, icon, display_order, created_at FROM certifications ORDER BY display_order ASC
`

func (q *Queries) ListCertifications(ctx context.Context) ([]Certification, error) {
	rows, err := q.db.QueryContext(ctx, listCertifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certification{}
	for rows.Next() {
		var i Certification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Abbreviation,
			&i.Description,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreValues = `-- name: ListCoreValues :many
SELECT id, title, description, icon, display_order, created_at FROM core_values ORDER BY display_order ASC
`

func (q *Queries) ListCoreValues(ctx context.Context) ([]CoreValue, error) {
	rows, err := q.db.QueryContext(ctx, listCoreValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreValue{}
	for rows.Next() {
		var i CoreValue
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, year, title, description, is_current, display_order, created_at FROM milestones ORDER BY display_order ASC
`

func (q *Queries) ListMilestones(ctx context.Context) ([]Milestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Title,
			&i.Description,
			&i.IsCurrent,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertification = `-- name: UpdateCertification :one
UPDATE certifications SET name = ?, abbreviation = ?, description = ?, icon = ?, display_order = ?
WHERE id = ? RETURNING id, name, abbreviation, description, icon, display_order, created_at
`

type UpdateCertificationParams struct {
	Name         string         `json:"name"`
	Abbreviation string         `json:"abbreviation"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	DisplayOrder int64          `json:"display_order"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateCertification(ctx context.Context, arg UpdateCertificationParams) (Certification, error) {
	row := q.db.QueryRowContext(ctx, updateCertification,
		arg.Name,
		arg.Abbreviation,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
		arg.ID,
	)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateCoreValue = `-- name: UpdateCoreValue :one
UPDATE core_values SET title = ?, description = ?, icon = ?, display_order = ?
WHERE id = ? RETURNING id, title, description, icon, display_order, created_at
`

type UpdateCoreValueParams struct {
	Title        string `json:"title"`
	Description  string `json:"description"`
	Icon         string `json:"icon"`
	DisplayOrder int64  `json:"display_order"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateCoreValue(ctx context.Context, arg UpdateCoreValueParams) (CoreValue, error) {
	row := q.db.QueryRowContext(ctx, updateCoreValue,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
		arg.ID,
	)
	var i CoreValue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones SET year = ?, title = ?, description = ?, is_current = ?, display_order = ?
WHERE id = ? RETURNING id, year, title, description, is_current, display_order, created_at
`

type UpdateMilestoneParams struct {
	Year         int64  `json:"year"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	IsCurrent    int64  `json:"is_current"`
	DisplayOrder int64  `json:"display_order"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, updateMilestone,
		arg.Year,
		arg.Title,
		arg.Description,
		arg.IsCurrent,
		arg.DisplayOrder,
		arg.ID,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Title,
		&i.Description,
		&i.IsCurrent,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCompanyOverview = `-- name: UpsertCompanyOverview :one
INSERT INTO company_overview (
    headline, tagline, description_main, description_secondary,
    description_tertiary, hero_image_url, company_image_url
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, headline, tagline, description_main, description_secondary, description_tertiary, hero_image_url, company_image_url, updated_at
`

type UpsertCompanyOverviewParams struct {
	Headline             string         `json:"headline"`
	Tagline              string         `json:"tagline"`
	DescriptionMain      string         `json:"description_main"`
	DescriptionSecondary sql.NullString `json:"description_secondary"`
	DescriptionTertiary  sql.NullString `json:"description_tertiary"`
	HeroImageUrl         sql.NullString `json:"hero_image_url"`
	CompanyImageUrl      sql.NullString `json:"company_image_url"`
}

func (q *Queries) UpsertCompanyOverview(ctx context.Context, arg UpsertCompanyOverviewParams) (CompanyOverview, error) {
	row := q.db.QueryRowContext(ctx, upsertCompanyOverview,
		arg.Headline,
		arg.Tagline,
		arg.DescriptionMain,
		arg.DescriptionSecondary,
		arg.DescriptionTertiary,
		arg.HeroImageUrl,
		arg.CompanyImageUrl,
	)
	var i CompanyOverview
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Tagline,
		&i.DescriptionMain,
		&i.DescriptionSecondary,
		&i.DescriptionTertiary,
		&i.HeroImageUrl,
		&i.CompanyImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMissionVisionValues = `-- name: UpsertMissionVisionValues :one
INSERT INTO mission_vision_values (
    mission, vision, values_summary,
    mission_icon, vision_icon, values_icon
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, mission, vision, values_summary, mission_icon, vision_icon, values_icon, updated_at
`

type UpsertMissionVisionValuesParams struct {
	Mission       string         `json:"mission"`
	Vision        string         `json:"vision"`
	ValuesSummary sql.NullString `json:"values_summary"`
	MissionIcon   string         `json:"mission_icon"`
	VisionIcon    string         `json:"vision_icon"`
	ValuesIcon    string         `json:"values_icon"`
}

func (q *Queries) UpsertMissionVisionValues(ctx context.Context, arg UpsertMissionVisionValuesParams) (MissionVisionValue, error) {
	row := q.db.QueryRowContext(ctx, upsertMissionVisionValues,
		arg.Mission,
		arg.Vision,
		arg.ValuesSummary,
		arg.MissionIcon,
		arg.VisionIcon,
		arg.ValuesIcon,
	)
	var i MissionVisionValue
	err := row.Scan(
		&i.ID,
		&i.Mission,
		&i.Vision,
		&i.ValuesSummary,
		&i.MissionIcon,
		&i.VisionIcon,
		&i.ValuesIcon,
		&i.UpdatedAt,
	)
	return i, err
}
