// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: about.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCertification = `-- name: CreateCertification :one
INSERT INTO certifications (name, abbreviation, description, icon, display_order)
VALUES (?, ?, ?, ?, ?) RETURNING id, name, abbreviation, description, icon, display_order, created_at
`

type CreateCertificationParams struct {
	Name         string         `json:"name"`
	Abbreviation string         `json:"abbreviation"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	DisplayOrder int64          `json:"display_order"`
}

// sqlc annotation: :one returns created certification
// Purpose: Adds a new certification/credential entry
// Parameters (5 positional):
//  1. name (TEXT): full certification name
//  2. abbreviation (TEXT): short form (e.g., "ISO 9001")
//  3. description (TEXT): certification details
//  4. icon (TEXT): icon identifier for display
//  5. display_order (INTEGER): sort position
//
// Return type: complete inserted row with ID
func (q *Queries) CreateCertification(ctx context.Context, arg CreateCertificationParams) (Certification, error) {
	row := q.db.QueryRowContext(ctx, createCertification,
		arg.Name,
		arg.Abbreviation,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createCoreValue = `-- name: CreateCoreValue :one
INSERT INTO core_values (title, description, icon, display_order)
VALUES (?, ?, ?, ?) RETURNING id, title, description, icon, display_order, created_at
`

type CreateCoreValueParams struct {
	Title        string `json:"title"`
	Description  string `json:"description"`
	Icon         string `json:"icon"`
	DisplayOrder int64  `json:"display_order"`
}

// sqlc annotation: :one returns the created row
// Purpose: Creates a new core value entry
// Parameters (4 positional):
//  1. title (TEXT): value name/title
//  2. description (TEXT): detailed explanation
//  3. icon (TEXT): icon identifier (e.g., "shield", "star")
//  4. display_order (INTEGER): sort position in list
//
// Return type: complete inserted row with generated ID
func (q *Queries) CreateCoreValue(ctx context.Context, arg CreateCoreValueParams) (CoreValue, error) {
	row := q.db.QueryRowContext(ctx, createCoreValue,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i CoreValue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (year, title, description, is_current, display_order)
VALUES (?, ?, ?, ?, ?) RETURNING id, year, title, description, is_current, display_order, created_at
`

type CreateMilestoneParams struct {
	Year         int64  `json:"year"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	IsCurrent    int64  `json:"is_current"`
	DisplayOrder int64  `json:"display_order"`
}

// sqlc annotation: :one returns created milestone
// Purpose: Creates a new milestone entry for company timeline
// Parameters (5 positional):
//  1. year (TEXT): year of milestone (stored as text for flexibility)
//  2. title (TEXT): milestone heading
//  3. description (TEXT): milestone details
//  4. is_current (BOOLEAN): marks if this is the current/ongoing milestone
//  5. display_order (INTEGER): sort position in timeline
//
// Return type: complete inserted row
func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, createMilestone,
		arg.Year,
		arg.Title,
		arg.Description,
		arg.IsCurrent,
		arg.DisplayOrder,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Title,
		&i.Description,
		&i.IsCurrent,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCertification = `-- name: DeleteCertification :exec
DELETE FROM certifications WHERE id = ?
`

// sqlc annotation: :exec returns no data
// Purpose: Removes a certification from the list
// Parameters:
//  1. id (INTEGER): certification to delete
//
// Return type: none
func (q *Queries) DeleteCertification(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCertification, id)
	return err
}

const deleteCoreValue = `-- name: DeleteCoreValue :exec
DELETE FROM core_values WHERE id = ?
`

// sqlc annotation: :exec returns no data, only error or nil
// Purpose: Permanently removes a core value entry
// Parameters:
//  1. id (INTEGER): core value to delete
//
// Return type: none (exec returns only error status)
func (q *Queries) DeleteCoreValue(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoreValue, id)
	return err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones WHERE id = ?
`

// sqlc annotation: :exec returns no data
// Purpose: Removes a milestone from the timeline
// Parameters:
//  1. id (INTEGER): milestone to delete
//
// Return type: none
func (q *Queries) DeleteMilestone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMilestone, id)
	return err
}

const getCertification = `-- name: GetCertification :one
SELECT id, name, abbreviation, description, icon, display_order, created_at FROM certifications WHERE id = ? LIMIT 1
`

// sqlc annotation: :one returns single certification or error
// Purpose: Retrieves specific certification for editing
// Parameters:
//  1. id (INTEGER): certification primary key
//
// Return type: single certifications row
func (q *Queries) GetCertification(ctx context.Context, id int64) (Certification, error) {
	row := q.db.QueryRowContext(ctx, getCertification, id)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getCompanyOverview = `-- name: GetCompanyOverview :one


SELECT id, headline, tagline, description_main, description_secondary, description_tertiary, hero_image_url, company_image_url, updated_at FROM company_overview ORDER BY id DESC LIMIT 1
`

// ====================================================================
// ABOUT PAGE QUERIES
// ====================================================================
// This file contains all SQL queries for managing "About Us" page content
// including company overview, mission/vision/values, core values list,
// company milestones timeline, and certifications/credentials display.
//
// Managed entities:
// - company_overview: main about page hero content
// - mission_vision_values: strategic statements section
// - core_values: individual value items with icons
// - milestones: company history timeline
// - certifications: professional credentials and certifications
// ====================================================================
// ====================================================================
// COMPANY OVERVIEW
// ====================================================================
// sqlc annotation: :one returns a single row or error if not found
// Purpose: Retrieves the most recent company overview content for the About page
// Parameters: none
// Return type: single company_overview row
// Note: Uses ORDER BY id DESC to get the latest entry (highest ID)
func (q *Queries) GetCompanyOverview(ctx context.Context) (CompanyOverview, error) {
	row := q.db.QueryRowContext(ctx, getCompanyOverview)
	var i CompanyOverview
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Tagline,
		&i.DescriptionMain,
		&i.DescriptionSecondary,
		&i.DescriptionTertiary,
		&i.HeroImageUrl,
		&i.CompanyImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoreValue = `-- name: GetCoreValue :one
SELECT id, title, description, icon, display_order, created_at FROM core_values WHERE id = ? LIMIT 1
`

// sqlc annotation: :one returns single row or error
// Purpose: Retrieves a specific core value by ID for editing
// Parameters:
//  1. id (INTEGER): core value primary key
//
// Return type: single core_values row
func (q *Queries) GetCoreValue(ctx context.Context, id int64) (CoreValue, error) {
	row := q.db.QueryRowContext(ctx, getCoreValue, id)
	var i CoreValue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, year, title, description, is_current, display_order, created_at FROM milestones WHERE id = ? LIMIT 1
`

// sqlc annotation: :one returns single milestone or error
// Purpose: Retrieves specific milestone for editing
// Parameters:
//  1. id (INTEGER): milestone primary key
//
// Return type: single milestones row
func (q *Queries) GetMilestone(ctx context.Context, id int64) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, getMilestone, id)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Title,
		&i.Description,
		&i.IsCurrent,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getMissionVisionValues = `-- name: GetMissionVisionValues :one

SELECT id, mission, vision, values_summary, mission_icon, vision_icon, values_icon, updated_at FROM mission_vision_values ORDER BY id DESC LIMIT 1
`

// ====================================================================
// MISSION, VISION & VALUES
// ====================================================================
// sqlc annotation: :one returns single row or error
// Purpose: Retrieves the latest mission/vision/values content block
// Parameters: none
// Return type: single mission_vision_values row
// Note: ORDER BY id DESC ensures we get the most recent version
func (q *Queries) GetMissionVisionValues(ctx context.Context) (MissionVisionValue, error) {
	row := q.db.QueryRowContext(ctx, getMissionVisionValues)
	var i MissionVisionValue
	err := row.Scan(
		&i.ID,
		&i.Mission,
		&i.Vision,
		&i.ValuesSummary,
		&i.MissionIcon,
		&i.VisionIcon,
		&i.ValuesIcon,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertifications = `-- name: ListCertifications :many

SELECT id, name, abbreviation, description, icon, display_order, created_at FROM certifications ORDER BY display_order ASC
`

// ====================================================================
// CERTIFICATIONS & CREDENTIALS
// ====================================================================
// sqlc annotation: :many returns slice of certification rows
// Purpose: Lists all certifications/credentials for About page display
// Parameters: none
// Return type: slice of certifications rows
// Note: ORDER BY display_order for custom presentation sequence
func (q *Queries) ListCertifications(ctx context.Context) ([]Certification, error) {
	rows, err := q.db.QueryContext(ctx, listCertifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certification{}
	for rows.Next() {
		var i Certification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Abbreviation,
			&i.Description,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreValues = `-- name: ListCoreValues :many

SELECT id, title, description, icon, display_order, created_at FROM core_values ORDER BY display_order ASC
`

// ====================================================================
// CORE VALUES
// ====================================================================
// sqlc annotation: :many returns slice of rows (0 or more)
// Purpose: Lists all core values for display on About page
// Parameters: none
// Return type: slice of core_values rows
// Note: ORDER BY display_order ensures consistent presentation order
func (q *Queries) ListCoreValues(ctx context.Context) ([]CoreValue, error) {
	rows, err := q.db.QueryContext(ctx, listCoreValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreValue{}
	for rows.Next() {
		var i CoreValue
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestones = `-- name: ListMilestones :many

SELECT id, year, title, description, is_current, display_order, created_at FROM milestones ORDER BY display_order ASC
`

// ====================================================================
// MILESTONES / COMPANY TIMELINE
// ====================================================================
// sqlc annotation: :many returns slice of milestone rows
// Purpose: Lists all company milestones for timeline display
// Parameters: none
// Return type: slice of milestones rows
// Note: ORDER BY display_order for chronological or custom ordering
func (q *Queries) ListMilestones(ctx context.Context) ([]Milestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Title,
			&i.Description,
			&i.IsCurrent,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertification = `-- name: UpdateCertification :one
UPDATE certifications SET name = ?, abbreviation = ?, description = ?, icon = ?, display_order = ?
WHERE id = ? RETURNING id, name, abbreviation, description, icon, display_order, created_at
`

type UpdateCertificationParams struct {
	Name         string         `json:"name"`
	Abbreviation string         `json:"abbreviation"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	DisplayOrder int64          `json:"display_order"`
	ID           int64          `json:"id"`
}

// sqlc annotation: :one returns updated row
// Purpose: Updates an existing certification entry
// Parameters (6 positional):
//
//	1-5. updated field values
//	6. id (INTEGER): which certification to update
//
// Return type: updated certification row
func (q *Queries) UpdateCertification(ctx context.Context, arg UpdateCertificationParams) (Certification, error) {
	row := q.db.QueryRowContext(ctx, updateCertification,
		arg.Name,
		arg.Abbreviation,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
		arg.ID,
	)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateCoreValue = `-- name: UpdateCoreValue :one
UPDATE core_values SET title = ?, description = ?, icon = ?, display_order = ?
WHERE id = ? RETURNING id, title, description, icon, display_order, created_at
`

type UpdateCoreValueParams struct {
	Title        string `json:"title"`
	Description  string `json:"description"`
	Icon         string `json:"icon"`
	DisplayOrder int64  `json:"display_order"`
	ID           int64  `json:"id"`
}

// sqlc annotation: :one returns the updated row
// Purpose: Updates an existing core value
// Parameters (5 positional):
//  1. title (TEXT): updated title
//  2. description (TEXT): updated description
//  3. icon (TEXT): updated icon
//  4. display_order (INTEGER): updated sort position
//  5. id (INTEGER): which core value to update (WHERE clause)
//
// Return type: updated row with new values
func (q *Queries) UpdateCoreValue(ctx context.Context, arg UpdateCoreValueParams) (CoreValue, error) {
	row := q.db.QueryRowContext(ctx, updateCoreValue,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.DisplayOrder,
		arg.ID,
	)
	var i CoreValue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones SET year = ?, title = ?, description = ?, is_current = ?, display_order = ?
WHERE id = ? RETURNING id, year, title, description, is_current, display_order, created_at
`

type UpdateMilestoneParams struct {
	Year         int64  `json:"year"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	IsCurrent    int64  `json:"is_current"`
	DisplayOrder int64  `json:"display_order"`
	ID           int64  `json:"id"`
}

// sqlc annotation: :one returns updated row
// Purpose: Updates an existing milestone entry
// Parameters (6 positional):
//
//	1-5. updated field values (year, title, description, is_current, display_order)
//	6. id (INTEGER): which milestone to update
//
// Return type: updated milestone row
func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, updateMilestone,
		arg.Year,
		arg.Title,
		arg.Description,
		arg.IsCurrent,
		arg.DisplayOrder,
		arg.ID,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Title,
		&i.Description,
		&i.IsCurrent,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCompanyOverview = `-- name: UpsertCompanyOverview :one
INSERT INTO company_overview (
    headline, tagline, description_main, description_secondary,
    description_tertiary, hero_image_url, company_image_url
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, headline, tagline, description_main, description_secondary, description_tertiary, hero_image_url, company_image_url, updated_at
`

type UpsertCompanyOverviewParams struct {
	Headline             string         `json:"headline"`
	Tagline              string         `json:"tagline"`
	DescriptionMain      string         `json:"description_main"`
	DescriptionSecondary sql.NullString `json:"description_secondary"`
	DescriptionTertiary  sql.NullString `json:"description_tertiary"`
	HeroImageUrl         sql.NullString `json:"hero_image_url"`
	CompanyImageUrl      sql.NullString `json:"company_image_url"`
}

// sqlc annotation: :one returns the newly inserted row
// Purpose: Creates a new company overview entry (upsert pattern via insert-only)
// Parameters (7 positional):
//  1. headline (TEXT): main hero headline
//  2. tagline (TEXT): supporting tagline
//  3. description_main (TEXT): primary description paragraph
//  4. description_secondary (TEXT): secondary description
//  5. description_tertiary (TEXT): tertiary description
//  6. hero_image_url (TEXT): hero section image
//  7. company_image_url (TEXT): additional company image
//
// Return type: complete inserted row with generated ID and timestamps
// Note: Called "Upsert" but actually inserts new row each time
func (q *Queries) UpsertCompanyOverview(ctx context.Context, arg UpsertCompanyOverviewParams) (CompanyOverview, error) {
	row := q.db.QueryRowContext(ctx, upsertCompanyOverview,
		arg.Headline,
		arg.Tagline,
		arg.DescriptionMain,
		arg.DescriptionSecondary,
		arg.DescriptionTertiary,
		arg.HeroImageUrl,
		arg.CompanyImageUrl,
	)
	var i CompanyOverview
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Tagline,
		&i.DescriptionMain,
		&i.DescriptionSecondary,
		&i.DescriptionTertiary,
		&i.HeroImageUrl,
		&i.CompanyImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMissionVisionValues = `-- name: UpsertMissionVisionValues :one
INSERT INTO mission_vision_values (
    mission, vision, values_summary,
    mission_icon, vision_icon, values_icon
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, mission, vision, values_summary, mission_icon, vision_icon, values_icon, updated_at
`

type UpsertMissionVisionValuesParams struct {
	Mission       string         `json:"mission"`
	Vision        string         `json:"vision"`
	ValuesSummary sql.NullString `json:"values_summary"`
	MissionIcon   string         `json:"mission_icon"`
	VisionIcon    string         `json:"vision_icon"`
	ValuesIcon    string         `json:"values_icon"`
}

// sqlc annotation: :one returns inserted row
// Purpose: Creates new mission/vision/values entry
// Parameters (6 positional):
//  1. mission (TEXT): company mission statement
//  2. vision (TEXT): company vision statement
//  3. values_summary (TEXT): overview of company values
//  4. mission_icon (TEXT): icon identifier for mission
//  5. vision_icon (TEXT): icon identifier for vision
//  6. values_icon (TEXT): icon identifier for values
//
// Return type: complete inserted row
func (q *Queries) UpsertMissionVisionValues(ctx context.Context, arg UpsertMissionVisionValuesParams) (MissionVisionValue, error) {
	row := q.db.QueryRowContext(ctx, upsertMissionVisionValues,
		arg.Mission,
		arg.Vision,
		arg.ValuesSummary,
		arg.MissionIcon,
		arg.VisionIcon,
		arg.ValuesIcon,
	)
	var i MissionVisionValue
	err := row.Scan(
		&i.ID,
		&i.Mission,
		&i.Vision,
		&i.ValuesSummary,
		&i.MissionIcon,
		&i.VisionIcon,
		&i.ValuesIcon,
		&i.UpdatedAt,
	)
	return i, err
}
