// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_log.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActivityLogs = `-- name: CountActivityLogs :one
SELECT COUNT(*) FROM activity_log
WHERE
    (CAST(?1 AS TEXT) = '' OR action = ?1)
    AND (CAST(?2 AS TEXT) = '' OR description LIKE '%' || ?2 || '%')
`

type CountActivityLogsParams struct {
	FilterAction string `json:"filter_action"`
	FilterSearch string `json:"filter_search"`
}

func (q *Queries) CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityLogs, arg.FilterAction, arg.FilterSearch)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_log (user_id, action, resource_type, resource_id, resource_title, description)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateActivityLogParams struct {
	UserID        sql.NullInt64  `json:"user_id"`
	Action        string         `json:"action"`
	ResourceType  string         `json:"resource_type"`
	ResourceID    sql.NullInt64  `json:"resource_id"`
	ResourceTitle sql.NullString `json:"resource_title"`
	Description   string         `json:"description"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, createActivityLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceTitle,
		arg.Description,
	)
	return err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT id, user_id, "action", resource_type, resource_id, resource_title, description, created_at FROM activity_log
WHERE
    (CAST(?1 AS TEXT) = '' OR action = ?1)
    AND (CAST(?2 AS TEXT) = '' OR description LIKE '%' || ?2 || '%')
ORDER BY created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListActivityLogsParams struct {
	FilterAction string `json:"filter_action"`
	FilterSearch string `json:"filter_search"`
	PageOffset   int64  `json:"page_offset"`
	PageLimit    int64  `json:"page_limit"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogs,
		arg.FilterAction,
		arg.FilterSearch,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceTitle,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
