// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_log.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActivityLogs = `-- name: CountActivityLogs :one
SELECT COUNT(*) FROM activity_log
WHERE
    -- Same filter logic as ListActivityLogs for consistency
    (CAST(?1 AS TEXT) = '' OR action = ?1)
    AND (CAST(?2 AS TEXT) = '' OR description LIKE '%' || ?2 || '%')
`

type CountActivityLogsParams struct {
	FilterAction string `json:"filter_action"`
	FilterSearch string `json:"filter_search"`
}

// sqlc annotation: :one returns single integer count
// Purpose: Counts total activity logs matching filters (for pagination UI)
// Parameters (named):
//
//	@filter_action (TEXT): same filter as ListActivityLogs
//	@filter_search (TEXT): same search filter as ListActivityLogs
//
// Return type: single integer COUNT(*) value
// Note: WHERE clause MUST match ListActivityLogs exactly for accurate pagination
func (q *Queries) CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityLogs, arg.FilterAction, arg.FilterSearch)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec

INSERT INTO activity_log (user_id, action, resource_type, resource_id, resource_title, description)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateActivityLogParams struct {
	UserID        sql.NullInt64  `json:"user_id"`
	Action        string         `json:"action"`
	ResourceType  string         `json:"resource_type"`
	ResourceID    sql.NullInt64  `json:"resource_id"`
	ResourceTitle sql.NullString `json:"resource_title"`
	Description   string         `json:"description"`
}

// ====================================================================
// ACTIVITY LOG QUERIES
// ====================================================================
// This file manages audit trail queries for tracking admin user actions
// throughout the CMS. All create/update/delete operations should be logged
// to provide accountability and change history.
//
// Managed entity:
// - activity_log: stores admin actions with context (who, what, when, where)
// ====================================================================
// sqlc annotation: :exec returns no data, only error or success
// Purpose: Records a new activity log entry when admins perform actions
// Parameters (6 positional):
//  1. user_id (INTEGER): ID of admin user performing the action
//  2. action (TEXT): type of action (e.g., "created", "updated", "deleted")
//  3. resource_type (TEXT): entity being modified (e.g., "blog_post", "product")
//  4. resource_id (INTEGER): ID of the modified resource
//  5. resource_title (TEXT): human-readable title of modified resource
//  6. description (TEXT): detailed description of the action
//
// Return type: none (exec only returns error status)
// Note: created_at timestamp is auto-generated by database
func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, createActivityLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceTitle,
		arg.Description,
	)
	return err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT id, user_id, "action", resource_type, resource_id, resource_title, description, created_at FROM activity_log
WHERE
    -- Filter by action type if provided, otherwise include all actions
    (CAST(?1 AS TEXT) = '' OR action = ?1)
    -- Filter by search term in description if provided
    AND (CAST(?2 AS TEXT) = '' OR description LIKE '%' || ?2 || '%')
ORDER BY created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListActivityLogsParams struct {
	FilterAction string `json:"filter_action"`
	FilterSearch string `json:"filter_search"`
	PageOffset   int64  `json:"page_offset"`
	PageLimit    int64  `json:"page_limit"`
}

// sqlc annotation: :many returns slice of activity_log rows
// Purpose: Retrieves paginated, filtered activity log entries for admin dashboard
// Parameters (named parameters using @ prefix):
//
//	@filter_action (TEXT): filter by action type (empty string = no filter)
//	@filter_search (TEXT): search term for description field (empty = no filter)
//	@page_limit (INTEGER): number of results per page
//	@page_offset (INTEGER): pagination offset (page_number * page_limit)
//
// Return type: slice of activity_log rows
// Complex WHERE logic:
//   - CAST to TEXT handles nullable/empty filter parameters safely
//   - Empty string check allows "no filter" without complex null handling
//   - LIKE with wildcards enables partial text search in descriptions
//
// Note: Always ordered by created_at DESC to show newest actions first
func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogs,
		arg.FilterAction,
		arg.FilterSearch,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceTitle,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
