// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (email, password_hash, display_name, role)
VALUES (?, ?, ?, ?)
RETURNING id, email, display_name, role, created_at
`

type CreateAdminUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Role         string `json:"role"`
}

type CreateAdminUserRow struct {
	ID          int64     `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

// sqlc annotation: :one returns the newly created user (partial)
// Purpose: Creates a new admin user account
// Parameters (4 positional):
//  1. email (TEXT): unique email address for login
//  2. password_hash (TEXT): bcrypt/argon2 hashed password
//  3. display_name (TEXT): human-friendly name for UI
//  4. role (TEXT): permission level (e.g., "admin", "editor", "viewer")
//
// Return type: partial row (id, email, display_name, role, created_at)
// Note: Does NOT return password_hash for security
//
//	is_active defaults to 1 (true) via schema default
//	UNIQUE constraint on email enforced at database level
func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
	)
	var i CreateAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one

SELECT id, email, password_hash, display_name, role, is_active, last_login_at
FROM admin_users
WHERE email = ? AND is_active = 1
LIMIT 1
`

type GetAdminUserByEmailRow struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	DisplayName  string       `json:"display_name"`
	Role         string       `json:"role"`
	IsActive     int64        `json:"is_active"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
}

// ====================================================================
// ADMIN USERS QUERIES
// ====================================================================
// This file manages authentication and admin user account operations.
// These queries handle login verification, user creation, and admin
// user management within the CMS.
//
// Managed entity:
// - admin_users: CMS admin accounts with roles and permissions
//
// Security notes:
// - password_hash is stored, never plain text passwords
// - is_active flag allows soft-disable of accounts
// - last_login_at tracks account activity
// ====================================================================
// sqlc annotation: :one returns single admin_users row or error
// Purpose: Retrieves admin user by email for authentication during login
// Parameters:
//  1. email (TEXT): email address to look up
//
// Return type: partial admin_users row (excludes sensitive created_at/updated_at)
// WHERE clause notes:
//   - email = ? ensures exact match (case-sensitive in SQLite)
//   - is_active = 1 prevents disabled accounts from logging in
//
// Security: Only returns active accounts; password_hash included for verification
func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (GetAdminUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByEmail, email)
	var i GetAdminUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, display_name, role, is_active, created_at, last_login_at
FROM admin_users
ORDER BY created_at DESC
`

type ListAdminUsersRow struct {
	ID          int64        `json:"id"`
	Email       string       `json:"email"`
	DisplayName string       `json:"display_name"`
	Role        string       `json:"role"`
	IsActive    int64        `json:"is_active"`
	CreatedAt   time.Time    `json:"created_at"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
}

// sqlc annotation: :many returns slice of admin_users rows
// Purpose: Lists all admin users for management dashboard
// Parameters: none
// Return type: slice of partial admin_users rows (excludes password_hash)
// Note: Ordered by created_at DESC to show newest accounts first
//
//	Does NOT return password_hash for security
func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE admin_users
SET last_login_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

// sqlc annotation: :exec returns no data, only error or success
// Purpose: Updates last_login_at timestamp after successful authentication
// Parameters:
//  1. id (INTEGER): admin user ID to update
//
// Return type: none
// Note: CURRENT_TIMESTAMP uses database server time (UTC in SQLite)
//
//	updated_at also refreshed to track any account modifications
func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, id)
	return err
}
