// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blog_tags.sql

package sqlc

import (
	"context"
)

const createBlogTag = `-- name: CreateBlogTag :one
INSERT INTO blog_tags (name, slug)
VALUES (?, ?)
RETURNING id, name, slug, created_at
`

type CreateBlogTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// sqlc annotation: :one returns the created tag
// Purpose: Creates a new blog tag
// Parameters (2 positional):
//  1. name (TEXT): display name of tag
//  2. slug (TEXT): URL-safe identifier (must be unique)
//
// Return type: complete inserted row with ID
func (q *Queries) CreateBlogTag(ctx context.Context, arg CreateBlogTagParams) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, createBlogTag, arg.Name, arg.Slug)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlogTag = `-- name: DeleteBlogTag :exec
DELETE FROM blog_tags WHERE id = ?
`

// sqlc annotation: :exec returns no data
// Purpose: Permanently removes a blog tag
// Parameters:
//  1. id (INTEGER): tag to delete
//
// Return type: none
// Note: May fail if tag is still associated with posts (foreign key constraint)
//
//	Consider removing tag associations first or using ON DELETE CASCADE
func (q *Queries) DeleteBlogTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlogTag, id)
	return err
}

const getBlogTag = `-- name: GetBlogTag :one
SELECT id, name, slug, created_at FROM blog_tags WHERE id = ?
`

// sqlc annotation: :one returns single blog tag by ID
// Purpose: Retrieves specific tag for editing
// Parameters:
//  1. id (INTEGER): tag primary key
//
// Return type: single blog_tags row
func (q *Queries) GetBlogTag(ctx context.Context, id int64) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, getBlogTag, id)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getBlogTagBySlug = `-- name: GetBlogTagBySlug :one
SELECT id, name, slug, created_at FROM blog_tags WHERE slug = ?
`

// sqlc annotation: :one returns single blog tag by slug
// Purpose: Retrieves tag by URL slug (for tag archive pages if implemented)
// Parameters:
//  1. slug (TEXT): URL-safe tag identifier
//
// Return type: single blog_tags row
// Note: slug should be UNIQUE via database constraint
func (q *Queries) GetBlogTagBySlug(ctx context.Context, slug string) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, getBlogTagBySlug, slug)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listAllBlogTags = `-- name: ListAllBlogTags :many

SELECT id, name, slug, created_at FROM blog_tags ORDER BY name
`

// ====================================================================
// BLOG TAGS QUERIES
// ====================================================================
// This file manages blog tags (keywords/topics) used for cross-referencing
// and organizing blog posts. Tags enable many-to-many relationships with
// posts (one post can have multiple tags, one tag can be on multiple posts).
//
// Managed entity:
// - blog_tags: tag definitions (name, slug)
//
// Note: Tags are linked to posts via blog_post_tags junction table
// ====================================================================
// sqlc annotation: :many returns slice of all blog tags
// Purpose: Lists all available tags for admin management or tag selection
// Parameters: none
// Return type: slice of blog_tags rows
// ORDER BY name: alphabetical sorting for easier browsing
func (q *Queries) ListAllBlogTags(ctx context.Context) ([]BlogTag, error) {
	rows, err := q.db.QueryContext(ctx, listAllBlogTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogTag{}
	for rows.Next() {
		var i BlogTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBlogTags = `-- name: SearchBlogTags :many
SELECT id, name, slug, created_at FROM blog_tags WHERE name LIKE ? ORDER BY name LIMIT 10
`

// sqlc annotation: :many returns filtered tags for autocomplete
// Purpose: Searches tags by partial name match (for typeahead/autocomplete UI)
// Parameters:
//  1. search_pattern (TEXT): LIKE pattern (e.g., "%java%")
//
// Return type: slice of blog_tags (limited to 10 results)
// LIMIT 10: restricts results for autocomplete dropdown performance
func (q *Queries) SearchBlogTags(ctx context.Context, name string) ([]BlogTag, error) {
	rows, err := q.db.QueryContext(ctx, searchBlogTags, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogTag{}
	for rows.Next() {
		var i BlogTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogTag = `-- name: UpdateBlogTag :one
UPDATE blog_tags SET
    name = ?,
    slug = ?
WHERE id = ?
RETURNING id, name, slug, created_at
`

type UpdateBlogTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

// sqlc annotation: :one returns the updated tag
// Purpose: Updates an existing blog tag
// Parameters (3 positional):
//  1. name (TEXT): updated display name
//  2. slug (TEXT): updated slug
//  3. id (INTEGER): which tag to update (WHERE clause)
//
// Return type: updated blog_tags row
func (q *Queries) UpdateBlogTag(ctx context.Context, arg UpdateBlogTagParams) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, updateBlogTag, arg.Name, arg.Slug, arg.ID)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
