// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blog_categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBlogCategory = `-- name: CreateBlogCategory :one
INSERT INTO blog_categories (name, slug, color_hex, description, sort_order)
VALUES (?, ?, ?, ?, ?) RETURNING id, name, slug, color_hex, description, sort_order, created_at, updated_at
`

type CreateBlogCategoryParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	ColorHex    string         `json:"color_hex"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
}

func (q *Queries) CreateBlogCategory(ctx context.Context, arg CreateBlogCategoryParams) (BlogCategory, error) {
	row := q.db.QueryRowContext(ctx, createBlogCategory,
		arg.Name,
		arg.Slug,
		arg.ColorHex,
		arg.Description,
		arg.SortOrder,
	)
	var i BlogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ColorHex,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlogCategory = `-- name: DeleteBlogCategory :exec
DELETE FROM blog_categories WHERE id = ?
`

func (q *Queries) DeleteBlogCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlogCategory, id)
	return err
}

const getBlogCategory = `-- name: GetBlogCategory :one
SELECT id, name, slug, color_hex, description, sort_order, created_at, updated_at FROM blog_categories WHERE id = ? LIMIT 1
`

func (q *Queries) GetBlogCategory(ctx context.Context, id int64) (BlogCategory, error) {
	row := q.db.QueryRowContext(ctx, getBlogCategory, id)
	var i BlogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ColorHex,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlogCategoryBySlug = `-- name: GetBlogCategoryBySlug :one
SELECT id, name, slug, color_hex, description, sort_order, created_at, updated_at FROM blog_categories WHERE slug = ? LIMIT 1
`

func (q *Queries) GetBlogCategoryBySlug(ctx context.Context, slug string) (BlogCategory, error) {
	row := q.db.QueryRowContext(ctx, getBlogCategoryBySlug, slug)
	var i BlogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ColorHex,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlogCategories = `-- name: ListBlogCategories :many
SELECT id, name, slug, color_hex, description, sort_order, created_at, updated_at FROM blog_categories ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListBlogCategories(ctx context.Context) ([]BlogCategory, error) {
	rows, err := q.db.QueryContext(ctx, listBlogCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogCategory{}
	for rows.Next() {
		var i BlogCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ColorHex,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogCategory = `-- name: UpdateBlogCategory :one
UPDATE blog_categories SET name = ?, slug = ?, color_hex = ?, description = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, slug, color_hex, description, sort_order, created_at, updated_at
`

type UpdateBlogCategoryParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	ColorHex    string         `json:"color_hex"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateBlogCategory(ctx context.Context, arg UpdateBlogCategoryParams) (BlogCategory, error) {
	row := q.db.QueryRowContext(ctx, updateBlogCategory,
		arg.Name,
		arg.Slug,
		arg.ColorHex,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	var i BlogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ColorHex,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
