// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blog_tags.sql

package sqlc

import (
	"context"
)

const createBlogTag = `-- name: CreateBlogTag :one
INSERT INTO blog_tags (name, slug)
VALUES (?, ?)
RETURNING id, name, slug, created_at
`

type CreateBlogTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateBlogTag(ctx context.Context, arg CreateBlogTagParams) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, createBlogTag, arg.Name, arg.Slug)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlogTag = `-- name: DeleteBlogTag :exec
DELETE FROM blog_tags WHERE id = ?
`

func (q *Queries) DeleteBlogTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlogTag, id)
	return err
}

const getBlogTag = `-- name: GetBlogTag :one
SELECT id, name, slug, created_at FROM blog_tags WHERE id = ?
`

func (q *Queries) GetBlogTag(ctx context.Context, id int64) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, getBlogTag, id)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getBlogTagBySlug = `-- name: GetBlogTagBySlug :one
SELECT id, name, slug, created_at FROM blog_tags WHERE slug = ?
`

func (q *Queries) GetBlogTagBySlug(ctx context.Context, slug string) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, getBlogTagBySlug, slug)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listAllBlogTags = `-- name: ListAllBlogTags :many
SELECT id, name, slug, created_at FROM blog_tags ORDER BY name
`

func (q *Queries) ListAllBlogTags(ctx context.Context) ([]BlogTag, error) {
	rows, err := q.db.QueryContext(ctx, listAllBlogTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogTag{}
	for rows.Next() {
		var i BlogTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBlogTags = `-- name: SearchBlogTags :many
SELECT id, name, slug, created_at FROM blog_tags WHERE name LIKE ? ORDER BY name LIMIT 10
`

func (q *Queries) SearchBlogTags(ctx context.Context, name string) ([]BlogTag, error) {
	rows, err := q.db.QueryContext(ctx, searchBlogTags, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogTag{}
	for rows.Next() {
		var i BlogTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogTag = `-- name: UpdateBlogTag :one
UPDATE blog_tags SET
    name = ?,
    slug = ?
WHERE id = ?
RETURNING id, name, slug, created_at
`

type UpdateBlogTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateBlogTag(ctx context.Context, arg UpdateBlogTagParams) (BlogTag, error) {
	row := q.db.QueryRowContext(ctx, updateBlogTag, arg.Name, arg.Slug, arg.ID)
	var i BlogTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
