// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: footer.sql

package sqlc

import (
	"context"
)

const createFooterColumnItem = `-- name: CreateFooterColumnItem :one
INSERT INTO footer_column_items (column_index, type, heading, content, sort_order)
VALUES (?, ?, ?, ?, ?)
RETURNING id, column_index, type, heading, content, sort_order
`

type CreateFooterColumnItemParams struct {
	ColumnIndex int64  `json:"column_index"`
	Type        string `json:"type"`
	Heading     string `json:"heading"`
	Content     string `json:"content"`
	SortOrder   int64  `json:"sort_order"`
}

func (q *Queries) CreateFooterColumnItem(ctx context.Context, arg CreateFooterColumnItemParams) (FooterColumnItem, error) {
	row := q.db.QueryRowContext(ctx, createFooterColumnItem,
		arg.ColumnIndex,
		arg.Type,
		arg.Heading,
		arg.Content,
		arg.SortOrder,
	)
	var i FooterColumnItem
	err := row.Scan(
		&i.ID,
		&i.ColumnIndex,
		&i.Type,
		&i.Heading,
		&i.Content,
		&i.SortOrder,
	)
	return i, err
}

const createFooterLegalLink = `-- name: CreateFooterLegalLink :one
INSERT INTO footer_legal_links (label, url, sort_order)
VALUES (?, ?, ?)
RETURNING id, label, url, sort_order
`

type CreateFooterLegalLinkParams struct {
	Label     string `json:"label"`
	Url       string `json:"url"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateFooterLegalLink(ctx context.Context, arg CreateFooterLegalLinkParams) (FooterLegalLink, error) {
	row := q.db.QueryRowContext(ctx, createFooterLegalLink, arg.Label, arg.Url, arg.SortOrder)
	var i FooterLegalLink
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Url,
		&i.SortOrder,
	)
	return i, err
}

const createFooterLink = `-- name: CreateFooterLink :one
INSERT INTO footer_links (column_item_id, label, url, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id, column_item_id, label, url, sort_order
`

type CreateFooterLinkParams struct {
	ColumnItemID int64  `json:"column_item_id"`
	Label        string `json:"label"`
	Url          string `json:"url"`
	SortOrder    int64  `json:"sort_order"`
}

func (q *Queries) CreateFooterLink(ctx context.Context, arg CreateFooterLinkParams) (FooterLink, error) {
	row := q.db.QueryRowContext(ctx, createFooterLink,
		arg.ColumnItemID,
		arg.Label,
		arg.Url,
		arg.SortOrder,
	)
	var i FooterLink
	err := row.Scan(
		&i.ID,
		&i.ColumnItemID,
		&i.Label,
		&i.Url,
		&i.SortOrder,
	)
	return i, err
}

const deleteAllFooterLegalLinks = `-- name: DeleteAllFooterLegalLinks :exec
DELETE FROM footer_legal_links
`

func (q *Queries) DeleteAllFooterLegalLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFooterLegalLinks)
	return err
}

const deleteFooterColumnItem = `-- name: DeleteFooterColumnItem :exec
DELETE FROM footer_column_items WHERE id = ?
`

func (q *Queries) DeleteFooterColumnItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFooterColumnItem, id)
	return err
}

const deleteFooterColumnItemsByIndex = `-- name: DeleteFooterColumnItemsByIndex :exec
DELETE FROM footer_column_items WHERE column_index >= ?
`

func (q *Queries) DeleteFooterColumnItemsByIndex(ctx context.Context, columnIndex int64) error {
	_, err := q.db.ExecContext(ctx, deleteFooterColumnItemsByIndex, columnIndex)
	return err
}

const deleteFooterLinksByColumnItem = `-- name: DeleteFooterLinksByColumnItem :exec
DELETE FROM footer_links WHERE column_item_id = ?
`

func (q *Queries) DeleteFooterLinksByColumnItem(ctx context.Context, columnItemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFooterLinksByColumnItem, columnItemID)
	return err
}

const getFooterColumnItem = `-- name: GetFooterColumnItem :one
SELECT id, column_index, type, heading, content, sort_order FROM footer_column_items WHERE id = ? LIMIT 1
`

func (q *Queries) GetFooterColumnItem(ctx context.Context, id int64) (FooterColumnItem, error) {
	row := q.db.QueryRowContext(ctx, getFooterColumnItem, id)
	var i FooterColumnItem
	err := row.Scan(
		&i.ID,
		&i.ColumnIndex,
		&i.Type,
		&i.Heading,
		&i.Content,
		&i.SortOrder,
	)
	return i, err
}

const listAllFooterLinks = `-- name: ListAllFooterLinks :many
SELECT id, column_item_id, label, url, sort_order FROM footer_links ORDER BY column_item_id, sort_order
`

func (q *Queries) ListAllFooterLinks(ctx context.Context) ([]FooterLink, error) {
	rows, err := q.db.QueryContext(ctx, listAllFooterLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FooterLink{}
	for rows.Next() {
		var i FooterLink
		if err := rows.Scan(
			&i.ID,
			&i.ColumnItemID,
			&i.Label,
			&i.Url,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFooterColumnItems = `-- name: ListFooterColumnItems :many
SELECT id, column_index, type, heading, content, sort_order FROM footer_column_items ORDER BY column_index, sort_order
`

func (q *Queries) ListFooterColumnItems(ctx context.Context) ([]FooterColumnItem, error) {
	rows, err := q.db.QueryContext(ctx, listFooterColumnItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FooterColumnItem{}
	for rows.Next() {
		var i FooterColumnItem
		if err := rows.Scan(
			&i.ID,
			&i.ColumnIndex,
			&i.Type,
			&i.Heading,
			&i.Content,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFooterLegalLinks = `-- name: ListFooterLegalLinks :many
SELECT id, label, url, sort_order FROM footer_legal_links ORDER BY sort_order
`

func (q *Queries) ListFooterLegalLinks(ctx context.Context) ([]FooterLegalLink, error) {
	rows, err := q.db.QueryContext(ctx, listFooterLegalLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FooterLegalLink{}
	for rows.Next() {
		var i FooterLegalLink
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Url,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFooterLinks = `-- name: ListFooterLinks :many
SELECT id, column_item_id, label, url, sort_order FROM footer_links WHERE column_item_id = ? ORDER BY sort_order
`

func (q *Queries) ListFooterLinks(ctx context.Context, columnItemID int64) ([]FooterLink, error) {
	rows, err := q.db.QueryContext(ctx, listFooterLinks, columnItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FooterLink{}
	for rows.Next() {
		var i FooterLink
		if err := rows.Scan(
			&i.ID,
			&i.ColumnItemID,
			&i.Label,
			&i.Url,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFooterColumnItem = `-- name: UpdateFooterColumnItem :exec
UPDATE footer_column_items
SET column_index = ?, type = ?, heading = ?, content = ?, sort_order = ?
WHERE id = ?
`

type UpdateFooterColumnItemParams struct {
	ColumnIndex int64  `json:"column_index"`
	Type        string `json:"type"`
	Heading     string `json:"heading"`
	Content     string `json:"content"`
	SortOrder   int64  `json:"sort_order"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateFooterColumnItem(ctx context.Context, arg UpdateFooterColumnItemParams) error {
	_, err := q.db.ExecContext(ctx, updateFooterColumnItem,
		arg.ColumnIndex,
		arg.Type,
		arg.Heading,
		arg.Content,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateFooterSettings = `-- name: UpdateFooterSettings :exec
UPDATE settings
SET footer_columns = ?,
    footer_bg_style = ?,
    footer_show_social = ?,
    footer_social_style = ?,
    footer_copyright = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateFooterSettingsParams struct {
	FooterColumns     int64  `json:"footer_columns"`
	FooterBgStyle     string `json:"footer_bg_style"`
	FooterShowSocial  int64  `json:"footer_show_social"`
	FooterSocialStyle string `json:"footer_social_style"`
	FooterCopyright   string `json:"footer_copyright"`
}

func (q *Queries) UpdateFooterSettings(ctx context.Context, arg UpdateFooterSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateFooterSettings,
		arg.FooterColumns,
		arg.FooterBgStyle,
		arg.FooterShowSocial,
		arg.FooterSocialStyle,
		arg.FooterCopyright,
	)
	return err
}
