// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: industries.sql

package sqlc

import (
	"context"
)

const createIndustry = `-- name: CreateIndustry :one
INSERT INTO industries (name, slug, icon, description, sort_order)
VALUES (?, ?, ?, ?, ?) RETURNING id, name, slug, icon, description, sort_order, created_at, updated_at
`

type CreateIndustryParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Icon        string `json:"icon"`
	Description string `json:"description"`
	SortOrder   int64  `json:"sort_order"`
}

func (q *Queries) CreateIndustry(ctx context.Context, arg CreateIndustryParams) (Industry, error) {
	row := q.db.QueryRowContext(ctx, createIndustry,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Description,
		arg.SortOrder,
	)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIndustry = `-- name: DeleteIndustry :exec
DELETE FROM industries WHERE id = ?
`

func (q *Queries) DeleteIndustry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIndustry, id)
	return err
}

const getIndustry = `-- name: GetIndustry :one
SELECT id, name, slug, icon, description, sort_order, created_at, updated_at FROM industries WHERE id = ? LIMIT 1
`

func (q *Queries) GetIndustry(ctx context.Context, id int64) (Industry, error) {
	row := q.db.QueryRowContext(ctx, getIndustry, id)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndustryBySlug = `-- name: GetIndustryBySlug :one
SELECT id, name, slug, icon, description, sort_order, created_at, updated_at FROM industries WHERE slug = ? LIMIT 1
`

func (q *Queries) GetIndustryBySlug(ctx context.Context, slug string) (Industry, error) {
	row := q.db.QueryRowContext(ctx, getIndustryBySlug, slug)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndustries = `-- name: ListIndustries :many
SELECT id, name, slug, icon, description, sort_order, created_at, updated_at FROM industries ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListIndustries(ctx context.Context) ([]Industry, error) {
	rows, err := q.db.QueryContext(ctx, listIndustries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Industry{}
	for rows.Next() {
		var i Industry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndustry = `-- name: UpdateIndustry :one
UPDATE industries SET name = ?, slug = ?, icon = ?, description = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, slug, icon, description, sort_order, created_at, updated_at
`

type UpdateIndustryParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Icon        string `json:"icon"`
	Description string `json:"description"`
	SortOrder   int64  `json:"sort_order"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateIndustry(ctx context.Context, arg UpdateIndustryParams) (Industry, error) {
	row := q.db.QueryRowContext(ctx, updateIndustry,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
