// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: industries.sql

package sqlc

import (
	"context"
)

const createIndustry = `-- name: CreateIndustry :one
INSERT INTO industries (name, slug, icon, description, sort_order)
VALUES (?, ?, ?, ?, ?) RETURNING id, name, slug, icon, description, sort_order, created_at, updated_at
`

type CreateIndustryParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Icon        string `json:"icon"`
	Description string `json:"description"`
	SortOrder   int64  `json:"sort_order"`
}

// Inserts a new industry record and returns the created record.
//
// Parameters:
//
//	$1 (TEXT) - name: Display name of the industry
//	$2 (TEXT) - slug: URL-safe identifier
//	$3 (TEXT) - icon: Icon identifier or CSS class (optional)
//	$4 (TEXT) - description: Industry description (optional)
//	$5 (INTEGER) - sort_order: Display position (lower = higher priority)
//
// Returns: Industry - The newly created industry record with auto-generated ID and timestamps
//
// Note: RETURNING * returns all columns including auto-generated created_at, updated_at
func (q *Queries) CreateIndustry(ctx context.Context, arg CreateIndustryParams) (Industry, error) {
	row := q.db.QueryRowContext(ctx, createIndustry,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Description,
		arg.SortOrder,
	)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIndustry = `-- name: DeleteIndustry :exec
DELETE FROM industries WHERE id = ?
`

// Permanently deletes an industry record.
//
// Parameters:
//
//	$1 (INTEGER) - industry ID to delete
//
// Returns: (none) - sqlc annotation :exec returns only row count, no data
//
// WARNING: This is a hard delete. Consider adding soft delete (is_active flag) for production.
// Note: May fail if foreign key constraints exist (e.g., solutions referencing this industry)
func (q *Queries) DeleteIndustry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIndustry, id)
	return err
}

const getIndustry = `-- name: GetIndustry :one
SELECT id, name, slug, icon, description, sort_order, created_at, updated_at FROM industries WHERE id = ? LIMIT 1
`

// Retrieves a single industry by its primary key ID.
//
// Parameters:
//
//	$1 (INTEGER) - industry ID
//
// Returns: Industry - Single industry record or error if not found
//
// Note: sqlc annotation :one expects exactly one row; will error if 0 or >1 rows returned
func (q *Queries) GetIndustry(ctx context.Context, id int64) (Industry, error) {
	row := q.db.QueryRowContext(ctx, getIndustry, id)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndustryBySlug = `-- name: GetIndustryBySlug :one
SELECT id, name, slug, icon, description, sort_order, created_at, updated_at FROM industries WHERE slug = ? LIMIT 1
`

// Retrieves a single industry by its URL-safe slug identifier.
//
// Parameters:
//
//	$1 (TEXT) - industry slug (e.g., "healthcare", "manufacturing")
//
// Returns: Industry - Single industry record or error if not found
//
// Use case: Frontend routing, displaying industry-specific content
// Note: Slugs should be unique (enforced by database constraint)
func (q *Queries) GetIndustryBySlug(ctx context.Context, slug string) (Industry, error) {
	row := q.db.QueryRowContext(ctx, getIndustryBySlug, slug)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndustries = `-- name: ListIndustries :many

SELECT id, name, slug, icon, description, sort_order, created_at, updated_at FROM industries ORDER BY sort_order ASC, name ASC
`

// ====================================================================
// INDUSTRIES QUERY FILE
// ====================================================================
// This file contains all SQL queries for managing industry categories.
// Industries are used to categorize solutions and content by target market
// or business sector (e.g., Healthcare, Manufacturing, Finance).
//
// Entity: industries table
// Related tables: solutions (via solution_industries junction table)
// ====================================================================
// Retrieves all industries ordered by custom sort order, then alphabetically.
//
// Parameters: none
// Returns: []Industry - Array of all industry records
//
// Sorting logic:
//  1. sort_order ASC - Custom display order (lower numbers appear first)
//  2. name ASC - Alphabetical fallback for same sort_order values
//
// Use case: Display industries in navigation, filters, or admin listing
func (q *Queries) ListIndustries(ctx context.Context) ([]Industry, error) {
	rows, err := q.db.QueryContext(ctx, listIndustries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Industry{}
	for rows.Next() {
		var i Industry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndustry = `-- name: UpdateIndustry :one
UPDATE industries SET name = ?, slug = ?, icon = ?, description = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, slug, icon, description, sort_order, created_at, updated_at
`

type UpdateIndustryParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Icon        string `json:"icon"`
	Description string `json:"description"`
	SortOrder   int64  `json:"sort_order"`
	ID          int64  `json:"id"`
}

// Updates an existing industry record and returns the updated record.
//
// Parameters:
//
//	$1 (TEXT) - name: Updated display name
//	$2 (TEXT) - slug: Updated URL-safe identifier
//	$3 (TEXT) - icon: Updated icon identifier
//	$4 (TEXT) - description: Updated description
//	$5 (INTEGER) - sort_order: Updated display position
//	$6 (INTEGER) - id: Primary key of industry to update
//
// Returns: Industry - The updated industry record
//
// Note: updated_at is automatically set to CURRENT_TIMESTAMP to track last modification
func (q *Queries) UpdateIndustry(ctx context.Context, arg UpdateIndustryParams) (Industry, error) {
	row := q.db.QueryRowContext(ctx, updateIndustry,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
