// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ActivityLog struct {
	ID            int64          `json:"id"`
	UserID        sql.NullInt64  `json:"user_id"`
	Action        string         `json:"action"`
	ResourceType  string         `json:"resource_type"`
	ResourceID    sql.NullInt64  `json:"resource_id"`
	ResourceTitle sql.NullString `json:"resource_title"`
	Description   string         `json:"description"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type AdminUser struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	DisplayName  string       `json:"display_name"`
	Role         string       `json:"role"`
	IsActive     int64        `json:"is_active"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
}

type BlogAuthor struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Title       string         `json:"title"`
	Bio         sql.NullString `json:"bio"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	LinkedinUrl sql.NullString `json:"linkedin_url"`
	Email       sql.NullString `json:"email"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type BlogCategory struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	ColorHex    string         `json:"color_hex"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type BlogPost struct {
	ID                 int64          `json:"id"`
	Title              string         `json:"title"`
	Slug               string         `json:"slug"`
	Excerpt            string         `json:"excerpt"`
	Body               string         `json:"body"`
	FeaturedImageUrl   sql.NullString `json:"featured_image_url"`
	FeaturedImageAlt   sql.NullString `json:"featured_image_alt"`
	CategoryID         int64          `json:"category_id"`
	AuthorID           int64          `json:"author_id"`
	MetaDescription    sql.NullString `json:"meta_description"`
	ReadingTimeMinutes sql.NullInt64  `json:"reading_time_minutes"`
	Status             string         `json:"status"`
	PublishedAt        sql.NullTime   `json:"published_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	MetaTitle          string         `json:"meta_title"`
	OgImage            string         `json:"og_image"`
}

type BlogPostProduct struct {
	BlogPostID   int64         `json:"blog_post_id"`
	ProductID    int64         `json:"product_id"`
	DisplayOrder sql.NullInt64 `json:"display_order"`
}

type BlogPostTag struct {
	BlogPostID int64 `json:"blog_post_id"`
	BlogTagID  int64 `json:"blog_tag_id"`
}

type BlogPostsFt struct {
	Title   string `json:"title"`
	Excerpt string `json:"excerpt"`
	Body    string `json:"body"`
}

type BlogTag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type CaseStudiesFt struct {
	Title            string `json:"title"`
	ClientName       string `json:"client_name"`
	ChallengeContent string `json:"challenge_content"`
	SolutionContent  string `json:"solution_content"`
}

type CaseStudy struct {
	ID               int64          `json:"id"`
	Slug             string         `json:"slug"`
	Title            string         `json:"title"`
	ClientName       string         `json:"client_name"`
	IndustryID       int64          `json:"industry_id"`
	HeroImageUrl     sql.NullString `json:"hero_image_url"`
	Summary          string         `json:"summary"`
	ChallengeTitle   string         `json:"challenge_title"`
	ChallengeContent string         `json:"challenge_content"`
	ChallengeBullets sql.NullString `json:"challenge_bullets"`
	SolutionTitle    string         `json:"solution_title"`
	SolutionContent  string         `json:"solution_content"`
	OutcomeTitle     string         `json:"outcome_title"`
	OutcomeContent   string         `json:"outcome_content"`
	MetaTitle        sql.NullString `json:"meta_title"`
	MetaDescription  sql.NullString `json:"meta_description"`
	IsPublished      int64          `json:"is_published"`
	DisplayOrder     int64          `json:"display_order"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	OgImage          string         `json:"og_image"`
}

type CaseStudyMetric struct {
	ID           int64     `json:"id"`
	CaseStudyID  int64     `json:"case_study_id"`
	MetricValue  string    `json:"metric_value"`
	MetricLabel  string    `json:"metric_label"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type CaseStudyProduct struct {
	ID           int64     `json:"id"`
	CaseStudyID  int64     `json:"case_study_id"`
	ProductID    int64     `json:"product_id"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type Certification struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Abbreviation string         `json:"abbreviation"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	DisplayOrder int64          `json:"display_order"`
	CreatedAt    time.Time      `json:"created_at"`
}

type CompanyOverview struct {
	ID                   int64          `json:"id"`
	Headline             string         `json:"headline"`
	Tagline              string         `json:"tagline"`
	DescriptionMain      string         `json:"description_main"`
	DescriptionSecondary sql.NullString `json:"description_secondary"`
	DescriptionTertiary  sql.NullString `json:"description_tertiary"`
	HeroImageUrl         sql.NullString `json:"hero_image_url"`
	CompanyImageUrl      sql.NullString `json:"company_image_url"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type ContactSubmission struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Phone          string         `json:"phone"`
	Company        string         `json:"company"`
	InquiryType    sql.NullString `json:"inquiry_type"`
	Message        string         `json:"message"`
	IpAddress      sql.NullString `json:"ip_address"`
	UserAgent      sql.NullString `json:"user_agent"`
	Status         string         `json:"status"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	SubmissionType string         `json:"submission_type"`
}

type CoreValue struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Icon         string    `json:"icon"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type FooterColumnItem struct {
	ID          int64  `json:"id"`
	ColumnIndex int64  `json:"column_index"`
	Type        string `json:"type"`
	Heading     string `json:"heading"`
	Content     string `json:"content"`
	SortOrder   int64  `json:"sort_order"`
}

type FooterLegalLink struct {
	ID        int64  `json:"id"`
	Label     string `json:"label"`
	Url       string `json:"url"`
	SortOrder int64  `json:"sort_order"`
}

type FooterLink struct {
	ID           int64  `json:"id"`
	ColumnItemID int64  `json:"column_item_id"`
	Label        string `json:"label"`
	Url          string `json:"url"`
	SortOrder    int64  `json:"sort_order"`
}

type HomepageCtum struct {
	ID               int64          `json:"id"`
	Headline         string         `json:"headline"`
	Description      sql.NullString `json:"description"`
	PrimaryCtaText   string         `json:"primary_cta_text"`
	PrimaryCtaUrl    string         `json:"primary_cta_url"`
	SecondaryCtaText sql.NullString `json:"secondary_cta_text"`
	SecondaryCtaUrl  sql.NullString `json:"secondary_cta_url"`
	BackgroundStyle  sql.NullString `json:"background_style"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type HomepageHero struct {
	ID               int64          `json:"id"`
	Headline         string         `json:"headline"`
	Subheadline      string         `json:"subheadline"`
	BadgeText        sql.NullString `json:"badge_text"`
	PrimaryCtaText   string         `json:"primary_cta_text"`
	PrimaryCtaUrl    string         `json:"primary_cta_url"`
	SecondaryCtaText sql.NullString `json:"secondary_cta_text"`
	SecondaryCtaUrl  sql.NullString `json:"secondary_cta_url"`
	BackgroundImage  sql.NullString `json:"background_image"`
	IsActive         int64          `json:"is_active"`
	DisplayOrder     int64          `json:"display_order"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type HomepageStat struct {
	ID           int64     `json:"id"`
	StatValue    string    `json:"stat_value"`
	StatLabel    string    `json:"stat_label"`
	DisplayOrder int64     `json:"display_order"`
	IsActive     int64     `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
}

type HomepageTestimonial struct {
	ID            int64          `json:"id"`
	Quote         string         `json:"quote"`
	AuthorName    string         `json:"author_name"`
	AuthorTitle   sql.NullString `json:"author_title"`
	AuthorCompany sql.NullString `json:"author_company"`
	AuthorImage   sql.NullString `json:"author_image"`
	Rating        int64          `json:"rating"`
	DisplayOrder  int64          `json:"display_order"`
	IsActive      int64          `json:"is_active"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Industry struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Icon        string    `json:"icon"`
	Description string    `json:"description"`
	SortOrder   int64     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type MediaFile struct {
	ID               int64          `json:"id"`
	Filename         string         `json:"filename"`
	OriginalFilename string         `json:"original_filename"`
	FilePath         string         `json:"file_path"`
	FileSize         int64          `json:"file_size"`
	MimeType         string         `json:"mime_type"`
	Width            sql.NullInt64  `json:"width"`
	Height           sql.NullInt64  `json:"height"`
	AltText          sql.NullString `json:"alt_text"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type Milestone struct {
	ID           int64     `json:"id"`
	Year         int64     `json:"year"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	IsCurrent    int64     `json:"is_current"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type MissionVisionValue struct {
	ID            int64          `json:"id"`
	Mission       string         `json:"mission"`
	Vision        string         `json:"vision"`
	ValuesSummary sql.NullString `json:"values_summary"`
	MissionIcon   string         `json:"mission_icon"`
	VisionIcon    string         `json:"vision_icon"`
	ValuesIcon    string         `json:"values_icon"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type NavigationItem struct {
	ID             int64          `json:"id"`
	MenuID         int64          `json:"menu_id"`
	ParentID       sql.NullInt64  `json:"parent_id"`
	Label          string         `json:"label"`
	LinkType       string         `json:"link_type"`
	Url            sql.NullString `json:"url"`
	PageIdentifier sql.NullString `json:"page_identifier"`
	OpenNewTab     sql.NullInt64  `json:"open_new_tab"`
	IsActive       sql.NullInt64  `json:"is_active"`
	SortOrder      sql.NullInt64  `json:"sort_order"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type NavigationMenu struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Location  string       `json:"location"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type OfficeLocation struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	AddressLine1 string         `json:"address_line1"`
	AddressLine2 sql.NullString `json:"address_line2"`
	City         string         `json:"city"`
	State        string         `json:"state"`
	PostalCode   string         `json:"postal_code"`
	Country      string         `json:"country"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	IsPrimary    int64          `json:"is_primary"`
	IsActive     int64          `json:"is_active"`
	DisplayOrder int64          `json:"display_order"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type PageSection struct {
	ID                  int64     `json:"id"`
	PageKey             string    `json:"page_key"`
	SectionKey          string    `json:"section_key"`
	Heading             string    `json:"heading"`
	Subheading          string    `json:"subheading"`
	Description         string    `json:"description"`
	Label               string    `json:"label"`
	PrimaryButtonText   string    `json:"primary_button_text"`
	PrimaryButtonUrl    string    `json:"primary_button_url"`
	SecondaryButtonText string    `json:"secondary_button_text"`
	SecondaryButtonUrl  string    `json:"secondary_button_url"`
	IsActive            bool      `json:"is_active"`
	DisplayOrder        int64     `json:"display_order"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type Partner struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	TierID       int64          `json:"tier_id"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Icon         sql.NullString `json:"icon"`
	WebsiteUrl   sql.NullString `json:"website_url"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	IsFeatured   int64          `json:"is_featured"`
}

type PartnerTestimonial struct {
	ID           int64     `json:"id"`
	PartnerID    int64     `json:"partner_id"`
	Quote        string    `json:"quote"`
	AuthorName   string    `json:"author_name"`
	AuthorTitle  string    `json:"author_title"`
	DisplayOrder int64     `json:"display_order"`
	IsActive     int64     `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
}

type PartnerTier struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	SortOrder   int64     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Product struct {
	ID              int64          `json:"id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Tagline         sql.NullString `json:"tagline"`
	Description     string         `json:"description"`
	Overview        sql.NullString `json:"overview"`
	CategoryID      int64          `json:"category_id"`
	Status          string         `json:"status"`
	IsFeatured      bool           `json:"is_featured"`
	FeaturedOrder   sql.NullInt64  `json:"featured_order"`
	MetaTitle       sql.NullString `json:"meta_title"`
	MetaDescription sql.NullString `json:"meta_description"`
	PrimaryImage    sql.NullString `json:"primary_image"`
	VideoUrl        sql.NullString `json:"video_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	OgImage         string         `json:"og_image"`
}

type ProductCategory struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  string         `json:"description"`
	Icon         string         `json:"icon"`
	ImageUrl     sql.NullString `json:"image_url"`
	ProductCount int64          `json:"product_count"`
	SortOrder    int64          `json:"sort_order"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type ProductCertification struct {
	ID                int64          `json:"id"`
	ProductID         int64          `json:"product_id"`
	CertificationName string         `json:"certification_name"`
	CertificationCode sql.NullString `json:"certification_code"`
	IconType          sql.NullString `json:"icon_type"`
	IconPath          sql.NullString `json:"icon_path"`
	DisplayOrder      int64          `json:"display_order"`
	CreatedAt         time.Time      `json:"created_at"`
}

type ProductDownload struct {
	ID            int64          `json:"id"`
	ProductID     int64          `json:"product_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	FileType      string         `json:"file_type"`
	FilePath      string         `json:"file_path"`
	FileSize      sql.NullInt64  `json:"file_size"`
	Version       sql.NullString `json:"version"`
	DownloadCount int64          `json:"download_count"`
	DisplayOrder  int64          `json:"display_order"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type ProductFeature struct {
	ID           int64     `json:"id"`
	ProductID    int64     `json:"product_id"`
	FeatureText  string    `json:"feature_text"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type ProductImage struct {
	ID           int64          `json:"id"`
	ProductID    int64          `json:"product_id"`
	ImagePath    string         `json:"image_path"`
	AltText      sql.NullString `json:"alt_text"`
	Caption      sql.NullString `json:"caption"`
	DisplayOrder int64          `json:"display_order"`
	IsThumbnail  bool           `json:"is_thumbnail"`
	CreatedAt    time.Time      `json:"created_at"`
}

type ProductSpec struct {
	ID           int64     `json:"id"`
	ProductID    int64     `json:"product_id"`
	SectionName  string    `json:"section_name"`
	SpecKey      string    `json:"spec_key"`
	SpecValue    string    `json:"spec_value"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type ProductsFt struct {
	Name        string `json:"name"`
	Tagline     string `json:"tagline"`
	Description string `json:"description"`
}

type Setting struct {
	ID                       int64     `json:"id"`
	SiteName                 string    `json:"site_name"`
	SiteTagline              string    `json:"site_tagline"`
	ContactEmail             string    `json:"contact_email"`
	ContactPhone             string    `json:"contact_phone"`
	Address                  string    `json:"address"`
	FooterText               string    `json:"footer_text"`
	MetaDescription          string    `json:"meta_description"`
	MetaKeywords             string    `json:"meta_keywords"`
	GoogleAnalyticsID        string    `json:"google_analytics_id"`
	SocialLinkedin           string    `json:"social_linkedin"`
	SocialTwitter            string    `json:"social_twitter"`
	SocialGithub             string    `json:"social_github"`
	CreatedAt                time.Time `json:"created_at"`
	UpdatedAt                time.Time `json:"updated_at"`
	SocialFacebook           string    `json:"social_facebook"`
	SocialYoutube            string    `json:"social_youtube"`
	SocialInstagram          string    `json:"social_instagram"`
	BusinessHours            string    `json:"business_hours"`
	AboutText                string    `json:"about_text"`
	ShowNavHome              bool      `json:"show_nav_home"`
	ShowNavAbout             bool      `json:"show_nav_about"`
	ShowNavProducts          bool      `json:"show_nav_products"`
	ShowNavSolutions         bool      `json:"show_nav_solutions"`
	ShowNavBlog              bool      `json:"show_nav_blog"`
	ShowNavPartners          bool      `json:"show_nav_partners"`
	ShowNavContact           bool      `json:"show_nav_contact"`
	ShowFooterAbout          bool      `json:"show_footer_about"`
	ShowFooterSocials        bool      `json:"show_footer_socials"`
	ShowFooterProducts       bool      `json:"show_footer_products"`
	ShowFooterSolutions      bool      `json:"show_footer_solutions"`
	ShowFooterResources      bool      `json:"show_footer_resources"`
	ShowFooterContact        bool      `json:"show_footer_contact"`
	NavLabelHome             string    `json:"nav_label_home"`
	NavLabelAbout            string    `json:"nav_label_about"`
	NavLabelProducts         string    `json:"nav_label_products"`
	NavLabelSolutions        string    `json:"nav_label_solutions"`
	NavLabelBlog             string    `json:"nav_label_blog"`
	NavLabelPartners         string    `json:"nav_label_partners"`
	NavLabelContact          string    `json:"nav_label_contact"`
	FooterHeadingProducts    string    `json:"footer_heading_products"`
	FooterHeadingSolutions   string    `json:"footer_heading_solutions"`
	FooterHeadingResources   string    `json:"footer_heading_resources"`
	FooterHeadingContact     string    `json:"footer_heading_contact"`
	HeaderLogoPath           string    `json:"header_logo_path"`
	HeaderLogoAlt            string    `json:"header_logo_alt"`
	HeaderCtaEnabled         bool      `json:"header_cta_enabled"`
	HeaderCtaText            string    `json:"header_cta_text"`
	HeaderCtaUrl             string    `json:"header_cta_url"`
	HeaderCtaStyle           string    `json:"header_cta_style"`
	HeaderShowPhone          bool      `json:"header_show_phone"`
	HeaderShowEmail          bool      `json:"header_show_email"`
	HeaderShowSocial         bool      `json:"header_show_social"`
	HeaderSocialStyle        string    `json:"header_social_style"`
	ShowNavCaseStudies       bool      `json:"show_nav_case_studies"`
	ShowNavWhitepapers       bool      `json:"show_nav_whitepapers"`
	NavLabelCaseStudies      string    `json:"nav_label_case_studies"`
	NavLabelWhitepapers      string    `json:"nav_label_whitepapers"`
	FooterColumns            int64     `json:"footer_columns"`
	FooterBgStyle            string    `json:"footer_bg_style"`
	FooterShowSocial         int64     `json:"footer_show_social"`
	FooterSocialStyle        string    `json:"footer_social_style"`
	FooterCopyright          string    `json:"footer_copyright"`
	HomepageShowHeroes       int64     `json:"homepage_show_heroes"`
	HomepageShowStats        int64     `json:"homepage_show_stats"`
	HomepageShowTestimonials int64     `json:"homepage_show_testimonials"`
	HomepageShowCta          int64     `json:"homepage_show_cta"`
	HomepageMaxHeroes        int64     `json:"homepage_max_heroes"`
	HomepageMaxStats         int64     `json:"homepage_max_stats"`
	HomepageMaxTestimonials  int64     `json:"homepage_max_testimonials"`
	HomepageHeroAutoplay     int64     `json:"homepage_hero_autoplay"`
	HomepageHeroInterval     int64     `json:"homepage_hero_interval"`
	AboutShowMission         int64     `json:"about_show_mission"`
	AboutShowMilestones      int64     `json:"about_show_milestones"`
	AboutShowCertifications  int64     `json:"about_show_certifications"`
	AboutShowTeam            int64     `json:"about_show_team"`
	ProductsPerPage          int64     `json:"products_per_page"`
	ProductsShowCategories   int64     `json:"products_show_categories"`
	ProductsShowSearch       int64     `json:"products_show_search"`
	ProductsDefaultSort      string    `json:"products_default_sort"`
	SolutionsPerPage         int64     `json:"solutions_per_page"`
	SolutionsShowIndustries  int64     `json:"solutions_show_industries"`
	SolutionsShowSearch      int64     `json:"solutions_show_search"`
	BlogPostsPerPage         int64     `json:"blog_posts_per_page"`
	BlogShowAuthor           int64     `json:"blog_show_author"`
	BlogShowDate             int64     `json:"blog_show_date"`
	BlogShowCategories       int64     `json:"blog_show_categories"`
	BlogShowTags             int64     `json:"blog_show_tags"`
	BlogShowSearch           int64     `json:"blog_show_search"`
}

type Solution struct {
	ID               int64          `json:"id"`
	Title            string         `json:"title"`
	Slug             string         `json:"slug"`
	Icon             string         `json:"icon"`
	ShortDescription string         `json:"short_description"`
	HeroImageUrl     sql.NullString `json:"hero_image_url"`
	HeroTitle        sql.NullString `json:"hero_title"`
	HeroDescription  sql.NullString `json:"hero_description"`
	OverviewContent  sql.NullString `json:"overview_content"`
	MetaDescription  sql.NullString `json:"meta_description"`
	ReferenceCode    sql.NullString `json:"reference_code"`
	IsPublished      sql.NullBool   `json:"is_published"`
	DisplayOrder     sql.NullInt64  `json:"display_order"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	MetaTitle        string         `json:"meta_title"`
	OgImage          string         `json:"og_image"`
}

type SolutionChallenge struct {
	ID           int64         `json:"id"`
	SolutionID   int64         `json:"solution_id"`
	Title        string        `json:"title"`
	Description  string        `json:"description"`
	Icon         string        `json:"icon"`
	DisplayOrder sql.NullInt64 `json:"display_order"`
}

type SolutionCta struct {
	ID                  int64          `json:"id"`
	SolutionID          int64          `json:"solution_id"`
	Heading             string         `json:"heading"`
	Subheading          sql.NullString `json:"subheading"`
	PrimaryButtonText   sql.NullString `json:"primary_button_text"`
	PrimaryButtonUrl    sql.NullString `json:"primary_button_url"`
	SecondaryButtonText sql.NullString `json:"secondary_button_text"`
	SecondaryButtonUrl  sql.NullString `json:"secondary_button_url"`
	PhoneNumber         sql.NullString `json:"phone_number"`
	SectionName         string         `json:"section_name"`
}

type SolutionPageFeature struct {
	ID           int64         `json:"id"`
	Title        string        `json:"title"`
	Description  string        `json:"description"`
	Icon         string        `json:"icon"`
	DisplayOrder sql.NullInt64 `json:"display_order"`
	IsActive     sql.NullBool  `json:"is_active"`
}

type SolutionProduct struct {
	ID           int64         `json:"id"`
	SolutionID   int64         `json:"solution_id"`
	ProductID    int64         `json:"product_id"`
	DisplayOrder sql.NullInt64 `json:"display_order"`
	IsFeatured   sql.NullBool  `json:"is_featured"`
}

type SolutionStat struct {
	ID           int64         `json:"id"`
	SolutionID   int64         `json:"solution_id"`
	Value        string        `json:"value"`
	Label        string        `json:"label"`
	DisplayOrder sql.NullInt64 `json:"display_order"`
}

type SolutionsListingCtum struct {
	ID                  int64          `json:"id"`
	Heading             string         `json:"heading"`
	Subheading          sql.NullString `json:"subheading"`
	PrimaryButtonText   sql.NullString `json:"primary_button_text"`
	PrimaryButtonUrl    sql.NullString `json:"primary_button_url"`
	SecondaryButtonText sql.NullString `json:"secondary_button_text"`
	SecondaryButtonUrl  sql.NullString `json:"secondary_button_url"`
	IsActive            sql.NullBool   `json:"is_active"`
}

type Whitepaper struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Description     string         `json:"description"`
	TopicID         int64          `json:"topic_id"`
	PdfFilePath     string         `json:"pdf_file_path"`
	FileSizeBytes   int64          `json:"file_size_bytes"`
	PageCount       sql.NullInt64  `json:"page_count"`
	PublishedDate   string         `json:"published_date"`
	IsPublished     int64          `json:"is_published"`
	CoverColorFrom  string         `json:"cover_color_from"`
	CoverColorTo    string         `json:"cover_color_to"`
	MetaDescription sql.NullString `json:"meta_description"`
	DownloadCount   int64          `json:"download_count"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	MetaTitle       string         `json:"meta_title"`
	OgImage         string         `json:"og_image"`
}

type WhitepaperDownload struct {
	ID               int64          `json:"id"`
	WhitepaperID     int64          `json:"whitepaper_id"`
	Name             string         `json:"name"`
	Email            string         `json:"email"`
	Company          string         `json:"company"`
	Designation      sql.NullString `json:"designation"`
	MarketingConsent int64          `json:"marketing_consent"`
	IpAddress        sql.NullString `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	CreatedAt        time.Time      `json:"created_at"`
}

type WhitepaperLearningPoint struct {
	ID           int64     `json:"id"`
	WhitepaperID int64     `json:"whitepaper_id"`
	PointText    string    `json:"point_text"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type WhitepaperTopic struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	ColorHex    string         `json:"color_hex"`
	Icon        string         `json:"icon"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
