// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_sections.sql

package sqlc

import (
	"context"
)

const getPageSection = `-- name: GetPageSection :one

SELECT id, page_key, section_key, heading, subheading, description, label, primary_button_text, primary_button_url, secondary_button_text, secondary_button_url, is_active, display_order, created_at, updated_at FROM page_sections
WHERE page_key = ? AND section_key = ? AND is_active = 1
`

type GetPageSectionParams struct {
	PageKey    string `json:"page_key"`
	SectionKey string `json:"section_key"`
}

// ====================================================================
// PAGE SECTIONS
// ====================================================================
func (q *Queries) GetPageSection(ctx context.Context, arg GetPageSectionParams) (PageSection, error) {
	row := q.db.QueryRowContext(ctx, getPageSection, arg.PageKey, arg.SectionKey)
	var i PageSection
	err := row.Scan(
		&i.ID,
		&i.PageKey,
		&i.SectionKey,
		&i.Heading,
		&i.Subheading,
		&i.Description,
		&i.Label,
		&i.PrimaryButtonText,
		&i.PrimaryButtonUrl,
		&i.SecondaryButtonText,
		&i.SecondaryButtonUrl,
		&i.IsActive,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageSectionByID = `-- name: GetPageSectionByID :one
SELECT id, page_key, section_key, heading, subheading, description, label, primary_button_text, primary_button_url, secondary_button_text, secondary_button_url, is_active, display_order, created_at, updated_at FROM page_sections WHERE id = ?
`

func (q *Queries) GetPageSectionByID(ctx context.Context, id int64) (PageSection, error) {
	row := q.db.QueryRowContext(ctx, getPageSectionByID, id)
	var i PageSection
	err := row.Scan(
		&i.ID,
		&i.PageKey,
		&i.SectionKey,
		&i.Heading,
		&i.Subheading,
		&i.Description,
		&i.Label,
		&i.PrimaryButtonText,
		&i.PrimaryButtonUrl,
		&i.SecondaryButtonText,
		&i.SecondaryButtonUrl,
		&i.IsActive,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPageSections = `-- name: ListAllPageSections :many
SELECT id, page_key, section_key, heading, subheading, description, label, primary_button_text, primary_button_url, secondary_button_text, secondary_button_url, is_active, display_order, created_at, updated_at FROM page_sections ORDER BY page_key, display_order ASC
`

func (q *Queries) ListAllPageSections(ctx context.Context) ([]PageSection, error) {
	rows, err := q.db.QueryContext(ctx, listAllPageSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageSection{}
	for rows.Next() {
		var i PageSection
		if err := rows.Scan(
			&i.ID,
			&i.PageKey,
			&i.SectionKey,
			&i.Heading,
			&i.Subheading,
			&i.Description,
			&i.Label,
			&i.PrimaryButtonText,
			&i.PrimaryButtonUrl,
			&i.SecondaryButtonText,
			&i.SecondaryButtonUrl,
			&i.IsActive,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageSections = `-- name: ListPageSections :many
SELECT id, page_key, section_key, heading, subheading, description, label, primary_button_text, primary_button_url, secondary_button_text, secondary_button_url, is_active, display_order, created_at, updated_at FROM page_sections
WHERE page_key = ? AND is_active = 1
ORDER BY display_order ASC
`

func (q *Queries) ListPageSections(ctx context.Context, pageKey string) ([]PageSection, error) {
	rows, err := q.db.QueryContext(ctx, listPageSections, pageKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageSection{}
	for rows.Next() {
		var i PageSection
		if err := rows.Scan(
			&i.ID,
			&i.PageKey,
			&i.SectionKey,
			&i.Heading,
			&i.Subheading,
			&i.Description,
			&i.Label,
			&i.PrimaryButtonText,
			&i.PrimaryButtonUrl,
			&i.SecondaryButtonText,
			&i.SecondaryButtonUrl,
			&i.IsActive,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePageSection = `-- name: UpdatePageSection :exec
UPDATE page_sections SET
    heading = ?,
    subheading = ?,
    description = ?,
    label = ?,
    primary_button_text = ?,
    primary_button_url = ?,
    secondary_button_text = ?,
    secondary_button_url = ?,
    is_active = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePageSectionParams struct {
	Heading             string `json:"heading"`
	Subheading          string `json:"subheading"`
	Description         string `json:"description"`
	Label               string `json:"label"`
	PrimaryButtonText   string `json:"primary_button_text"`
	PrimaryButtonUrl    string `json:"primary_button_url"`
	SecondaryButtonText string `json:"secondary_button_text"`
	SecondaryButtonUrl  string `json:"secondary_button_url"`
	IsActive            bool   `json:"is_active"`
	ID                  int64  `json:"id"`
}

func (q *Queries) UpdatePageSection(ctx context.Context, arg UpdatePageSectionParams) error {
	_, err := q.db.ExecContext(ctx, updatePageSection,
		arg.Heading,
		arg.Subheading,
		arg.Description,
		arg.Label,
		arg.PrimaryButtonText,
		arg.PrimaryButtonUrl,
		arg.SecondaryButtonText,
		arg.SecondaryButtonUrl,
		arg.IsActive,
		arg.ID,
	)
	return err
}
