// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partner_tiers.sql

package sqlc

import (
	"context"
)

const createPartnerTier = `-- name: CreatePartnerTier :one
INSERT INTO partner_tiers (name, slug, description, sort_order)
VALUES (?, ?, ?, ?) RETURNING id, name, slug, description, sort_order, created_at, updated_at
`

type CreatePartnerTierParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	SortOrder   int64  `json:"sort_order"`
}

func (q *Queries) CreatePartnerTier(ctx context.Context, arg CreatePartnerTierParams) (PartnerTier, error) {
	row := q.db.QueryRowContext(ctx, createPartnerTier,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i PartnerTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePartnerTier = `-- name: DeletePartnerTier :exec
DELETE FROM partner_tiers WHERE id = ?
`

func (q *Queries) DeletePartnerTier(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePartnerTier, id)
	return err
}

const getPartnerTier = `-- name: GetPartnerTier :one
SELECT id, name, slug, description, sort_order, created_at, updated_at FROM partner_tiers WHERE id = ? LIMIT 1
`

func (q *Queries) GetPartnerTier(ctx context.Context, id int64) (PartnerTier, error) {
	row := q.db.QueryRowContext(ctx, getPartnerTier, id)
	var i PartnerTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerTierBySlug = `-- name: GetPartnerTierBySlug :one
SELECT id, name, slug, description, sort_order, created_at, updated_at FROM partner_tiers WHERE slug = ? LIMIT 1
`

func (q *Queries) GetPartnerTierBySlug(ctx context.Context, slug string) (PartnerTier, error) {
	row := q.db.QueryRowContext(ctx, getPartnerTierBySlug, slug)
	var i PartnerTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPartnerTiers = `-- name: ListPartnerTiers :many
SELECT id, name, slug, description, sort_order, created_at, updated_at FROM partner_tiers ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListPartnerTiers(ctx context.Context) ([]PartnerTier, error) {
	rows, err := q.db.QueryContext(ctx, listPartnerTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartnerTier{}
	for rows.Next() {
		var i PartnerTier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartnerTier = `-- name: UpdatePartnerTier :one
UPDATE partner_tiers SET name = ?, slug = ?, description = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, slug, description, sort_order, created_at, updated_at
`

type UpdatePartnerTierParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	SortOrder   int64  `json:"sort_order"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdatePartnerTier(ctx context.Context, arg UpdatePartnerTierParams) (PartnerTier, error) {
	row := q.db.QueryRowContext(ctx, updatePartnerTier,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	var i PartnerTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
