// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partners.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPartner = `-- name: CreatePartner :one
INSERT INTO partners (
    name, tier_id, logo_url, icon, website_url, description, display_order
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, tier_id, logo_url, icon, website_url, description, display_order, is_active, created_at, updated_at, is_featured
`

type CreatePartnerParams struct {
	Name         string         `json:"name"`
	TierID       int64          `json:"tier_id"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Icon         sql.NullString `json:"icon"`
	WebsiteUrl   sql.NullString `json:"website_url"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error) {
	row := q.db.QueryRowContext(ctx, createPartner,
		arg.Name,
		arg.TierID,
		arg.LogoUrl,
		arg.Icon,
		arg.WebsiteUrl,
		arg.Description,
		arg.DisplayOrder,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TierID,
		&i.LogoUrl,
		&i.Icon,
		&i.WebsiteUrl,
		&i.Description,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFeatured,
	)
	return i, err
}

const createTestimonial = `-- name: CreateTestimonial :one
INSERT INTO partner_testimonials (
    partner_id, quote, author_name, author_title, display_order
) VALUES (?, ?, ?, ?, ?)
RETURNING id, partner_id, quote, author_name, author_title, display_order, is_active, created_at
`

type CreateTestimonialParams struct {
	PartnerID    int64  `json:"partner_id"`
	Quote        string `json:"quote"`
	AuthorName   string `json:"author_name"`
	AuthorTitle  string `json:"author_title"`
	DisplayOrder int64  `json:"display_order"`
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (PartnerTestimonial, error) {
	row := q.db.QueryRowContext(ctx, createTestimonial,
		arg.PartnerID,
		arg.Quote,
		arg.AuthorName,
		arg.AuthorTitle,
		arg.DisplayOrder,
	)
	var i PartnerTestimonial
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Quote,
		&i.AuthorName,
		&i.AuthorTitle,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deletePartner = `-- name: DeletePartner :exec
DELETE FROM partners WHERE id = ?
`

func (q *Queries) DeletePartner(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePartner, id)
	return err
}

const deleteTestimonial = `-- name: DeleteTestimonial :exec
DELETE FROM partner_testimonials WHERE id = ?
`

func (q *Queries) DeleteTestimonial(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTestimonial, id)
	return err
}

const getPartner = `-- name: GetPartner :one
SELECT p.id, p.name, p.tier_id, p.logo_url, p.icon, p.website_url, p.description, p.display_order, p.is_active, p.created_at, p.updated_at, p.is_featured, pt.name AS tier_name, pt.sort_order AS tier_level
FROM partners p
JOIN partner_tiers pt ON p.tier_id = pt.id
WHERE p.id = ?
`

type GetPartnerRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	TierID       int64          `json:"tier_id"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Icon         sql.NullString `json:"icon"`
	WebsiteUrl   sql.NullString `json:"website_url"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	IsFeatured   int64          `json:"is_featured"`
	TierName     string         `json:"tier_name"`
	TierLevel    int64          `json:"tier_level"`
}

func (q *Queries) GetPartner(ctx context.Context, id int64) (GetPartnerRow, error) {
	row := q.db.QueryRowContext(ctx, getPartner, id)
	var i GetPartnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TierID,
		&i.LogoUrl,
		&i.Icon,
		&i.WebsiteUrl,
		&i.Description,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFeatured,
		&i.TierName,
		&i.TierLevel,
	)
	return i, err
}

const getTestimonial = `-- name: GetTestimonial :one
SELECT pt.id, pt.partner_id, pt.quote, pt.author_name, pt.author_title, pt.display_order, pt.is_active, pt.created_at, p.name AS partner_name
FROM partner_testimonials pt
JOIN partners p ON pt.partner_id = p.id
WHERE pt.id = ?
`

type GetTestimonialRow struct {
	ID           int64     `json:"id"`
	PartnerID    int64     `json:"partner_id"`
	Quote        string    `json:"quote"`
	AuthorName   string    `json:"author_name"`
	AuthorTitle  string    `json:"author_title"`
	DisplayOrder int64     `json:"display_order"`
	IsActive     int64     `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	PartnerName  string    `json:"partner_name"`
}

func (q *Queries) GetTestimonial(ctx context.Context, id int64) (GetTestimonialRow, error) {
	row := q.db.QueryRowContext(ctx, getTestimonial, id)
	var i GetTestimonialRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Quote,
		&i.AuthorName,
		&i.AuthorTitle,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.PartnerName,
	)
	return i, err
}

const listActiveTestimonials = `-- name: ListActiveTestimonials :many
SELECT pt.id, pt.partner_id, pt.quote, pt.author_name, pt.author_title, pt.display_order, pt.is_active, pt.created_at, p.name AS partner_name, p.logo_url AS partner_logo_url, p.icon AS partner_icon
FROM partner_testimonials pt
JOIN partners p ON pt.partner_id = p.id
WHERE pt.is_active = 1
ORDER BY pt.display_order ASC
`

type ListActiveTestimonialsRow struct {
	ID             int64          `json:"id"`
	PartnerID      int64          `json:"partner_id"`
	Quote          string         `json:"quote"`
	AuthorName     string         `json:"author_name"`
	AuthorTitle    string         `json:"author_title"`
	DisplayOrder   int64          `json:"display_order"`
	IsActive       int64          `json:"is_active"`
	CreatedAt      time.Time      `json:"created_at"`
	PartnerName    string         `json:"partner_name"`
	PartnerLogoUrl sql.NullString `json:"partner_logo_url"`
	PartnerIcon    sql.NullString `json:"partner_icon"`
}

func (q *Queries) ListActiveTestimonials(ctx context.Context) ([]ListActiveTestimonialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTestimonialsRow{}
	for rows.Next() {
		var i ListActiveTestimonialsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Quote,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.PartnerName,
			&i.PartnerLogoUrl,
			&i.PartnerIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPartners = `-- name: ListAllPartners :many
SELECT p.id, p.name, p.tier_id, p.logo_url, p.icon, p.website_url, p.description, p.display_order, p.is_active, p.created_at, p.updated_at, p.is_featured, pt.name AS tier_name
FROM partners p
JOIN partner_tiers pt ON p.tier_id = pt.id
ORDER BY pt.sort_order ASC, p.display_order ASC
`

type ListAllPartnersRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	TierID       int64          `json:"tier_id"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Icon         sql.NullString `json:"icon"`
	WebsiteUrl   sql.NullString `json:"website_url"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	IsFeatured   int64          `json:"is_featured"`
	TierName     string         `json:"tier_name"`
}

func (q *Queries) ListAllPartners(ctx context.Context) ([]ListAllPartnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPartnersRow{}
	for rows.Next() {
		var i ListAllPartnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TierID,
			&i.LogoUrl,
			&i.Icon,
			&i.WebsiteUrl,
			&i.Description,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFeatured,
			&i.TierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedPartners = `-- name: ListFeaturedPartners :many
SELECT p.id, p.name, p.tier_id, p.logo_url, p.icon, p.website_url, p.description, p.display_order, p.is_active, p.created_at, p.updated_at, p.is_featured, pt.name AS tier_name
FROM partners p
JOIN partner_tiers pt ON p.tier_id = pt.id
WHERE p.is_featured = 1 AND p.is_active = 1
ORDER BY p.display_order ASC
LIMIT ?
`

type ListFeaturedPartnersRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	TierID       int64          `json:"tier_id"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Icon         sql.NullString `json:"icon"`
	WebsiteUrl   sql.NullString `json:"website_url"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	IsFeatured   int64          `json:"is_featured"`
	TierName     string         `json:"tier_name"`
}

func (q *Queries) ListFeaturedPartners(ctx context.Context, limit int64) ([]ListFeaturedPartnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturedPartners, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeaturedPartnersRow{}
	for rows.Next() {
		var i ListFeaturedPartnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TierID,
			&i.LogoUrl,
			&i.Icon,
			&i.WebsiteUrl,
			&i.Description,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFeatured,
			&i.TierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnersByTier = `-- name: ListPartnersByTier :many
SELECT p.id, p.name, p.tier_id, p.logo_url, p.icon, p.website_url, p.description, p.display_order, p.is_active, p.created_at, p.updated_at, p.is_featured, pt.name AS tier_name, pt.sort_order AS tier_level
FROM partners p
JOIN partner_tiers pt ON p.tier_id = pt.id
WHERE p.is_active = 1
ORDER BY pt.sort_order ASC, p.display_order ASC
`

type ListPartnersByTierRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	TierID       int64          `json:"tier_id"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Icon         sql.NullString `json:"icon"`
	WebsiteUrl   sql.NullString `json:"website_url"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	IsFeatured   int64          `json:"is_featured"`
	TierName     string         `json:"tier_name"`
	TierLevel    int64          `json:"tier_level"`
}

func (q *Queries) ListPartnersByTier(ctx context.Context) ([]ListPartnersByTierRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartnersByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartnersByTierRow{}
	for rows.Next() {
		var i ListPartnersByTierRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TierID,
			&i.LogoUrl,
			&i.Icon,
			&i.WebsiteUrl,
			&i.Description,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFeatured,
			&i.TierName,
			&i.TierLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnersByTierID = `-- name: ListPartnersByTierID :many
SELECT id, name, tier_id, logo_url, icon, website_url, description, display_order, is_active, created_at, updated_at, is_featured FROM partners
WHERE tier_id = ? AND is_active = 1
ORDER BY display_order ASC
`

func (q *Queries) ListPartnersByTierID(ctx context.Context, tierID int64) ([]Partner, error) {
	rows, err := q.db.QueryContext(ctx, listPartnersByTierID, tierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Partner{}
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TierID,
			&i.LogoUrl,
			&i.Icon,
			&i.WebsiteUrl,
			&i.Description,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFeatured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartner = `-- name: UpdatePartner :one
UPDATE partners
SET name = ?, tier_id = ?, logo_url = ?, icon = ?,
    website_url = ?, description = ?, display_order = ?,
    is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, tier_id, logo_url, icon, website_url, description, display_order, is_active, created_at, updated_at, is_featured
`

type UpdatePartnerParams struct {
	Name         string         `json:"name"`
	TierID       int64          `json:"tier_id"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Icon         sql.NullString `json:"icon"`
	WebsiteUrl   sql.NullString `json:"website_url"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	IsActive     int64          `json:"is_active"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (Partner, error) {
	row := q.db.QueryRowContext(ctx, updatePartner,
		arg.Name,
		arg.TierID,
		arg.LogoUrl,
		arg.Icon,
		arg.WebsiteUrl,
		arg.Description,
		arg.DisplayOrder,
		arg.IsActive,
		arg.ID,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TierID,
		&i.LogoUrl,
		&i.Icon,
		&i.WebsiteUrl,
		&i.Description,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsFeatured,
	)
	return i, err
}

const updateTestimonial = `-- name: UpdateTestimonial :one
UPDATE partner_testimonials
SET partner_id = ?, quote = ?, author_name = ?,
    author_title = ?, display_order = ?, is_active = ?
WHERE id = ?
RETURNING id, partner_id, quote, author_name, author_title, display_order, is_active, created_at
`

type UpdateTestimonialParams struct {
	PartnerID    int64  `json:"partner_id"`
	Quote        string `json:"quote"`
	AuthorName   string `json:"author_name"`
	AuthorTitle  string `json:"author_title"`
	DisplayOrder int64  `json:"display_order"`
	IsActive     int64  `json:"is_active"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) (PartnerTestimonial, error) {
	row := q.db.QueryRowContext(ctx, updateTestimonial,
		arg.PartnerID,
		arg.Quote,
		arg.AuthorName,
		arg.AuthorTitle,
		arg.DisplayOrder,
		arg.IsActive,
		arg.ID,
	)
	var i PartnerTestimonial
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Quote,
		&i.AuthorName,
		&i.AuthorTitle,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
