// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products WHERE status = 'published'
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsAdminFiltered = `-- name: CountProductsAdminFiltered :one
SELECT COUNT(*) FROM products p
WHERE
    (CASE WHEN ?1 = '' THEN 1 ELSE p.status = ?1 END)
    AND (CASE WHEN ?2 = 0 THEN 1 ELSE p.category_id = ?2 END)
    AND (CASE WHEN ?3 = '' THEN 1 ELSE (p.name LIKE '%' || ?3 || '%' OR p.sku LIKE '%' || ?3 || '%') END)
`

type CountProductsAdminFilteredParams struct {
	FilterStatus   interface{} `json:"filter_status"`
	FilterCategory interface{} `json:"filter_category"`
	FilterSearch   interface{} `json:"filter_search"`
}

func (q *Queries) CountProductsAdminFiltered(ctx context.Context, arg CountProductsAdminFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsAdminFiltered, arg.FilterStatus, arg.FilterCategory, arg.FilterSearch)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategory = `-- name: CountProductsByCategory :one
SELECT COUNT(*) FROM products WHERE category_id = ? AND status = 'published'
`

func (q *Queries) CountProductsByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    sku, slug, name, tagline, description, overview,
    category_id, status, is_featured, featured_order,
    meta_title, meta_description, primary_image, video_url, published_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image
`

type CreateProductParams struct {
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Tagline         sql.NullString `json:"tagline"`
	Description     string         `json:"description"`
	Overview        sql.NullString `json:"overview"`
	CategoryID      int64          `json:"category_id"`
	Status          string         `json:"status"`
	IsFeatured      bool           `json:"is_featured"`
	FeaturedOrder   sql.NullInt64  `json:"featured_order"`
	MetaTitle       sql.NullString `json:"meta_title"`
	MetaDescription sql.NullString `json:"meta_description"`
	PrimaryImage    sql.NullString `json:"primary_image"`
	VideoUrl        sql.NullString `json:"video_url"`
	PublishedAt     sql.NullTime   `json:"published_at"`
}

// ====================================================================
// PRODUCTS
// ====================================================================
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Sku,
		arg.Slug,
		arg.Name,
		arg.Tagline,
		arg.Description,
		arg.Overview,
		arg.CategoryID,
		arg.Status,
		arg.IsFeatured,
		arg.FeaturedOrder,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.PrimaryImage,
		arg.VideoUrl,
		arg.PublishedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Description,
		&i.Overview,
		&i.CategoryID,
		&i.Status,
		&i.IsFeatured,
		&i.FeaturedOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.PrimaryImage,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.OgImage,
	)
	return i, err
}

const createProductCertification = `-- name: CreateProductCertification :one

INSERT INTO product_certifications (product_id, certification_name, certification_code, icon_type, icon_path, display_order)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, product_id, certification_name, certification_code, icon_type, icon_path, display_order, created_at
`

type CreateProductCertificationParams struct {
	ProductID         int64          `json:"product_id"`
	CertificationName string         `json:"certification_name"`
	CertificationCode sql.NullString `json:"certification_code"`
	IconType          sql.NullString `json:"icon_type"`
	IconPath          sql.NullString `json:"icon_path"`
	DisplayOrder      int64          `json:"display_order"`
}

// ====================================================================
// PRODUCT CERTIFICATIONS
// ====================================================================
func (q *Queries) CreateProductCertification(ctx context.Context, arg CreateProductCertificationParams) (ProductCertification, error) {
	row := q.db.QueryRowContext(ctx, createProductCertification,
		arg.ProductID,
		arg.CertificationName,
		arg.CertificationCode,
		arg.IconType,
		arg.IconPath,
		arg.DisplayOrder,
	)
	var i ProductCertification
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CertificationName,
		&i.CertificationCode,
		&i.IconType,
		&i.IconPath,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createProductDownload = `-- name: CreateProductDownload :one

INSERT INTO product_downloads (product_id, title, description, file_type, file_path, file_size, version, display_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, product_id, title, description, file_type, file_path, file_size, version, download_count, display_order, created_at, updated_at
`

type CreateProductDownloadParams struct {
	ProductID    int64          `json:"product_id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	FileType     string         `json:"file_type"`
	FilePath     string         `json:"file_path"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Version      sql.NullString `json:"version"`
	DisplayOrder int64          `json:"display_order"`
}

// ====================================================================
// PRODUCT DOWNLOADS
// ====================================================================
func (q *Queries) CreateProductDownload(ctx context.Context, arg CreateProductDownloadParams) (ProductDownload, error) {
	row := q.db.QueryRowContext(ctx, createProductDownload,
		arg.ProductID,
		arg.Title,
		arg.Description,
		arg.FileType,
		arg.FilePath,
		arg.FileSize,
		arg.Version,
		arg.DisplayOrder,
	)
	var i ProductDownload
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.FileType,
		&i.FilePath,
		&i.FileSize,
		&i.Version,
		&i.DownloadCount,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductFeature = `-- name: CreateProductFeature :one

INSERT INTO product_features (product_id, feature_text, display_order)
VALUES (?, ?, ?)
RETURNING id, product_id, feature_text, display_order, created_at
`

type CreateProductFeatureParams struct {
	ProductID    int64  `json:"product_id"`
	FeatureText  string `json:"feature_text"`
	DisplayOrder int64  `json:"display_order"`
}

// ====================================================================
// PRODUCT FEATURES
// ====================================================================
func (q *Queries) CreateProductFeature(ctx context.Context, arg CreateProductFeatureParams) (ProductFeature, error) {
	row := q.db.QueryRowContext(ctx, createProductFeature, arg.ProductID, arg.FeatureText, arg.DisplayOrder)
	var i ProductFeature
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.FeatureText,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createProductImage = `-- name: CreateProductImage :one

INSERT INTO product_images (product_id, image_path, alt_text, caption, display_order, is_thumbnail)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, product_id, image_path, alt_text, caption, display_order, is_thumbnail, created_at
`

type CreateProductImageParams struct {
	ProductID    int64          `json:"product_id"`
	ImagePath    string         `json:"image_path"`
	AltText      sql.NullString `json:"alt_text"`
	Caption      sql.NullString `json:"caption"`
	DisplayOrder int64          `json:"display_order"`
	IsThumbnail  bool           `json:"is_thumbnail"`
}

// ====================================================================
// PRODUCT IMAGES
// ====================================================================
func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage,
		arg.ProductID,
		arg.ImagePath,
		arg.AltText,
		arg.Caption,
		arg.DisplayOrder,
		arg.IsThumbnail,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImagePath,
		&i.AltText,
		&i.Caption,
		&i.DisplayOrder,
		&i.IsThumbnail,
		&i.CreatedAt,
	)
	return i, err
}

const createProductSpec = `-- name: CreateProductSpec :one

INSERT INTO product_specs (product_id, section_name, spec_key, spec_value, display_order)
VALUES (?, ?, ?, ?, ?)
RETURNING id, product_id, section_name, spec_key, spec_value, display_order, created_at
`

type CreateProductSpecParams struct {
	ProductID    int64  `json:"product_id"`
	SectionName  string `json:"section_name"`
	SpecKey      string `json:"spec_key"`
	SpecValue    string `json:"spec_value"`
	DisplayOrder int64  `json:"display_order"`
}

// ====================================================================
// PRODUCT SPECS
// ====================================================================
func (q *Queries) CreateProductSpec(ctx context.Context, arg CreateProductSpecParams) (ProductSpec, error) {
	row := q.db.QueryRowContext(ctx, createProductSpec,
		arg.ProductID,
		arg.SectionName,
		arg.SpecKey,
		arg.SpecValue,
		arg.DisplayOrder,
	)
	var i ProductSpec
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SectionName,
		&i.SpecKey,
		&i.SpecValue,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const deleteProductCertifications = `-- name: DeleteProductCertifications :exec
DELETE FROM product_certifications WHERE product_id = ?
`

func (q *Queries) DeleteProductCertifications(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductCertifications, productID)
	return err
}

const deleteProductDownload = `-- name: DeleteProductDownload :exec
DELETE FROM product_downloads WHERE id = ?
`

func (q *Queries) DeleteProductDownload(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductDownload, id)
	return err
}

const deleteProductDownloads = `-- name: DeleteProductDownloads :exec
DELETE FROM product_downloads WHERE product_id = ?
`

func (q *Queries) DeleteProductDownloads(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductDownloads, productID)
	return err
}

const deleteProductFeatures = `-- name: DeleteProductFeatures :exec
DELETE FROM product_features WHERE product_id = ?
`

func (q *Queries) DeleteProductFeatures(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductFeatures, productID)
	return err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images WHERE id = ?
`

func (q *Queries) DeleteProductImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductImage, id)
	return err
}

const deleteProductImages = `-- name: DeleteProductImages :exec
DELETE FROM product_images WHERE product_id = ?
`

func (q *Queries) DeleteProductImages(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductImages, productID)
	return err
}

const deleteProductSpecs = `-- name: DeleteProductSpecs :exec
DELETE FROM product_specs WHERE product_id = ?
`

func (q *Queries) DeleteProductSpecs(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductSpecs, productID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image FROM products WHERE id = ? LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Description,
		&i.Overview,
		&i.CategoryID,
		&i.Status,
		&i.IsFeatured,
		&i.FeaturedOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.PrimaryImage,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.OgImage,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image FROM products WHERE sku = ? LIMIT 1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Description,
		&i.Overview,
		&i.CategoryID,
		&i.Status,
		&i.IsFeatured,
		&i.FeaturedOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.PrimaryImage,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.OgImage,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image FROM products WHERE slug = ? LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Description,
		&i.Overview,
		&i.CategoryID,
		&i.Status,
		&i.IsFeatured,
		&i.FeaturedOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.PrimaryImage,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.OgImage,
	)
	return i, err
}

const getProductDownload = `-- name: GetProductDownload :one
SELECT id, product_id, title, description, file_type, file_path, file_size, version, download_count, display_order, created_at, updated_at FROM product_downloads WHERE id = ? LIMIT 1
`

func (q *Queries) GetProductDownload(ctx context.Context, id int64) (ProductDownload, error) {
	row := q.db.QueryRowContext(ctx, getProductDownload, id)
	var i ProductDownload
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.FileType,
		&i.FilePath,
		&i.FileSize,
		&i.Version,
		&i.DownloadCount,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDownloadCount = `-- name: IncrementDownloadCount :exec
UPDATE product_downloads
SET download_count = download_count + 1
WHERE id = ?
`

func (q *Queries) IncrementDownloadCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementDownloadCount, id)
	return err
}

const listAllProductsAdmin = `-- name: ListAllProductsAdmin :many
SELECT id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image FROM products
ORDER BY created_at DESC
`

func (q *Queries) ListAllProductsAdmin(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listAllProductsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.Description,
			&i.Overview,
			&i.CategoryID,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.PrimaryImage,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT p.id, p.sku, p.slug, p.name, p.tagline, p.description, p.overview, p.category_id, p.status, p.is_featured, p.featured_order, p.meta_title, p.meta_description, p.primary_image, p.video_url, p.created_at, p.updated_at, p.published_at, p.og_image, pc.slug AS category_slug
FROM products p
INNER JOIN product_categories pc ON p.category_id = pc.id
WHERE p.is_featured = 1 AND p.status = 'published'
ORDER BY p.featured_order ASC
LIMIT ?
`

type ListFeaturedProductsRow struct {
	ID              int64          `json:"id"`
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Tagline         sql.NullString `json:"tagline"`
	Description     string         `json:"description"`
	Overview        sql.NullString `json:"overview"`
	CategoryID      int64          `json:"category_id"`
	Status          string         `json:"status"`
	IsFeatured      bool           `json:"is_featured"`
	FeaturedOrder   sql.NullInt64  `json:"featured_order"`
	MetaTitle       sql.NullString `json:"meta_title"`
	MetaDescription sql.NullString `json:"meta_description"`
	PrimaryImage    sql.NullString `json:"primary_image"`
	VideoUrl        sql.NullString `json:"video_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	OgImage         string         `json:"og_image"`
	CategorySlug    string         `json:"category_slug"`
}

func (q *Queries) ListFeaturedProducts(ctx context.Context, limit int64) ([]ListFeaturedProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeaturedProductsRow{}
	for rows.Next() {
		var i ListFeaturedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.Description,
			&i.Overview,
			&i.CategoryID,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.PrimaryImage,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.OgImage,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCertifications = `-- name: ListProductCertifications :many
SELECT id, product_id, certification_name, certification_code, icon_type, icon_path, display_order, created_at FROM product_certifications
WHERE product_id = ?
ORDER BY display_order ASC
`

func (q *Queries) ListProductCertifications(ctx context.Context, productID int64) ([]ProductCertification, error) {
	rows, err := q.db.QueryContext(ctx, listProductCertifications, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductCertification{}
	for rows.Next() {
		var i ProductCertification
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CertificationName,
			&i.CertificationCode,
			&i.IconType,
			&i.IconPath,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductDownloads = `-- name: ListProductDownloads :many
SELECT id, product_id, title, description, file_type, file_path, file_size, version, download_count, display_order, created_at, updated_at FROM product_downloads
WHERE product_id = ?
ORDER BY display_order ASC
`

func (q *Queries) ListProductDownloads(ctx context.Context, productID int64) ([]ProductDownload, error) {
	rows, err := q.db.QueryContext(ctx, listProductDownloads, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductDownload{}
	for rows.Next() {
		var i ProductDownload
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Description,
			&i.FileType,
			&i.FilePath,
			&i.FileSize,
			&i.Version,
			&i.DownloadCount,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductFeatures = `-- name: ListProductFeatures :many
SELECT id, product_id, feature_text, display_order, created_at FROM product_features
WHERE product_id = ?
ORDER BY display_order ASC
`

func (q *Queries) ListProductFeatures(ctx context.Context, productID int64) ([]ProductFeature, error) {
	rows, err := q.db.QueryContext(ctx, listProductFeatures, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductFeature{}
	for rows.Next() {
		var i ProductFeature
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.FeatureText,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, image_path, alt_text, caption, display_order, is_thumbnail, created_at FROM product_images
WHERE product_id = ?
ORDER BY display_order ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID int64) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImagePath,
			&i.AltText,
			&i.Caption,
			&i.DisplayOrder,
			&i.IsThumbnail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductSpecs = `-- name: ListProductSpecs :many
SELECT id, product_id, section_name, spec_key, spec_value, display_order, created_at FROM product_specs
WHERE product_id = ?
ORDER BY display_order ASC
`

func (q *Queries) ListProductSpecs(ctx context.Context, productID int64) ([]ProductSpec, error) {
	rows, err := q.db.QueryContext(ctx, listProductSpecs, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductSpec{}
	for rows.Next() {
		var i ProductSpec
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SectionName,
			&i.SpecKey,
			&i.SpecValue,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image FROM products
WHERE status = 'published'
ORDER BY
    CASE WHEN is_featured = 1 THEN featured_order ELSE 999999 END ASC,
    published_at DESC
LIMIT ? OFFSET ?
`

type ListProductsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.Description,
			&i.Overview,
			&i.CategoryID,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.PrimaryImage,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsAdminFiltered = `-- name: ListProductsAdminFiltered :many
SELECT p.id, p.sku, p.slug, p.name, p.tagline, p.description, p.overview, p.category_id, p.status, p.is_featured, p.featured_order, p.meta_title, p.meta_description, p.primary_image, p.video_url, p.created_at, p.updated_at, p.published_at, p.og_image FROM products p
WHERE
    (CASE WHEN ?1 = '' THEN 1 ELSE p.status = ?1 END)
    AND (CASE WHEN ?2 = 0 THEN 1 ELSE p.category_id = ?2 END)
    AND (CASE WHEN ?3 = '' THEN 1 ELSE (p.name LIKE '%' || ?3 || '%' OR p.sku LIKE '%' || ?3 || '%') END)
ORDER BY p.created_at DESC
LIMIT ?5 OFFSET ?4
`

type ListProductsAdminFilteredParams struct {
	FilterStatus   interface{} `json:"filter_status"`
	FilterCategory interface{} `json:"filter_category"`
	FilterSearch   interface{} `json:"filter_search"`
	PageOffset     int64       `json:"page_offset"`
	PageLimit      int64       `json:"page_limit"`
}

func (q *Queries) ListProductsAdminFiltered(ctx context.Context, arg ListProductsAdminFilteredParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsAdminFiltered,
		arg.FilterStatus,
		arg.FilterCategory,
		arg.FilterSearch,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.Description,
			&i.Overview,
			&i.CategoryID,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.PrimaryImage,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image FROM products
WHERE category_id = ? AND status = 'published'
ORDER BY
    CASE WHEN is_featured = 1 THEN featured_order ELSE 999999 END ASC,
    published_at DESC
LIMIT ? OFFSET ?
`

type ListProductsByCategoryParams struct {
	CategoryID int64 `json:"category_id"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.Description,
			&i.Overview,
			&i.CategoryID,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.PrimaryImage,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, sku, slug, name, tagline, description, overview, category_id, status, is_featured, featured_order, meta_title, meta_description, primary_image, video_url, created_at, updated_at, published_at, og_image FROM products
WHERE status = 'published'
    AND (name LIKE ? OR description LIKE ? OR tagline LIKE ?)
ORDER BY published_at DESC
LIMIT ? OFFSET ?
`

type SearchProductsParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Tagline     sql.NullString `json:"tagline"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts,
		arg.Name,
		arg.Description,
		arg.Tagline,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.Description,
			&i.Overview,
			&i.CategoryID,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.PrimaryImage,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET sku = ?, slug = ?, name = ?, tagline = ?, description = ?, overview = ?,
    category_id = ?, status = ?, is_featured = ?, featured_order = ?,
    meta_title = ?, meta_description = ?, primary_image = ?, video_url = ?, published_at = ?
WHERE id = ?
`

type UpdateProductParams struct {
	Sku             string         `json:"sku"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Tagline         sql.NullString `json:"tagline"`
	Description     string         `json:"description"`
	Overview        sql.NullString `json:"overview"`
	CategoryID      int64          `json:"category_id"`
	Status          string         `json:"status"`
	IsFeatured      bool           `json:"is_featured"`
	FeaturedOrder   sql.NullInt64  `json:"featured_order"`
	MetaTitle       sql.NullString `json:"meta_title"`
	MetaDescription sql.NullString `json:"meta_description"`
	PrimaryImage    sql.NullString `json:"primary_image"`
	VideoUrl        sql.NullString `json:"video_url"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Sku,
		arg.Slug,
		arg.Name,
		arg.Tagline,
		arg.Description,
		arg.Overview,
		arg.CategoryID,
		arg.Status,
		arg.IsFeatured,
		arg.FeaturedOrder,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.PrimaryImage,
		arg.VideoUrl,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}
