// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddProductToPost(ctx context.Context, arg AddProductToPostParams) error
	AddProductToSolution(ctx context.Context, arg AddProductToSolutionParams) error
	AddTagToPost(ctx context.Context, arg AddTagToPostParams) error
	// Case study products management
	AdminAddCaseStudyProduct(ctx context.Context, arg AdminAddCaseStudyProductParams) (CaseStudyProduct, error)
	AdminCreateCaseStudy(ctx context.Context, arg AdminCreateCaseStudyParams) (CaseStudy, error)
	// Metrics management
	AdminCreateMetric(ctx context.Context, arg AdminCreateMetricParams) (CaseStudyMetric, error)
	AdminDeleteCaseStudy(ctx context.Context, id int64) error
	AdminDeleteMetric(ctx context.Context, id int64) error
	AdminGetCaseStudy(ctx context.Context, id int64) (CaseStudy, error)
	// Admin queries
	AdminListCaseStudies(ctx context.Context) ([]AdminListCaseStudiesRow, error)
	AdminListCaseStudiesFiltered(ctx context.Context, arg AdminListCaseStudiesFilteredParams) ([]AdminListCaseStudiesFilteredRow, error)
	AdminListCaseStudyProducts(ctx context.Context, caseStudyID int64) ([]AdminListCaseStudyProductsRow, error)
	AdminListMetrics(ctx context.Context, caseStudyID int64) ([]AdminListMetricsRow, error)
	AdminRemoveCaseStudyProduct(ctx context.Context, arg AdminRemoveCaseStudyProductParams) error
	AdminUpdateCaseStudy(ctx context.Context, arg AdminUpdateCaseStudyParams) (CaseStudy, error)
	AdminUpdateMetric(ctx context.Context, arg AdminUpdateMetricParams) (CaseStudyMetric, error)
	BulkMarkContactSubmissionsRead(ctx context.Context) error
	ClearPostProducts(ctx context.Context, blogPostID int64) error
	ClearPostTags(ctx context.Context, blogPostID int64) error
	CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error)
	CountBlogPostsAdminFiltered(ctx context.Context, arg CountBlogPostsAdminFilteredParams) (int64, error)
	CountCaseStudies(ctx context.Context) (int64, error)
	CountCaseStudiesAdminFiltered(ctx context.Context, arg CountCaseStudiesAdminFilteredParams) (int64, error)
	CountCaseStudiesByIndustry(ctx context.Context, industryID int64) (int64, error)
	CountContactSubmissions(ctx context.Context) (int64, error)
	CountContactSubmissionsByStatus(ctx context.Context, status string) (int64, error)
	CountContactSubmissionsByStatusAndType(ctx context.Context, arg CountContactSubmissionsByStatusAndTypeParams) (int64, error)
	CountContactSubmissionsByType(ctx context.Context, submissionType string) (int64, error)
	CountContactSubmissionsSearch(ctx context.Context, arg CountContactSubmissionsSearchParams) (int64, error)
	CountDraftBlogPosts(ctx context.Context) (int64, error)
	CountDraftProducts(ctx context.Context) (int64, error)
	CountMediaFiles(ctx context.Context) (int64, error)
	CountMediaFilesSearch(ctx context.Context, search sql.NullString) (int64, error)
	CountNewContactSubmissions(ctx context.Context) (int64, error)
	CountPartners(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsAdminFiltered(ctx context.Context, arg CountProductsAdminFilteredParams) (int64, error)
	CountProductsByCategory(ctx context.Context, categoryID int64) (int64, error)
	CountPublishedPosts(ctx context.Context) (int64, error)
	CountPublishedPostsByCategory(ctx context.Context, slug string) (int64, error)
	CountPublishedWhitepapers(ctx context.Context) (int64, error)
	CountPublishedWhitepapersByTopic(ctx context.Context, topicID int64) (int64, error)
	CountSolutionsAdminFiltered(ctx context.Context, arg CountSolutionsAdminFilteredParams) (int64, error)
	CountWhitepaperDownloads(ctx context.Context) (int64, error)
	CountWhitepaperDownloadsFiltered(ctx context.Context, arg CountWhitepaperDownloadsFilteredParams) (int64, error)
	CountWhitepapersAdminFiltered(ctx context.Context, arg CountWhitepapersAdminFilteredParams) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error)
	CreateBlogAuthor(ctx context.Context, arg CreateBlogAuthorParams) (BlogAuthor, error)
	CreateBlogCategory(ctx context.Context, arg CreateBlogCategoryParams) (BlogCategory, error)
	CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (BlogPost, error)
	CreateBlogTag(ctx context.Context, arg CreateBlogTagParams) (BlogTag, error)
	CreateCTA(ctx context.Context, arg CreateCTAParams) (HomepageCtum, error)
	CreateCertification(ctx context.Context, arg CreateCertificationParams) (Certification, error)
	// ====================================================================
	// CONTACT SUBMISSIONS
	// ====================================================================
	CreateContactSubmission(ctx context.Context, arg CreateContactSubmissionParams) (CreateContactSubmissionRow, error)
	CreateCoreValue(ctx context.Context, arg CreateCoreValueParams) (CoreValue, error)
	CreateFooterColumnItem(ctx context.Context, arg CreateFooterColumnItemParams) (FooterColumnItem, error)
	CreateFooterLegalLink(ctx context.Context, arg CreateFooterLegalLinkParams) (FooterLegalLink, error)
	CreateFooterLink(ctx context.Context, arg CreateFooterLinkParams) (FooterLink, error)
	CreateHero(ctx context.Context, arg CreateHeroParams) (HomepageHero, error)
	CreateIndustry(ctx context.Context, arg CreateIndustryParams) (Industry, error)
	CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error)
	CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error)
	CreateNavigationItem(ctx context.Context, arg CreateNavigationItemParams) (NavigationItem, error)
	CreateNavigationMenu(ctx context.Context, arg CreateNavigationMenuParams) (NavigationMenu, error)
	CreateOfficeLocation(ctx context.Context, arg CreateOfficeLocationParams) (CreateOfficeLocationRow, error)
	CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error)
	CreatePartnerTier(ctx context.Context, arg CreatePartnerTierParams) (PartnerTier, error)
	// ====================================================================
	// PRODUCTS
	// ====================================================================
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	// ====================================================================
	// PRODUCT CERTIFICATIONS
	// ====================================================================
	CreateProductCertification(ctx context.Context, arg CreateProductCertificationParams) (ProductCertification, error)
	// ====================================================================
	// PRODUCT DOWNLOADS
	// ====================================================================
	CreateProductDownload(ctx context.Context, arg CreateProductDownloadParams) (ProductDownload, error)
	// ====================================================================
	// PRODUCT FEATURES
	// ====================================================================
	CreateProductFeature(ctx context.Context, arg CreateProductFeatureParams) (ProductFeature, error)
	// ====================================================================
	// PRODUCT IMAGES
	// ====================================================================
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	// ====================================================================
	// PRODUCT SPECS
	// ====================================================================
	CreateProductSpec(ctx context.Context, arg CreateProductSpecParams) (ProductSpec, error)
	CreateSolution(ctx context.Context, arg CreateSolutionParams) (Solution, error)
	CreateSolutionCTA(ctx context.Context, arg CreateSolutionCTAParams) (SolutionCta, error)
	CreateSolutionChallenge(ctx context.Context, arg CreateSolutionChallengeParams) (SolutionChallenge, error)
	CreateSolutionPageFeature(ctx context.Context, arg CreateSolutionPageFeatureParams) (SolutionPageFeature, error)
	CreateSolutionStat(ctx context.Context, arg CreateSolutionStatParams) (SolutionStat, error)
	CreateSolutionsListingCTA(ctx context.Context, arg CreateSolutionsListingCTAParams) (SolutionsListingCtum, error)
	CreateStat(ctx context.Context, arg CreateStatParams) (HomepageStat, error)
	CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (PartnerTestimonial, error)
	CreateTestimonialHomepage(ctx context.Context, arg CreateTestimonialHomepageParams) (HomepageTestimonial, error)
	CreateWhitepaper(ctx context.Context, arg CreateWhitepaperParams) (Whitepaper, error)
	CreateWhitepaperDownload(ctx context.Context, arg CreateWhitepaperDownloadParams) (CreateWhitepaperDownloadRow, error)
	CreateWhitepaperLearningPoint(ctx context.Context, arg CreateWhitepaperLearningPointParams) (int64, error)
	CreateWhitepaperTopic(ctx context.Context, arg CreateWhitepaperTopicParams) (WhitepaperTopic, error)
	DeleteAllFooterLegalLinks(ctx context.Context) error
	DeleteBlogAuthor(ctx context.Context, id int64) error
	DeleteBlogCategory(ctx context.Context, id int64) error
	DeleteBlogPost(ctx context.Context, id int64) error
	DeleteBlogTag(ctx context.Context, id int64) error
	DeleteCTA(ctx context.Context, id int64) error
	DeleteCertification(ctx context.Context, id int64) error
	DeleteContactSubmission(ctx context.Context, id int64) error
	DeleteCoreValue(ctx context.Context, id int64) error
	DeleteFooterColumnItem(ctx context.Context, id int64) error
	DeleteFooterColumnItemsByIndex(ctx context.Context, columnIndex int64) error
	DeleteFooterLinksByColumnItem(ctx context.Context, columnItemID int64) error
	DeleteHero(ctx context.Context, id int64) error
	DeleteIndustry(ctx context.Context, id int64) error
	DeleteMediaFile(ctx context.Context, id int64) error
	DeleteMilestone(ctx context.Context, id int64) error
	DeleteNavigationItem(ctx context.Context, id int64) error
	DeleteNavigationItemsByMenu(ctx context.Context, menuID int64) error
	DeleteNavigationMenu(ctx context.Context, id int64) error
	DeleteOfficeLocation(ctx context.Context, id int64) error
	DeletePartner(ctx context.Context, id int64) error
	DeletePartnerTier(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductCategory(ctx context.Context, id int64) error
	DeleteProductCertifications(ctx context.Context, productID int64) error
	DeleteProductDownload(ctx context.Context, id int64) error
	DeleteProductDownloads(ctx context.Context, productID int64) error
	DeleteProductFeatures(ctx context.Context, productID int64) error
	DeleteProductImage(ctx context.Context, id int64) error
	DeleteProductImages(ctx context.Context, productID int64) error
	DeleteProductSpecs(ctx context.Context, productID int64) error
	DeleteSolution(ctx context.Context, id int64) error
	DeleteSolutionCTA(ctx context.Context, id int64) error
	DeleteSolutionCTAsBySolutionID(ctx context.Context, solutionID int64) error
	DeleteSolutionChallenge(ctx context.Context, id int64) error
	DeleteSolutionChallengesBySolutionID(ctx context.Context, solutionID int64) error
	DeleteSolutionPageFeature(ctx context.Context, id int64) error
	DeleteSolutionProductsBySolutionID(ctx context.Context, solutionID int64) error
	DeleteSolutionStat(ctx context.Context, id int64) error
	DeleteSolutionStatsBySolutionID(ctx context.Context, solutionID int64) error
	DeleteStat(ctx context.Context, id int64) error
	DeleteTestimonial(ctx context.Context, id int64) error
	DeleteTestimonialHomepage(ctx context.Context, id int64) error
	DeleteWhitepaper(ctx context.Context, id int64) error
	DeleteWhitepaperLearningPoints(ctx context.Context, whitepaperID int64) error
	DeleteWhitepaperTopic(ctx context.Context, id int64) error
	// ====================================================================
	// HOMEPAGE CTA
	// ====================================================================
	GetActiveCTA(ctx context.Context) (HomepageCtum, error)
	// ====================================================================
	// HOMEPAGE HERO
	// ====================================================================
	GetActiveHero(ctx context.Context) (HomepageHero, error)
	GetActiveOfficeLocations(ctx context.Context) ([]GetActiveOfficeLocationsRow, error)
	// ====================================================================
	// SOLUTIONS LISTING CTA
	// ====================================================================
	GetActiveSolutionsListingCTA(ctx context.Context) (SolutionsListingCtum, error)
	GetAdminUserByEmail(ctx context.Context, email string) (GetAdminUserByEmailRow, error)
	GetBlogAuthor(ctx context.Context, id int64) (BlogAuthor, error)
	GetBlogAuthorBySlug(ctx context.Context, slug string) (BlogAuthor, error)
	GetBlogCategory(ctx context.Context, id int64) (BlogCategory, error)
	GetBlogCategoryBySlug(ctx context.Context, slug string) (BlogCategory, error)
	GetBlogPost(ctx context.Context, id int64) (BlogPost, error)
	GetBlogTag(ctx context.Context, id int64) (BlogTag, error)
	GetBlogTagBySlug(ctx context.Context, slug string) (BlogTag, error)
	GetCTA(ctx context.Context, id int64) (HomepageCtum, error)
	GetCaseStudyBySlug(ctx context.Context, slug string) (GetCaseStudyBySlugRow, error)
	GetCaseStudyBySlugIncludeDrafts(ctx context.Context, slug string) (GetCaseStudyBySlugIncludeDraftsRow, error)
	GetCaseStudyMetrics(ctx context.Context, caseStudyID int64) ([]GetCaseStudyMetricsRow, error)
	GetCaseStudyProducts(ctx context.Context, caseStudyID int64) ([]GetCaseStudyProductsRow, error)
	GetCertification(ctx context.Context, id int64) (Certification, error)
	GetCompanyOverview(ctx context.Context) (CompanyOverview, error)
	GetContactSubmissionByID(ctx context.Context, id int64) (GetContactSubmissionByIDRow, error)
	GetCoreValue(ctx context.Context, id int64) (CoreValue, error)
	GetFeaturedPost(ctx context.Context) (GetFeaturedPostRow, error)
	GetFooterColumnItem(ctx context.Context, id int64) (FooterColumnItem, error)
	GetHero(ctx context.Context, id int64) (HomepageHero, error)
	GetIndustry(ctx context.Context, id int64) (Industry, error)
	GetIndustryBySlug(ctx context.Context, slug string) (Industry, error)
	GetMediaFile(ctx context.Context, id int64) (MediaFile, error)
	GetMediaFileByPath(ctx context.Context, filePath string) (MediaFile, error)
	GetMilestone(ctx context.Context, id int64) (Milestone, error)
	GetMissionVisionValues(ctx context.Context) (MissionVisionValue, error)
	GetNavigationItem(ctx context.Context, id int64) (NavigationItem, error)
	GetNavigationMenu(ctx context.Context, id int64) (NavigationMenu, error)
	GetNextSubmissionID(ctx context.Context, id int64) (int64, error)
	GetOfficeLocationByID(ctx context.Context, id int64) (GetOfficeLocationByIDRow, error)
	// ====================================================================
	// PAGE SECTIONS
	// ====================================================================
	GetPageSection(ctx context.Context, arg GetPageSectionParams) (PageSection, error)
	GetPageSectionByID(ctx context.Context, id int64) (PageSection, error)
	GetPartner(ctx context.Context, id int64) (GetPartnerRow, error)
	GetPartnerTier(ctx context.Context, id int64) (PartnerTier, error)
	GetPartnerTierBySlug(ctx context.Context, slug string) (PartnerTier, error)
	GetPostBySlugIncludeDrafts(ctx context.Context, slug string) (GetPostBySlugIncludeDraftsRow, error)
	GetPostProductsByPostID(ctx context.Context, blogPostID int64) ([]GetPostProductsByPostIDRow, error)
	GetPostTagsByPostID(ctx context.Context, blogPostID int64) ([]GetPostTagsByPostIDRow, error)
	GetPreviousSubmissionID(ctx context.Context, id int64) (int64, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProductCategory(ctx context.Context, id int64) (ProductCategory, error)
	GetProductCategoryBySlug(ctx context.Context, slug string) (ProductCategory, error)
	GetProductDownload(ctx context.Context, id int64) (ProductDownload, error)
	GetPublishedPostBySlug(ctx context.Context, slug string) (GetPublishedPostBySlugRow, error)
	GetRelatedPosts(ctx context.Context, arg GetRelatedPostsParams) ([]GetRelatedPostsRow, error)
	GetRelatedWhitepapers(ctx context.Context, arg GetRelatedWhitepapersParams) ([]GetRelatedWhitepapersRow, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetSolutionByID(ctx context.Context, id int64) (Solution, error)
	GetSolutionBySlug(ctx context.Context, slug string) (Solution, error)
	GetSolutionBySlugIncludeDrafts(ctx context.Context, slug string) (Solution, error)
	// ====================================================================
	// SOLUTION CTAS
	// ====================================================================
	GetSolutionCTAs(ctx context.Context, solutionID int64) ([]SolutionCta, error)
	// ====================================================================
	// SOLUTION CHALLENGES
	// ====================================================================
	GetSolutionChallenges(ctx context.Context, solutionID int64) ([]SolutionChallenge, error)
	// ====================================================================
	// SOLUTION PRODUCTS
	// ====================================================================
	GetSolutionProducts(ctx context.Context, solutionID int64) ([]GetSolutionProductsRow, error)
	// ====================================================================
	// SOLUTION STATS
	// ====================================================================
	GetSolutionStats(ctx context.Context, solutionID int64) ([]SolutionStat, error)
	GetStat(ctx context.Context, id int64) (HomepageStat, error)
	GetTestimonial(ctx context.Context, id int64) (GetTestimonialRow, error)
	GetTestimonialHomepage(ctx context.Context, id int64) (HomepageTestimonial, error)
	GetWhitepaperByID(ctx context.Context, id int64) (GetWhitepaperByIDRow, error)
	GetWhitepaperBySlug(ctx context.Context, slug string) (GetWhitepaperBySlugRow, error)
	GetWhitepaperBySlugIncludeDrafts(ctx context.Context, slug string) (GetWhitepaperBySlugIncludeDraftsRow, error)
	GetWhitepaperLearningPoints(ctx context.Context, whitepaperID int64) ([]GetWhitepaperLearningPointsRow, error)
	GetWhitepaperTopic(ctx context.Context, id int64) (WhitepaperTopic, error)
	GetWhitepaperTopicBySlug(ctx context.Context, slug string) (WhitepaperTopic, error)
	IncrementDownloadCount(ctx context.Context, id int64) error
	IncrementWhitepaperDownloadCount(ctx context.Context, id int64) error
	// ====================================================================
	// HOMEPAGE STATS
	// ====================================================================
	ListActiveStats(ctx context.Context) ([]HomepageStat, error)
	ListActiveTestimonials(ctx context.Context) ([]ListActiveTestimonialsRow, error)
	// ====================================================================
	// HOMEPAGE TESTIMONIALS
	// ====================================================================
	ListActiveTestimonialsHomepage(ctx context.Context) ([]HomepageTestimonial, error)
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	ListAllBlogPosts(ctx context.Context) ([]ListAllBlogPostsRow, error)
	ListAllBlogTags(ctx context.Context) ([]BlogTag, error)
	ListAllCTAs(ctx context.Context) ([]HomepageCtum, error)
	ListAllFooterLinks(ctx context.Context) ([]FooterLink, error)
	ListAllHeroes(ctx context.Context) ([]HomepageHero, error)
	// ====================================================================
	// OFFICE LOCATIONS - ADMIN
	// ====================================================================
	ListAllOfficeLocations(ctx context.Context) ([]OfficeLocation, error)
	ListAllPageSections(ctx context.Context) ([]PageSection, error)
	ListAllPartners(ctx context.Context) ([]ListAllPartnersRow, error)
	ListAllProductsAdmin(ctx context.Context) ([]Product, error)
	ListAllSolutionPageFeatures(ctx context.Context) ([]SolutionPageFeature, error)
	ListAllSolutions(ctx context.Context) ([]Solution, error)
	ListAllStats(ctx context.Context) ([]HomepageStat, error)
	ListAllTestimonialsHomepage(ctx context.Context) ([]HomepageTestimonial, error)
	// ====================================================================
	// WHITEPAPERS - ADMIN
	// ====================================================================
	ListAllWhitepapers(ctx context.Context) ([]ListAllWhitepapersRow, error)
	ListBlogAuthors(ctx context.Context) ([]BlogAuthor, error)
	ListBlogCategories(ctx context.Context) ([]BlogCategory, error)
	ListBlogPostsAdminFiltered(ctx context.Context, arg ListBlogPostsAdminFilteredParams) ([]ListBlogPostsAdminFilteredRow, error)
	// ====================================================================
	// CASE STUDIES
	// ====================================================================
	ListCaseStudies(ctx context.Context) ([]ListCaseStudiesRow, error)
	ListCaseStudiesByIndustry(ctx context.Context, industryID int64) ([]ListCaseStudiesByIndustryRow, error)
	ListCertifications(ctx context.Context) ([]Certification, error)
	// ====================================================================
	// CONTACT - ADMIN
	// ====================================================================
	ListContactSubmissions(ctx context.Context, arg ListContactSubmissionsParams) ([]ListContactSubmissionsRow, error)
	ListContactSubmissionsByStatus(ctx context.Context, arg ListContactSubmissionsByStatusParams) ([]ListContactSubmissionsByStatusRow, error)
	ListContactSubmissionsByStatusAndType(ctx context.Context, arg ListContactSubmissionsByStatusAndTypeParams) ([]ListContactSubmissionsByStatusAndTypeRow, error)
	ListContactSubmissionsByType(ctx context.Context, arg ListContactSubmissionsByTypeParams) ([]ListContactSubmissionsByTypeRow, error)
	ListCoreValues(ctx context.Context) ([]CoreValue, error)
	ListFeaturedPartners(ctx context.Context, limit int64) ([]ListFeaturedPartnersRow, error)
	ListFeaturedProducts(ctx context.Context, limit int64) ([]ListFeaturedProductsRow, error)
	ListFooterColumnItems(ctx context.Context) ([]FooterColumnItem, error)
	ListFooterLegalLinks(ctx context.Context) ([]FooterLegalLink, error)
	ListFooterLinks(ctx context.Context, columnItemID int64) ([]FooterLink, error)
	ListIndustries(ctx context.Context) ([]Industry, error)
	ListLatestPublishedPosts(ctx context.Context, limit int64) ([]ListLatestPublishedPostsRow, error)
	ListMediaFiles(ctx context.Context, arg ListMediaFilesParams) ([]MediaFile, error)
	ListMediaFilesByName(ctx context.Context, arg ListMediaFilesByNameParams) ([]MediaFile, error)
	ListMediaFilesBySize(ctx context.Context, arg ListMediaFilesBySizeParams) ([]MediaFile, error)
	ListMediaFilesOldest(ctx context.Context, arg ListMediaFilesOldestParams) ([]MediaFile, error)
	ListMilestones(ctx context.Context) ([]Milestone, error)
	ListNavigationItems(ctx context.Context, menuID int64) ([]NavigationItem, error)
	ListNavigationMenus(ctx context.Context) ([]NavigationMenu, error)
	ListPageSections(ctx context.Context, pageKey string) ([]PageSection, error)
	ListPartnerTiers(ctx context.Context) ([]PartnerTier, error)
	ListPartnersByTier(ctx context.Context) ([]ListPartnersByTierRow, error)
	ListPartnersByTierID(ctx context.Context, tierID int64) ([]Partner, error)
	ListProductCategories(ctx context.Context) ([]ProductCategory, error)
	ListProductCertifications(ctx context.Context, productID int64) ([]ProductCertification, error)
	ListProductDownloads(ctx context.Context, productID int64) ([]ProductDownload, error)
	ListProductFeatures(ctx context.Context, productID int64) ([]ProductFeature, error)
	ListProductImages(ctx context.Context, productID int64) ([]ProductImage, error)
	ListProductSpecs(ctx context.Context, productID int64) ([]ProductSpec, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsAdminFiltered(ctx context.Context, arg ListProductsAdminFilteredParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error)
	ListPublishedPostsByCategory(ctx context.Context, arg ListPublishedPostsByCategoryParams) ([]ListPublishedPostsByCategoryRow, error)
	// ====================================================================
	// SOLUTIONS
	// ====================================================================
	ListPublishedSolutions(ctx context.Context) ([]ListPublishedSolutionsRow, error)
	// ====================================================================
	// WHITEPAPERS
	// ====================================================================
	ListPublishedWhitepapers(ctx context.Context) ([]ListPublishedWhitepapersRow, error)
	ListPublishedWhitepapersByTopic(ctx context.Context, topicID int64) ([]ListPublishedWhitepapersByTopicRow, error)
	// ====================================================================
	// SOLUTION PAGE FEATURES (Why Choose BlueJay)
	// ====================================================================
	ListSolutionPageFeatures(ctx context.Context) ([]SolutionPageFeature, error)
	ListSolutionsAdminFiltered(ctx context.Context, arg ListSolutionsAdminFilteredParams) ([]Solution, error)
	ListWhitepaperDownloads(ctx context.Context, arg ListWhitepaperDownloadsParams) ([]ListWhitepaperDownloadsRow, error)
	ListWhitepaperDownloadsByWhitepaperId(ctx context.Context, whitepaperID int64) ([]ListWhitepaperDownloadsByWhitepaperIdRow, error)
	ListWhitepaperDownloadsFiltered(ctx context.Context, arg ListWhitepaperDownloadsFilteredParams) ([]ListWhitepaperDownloadsFilteredRow, error)
	ListWhitepaperTopics(ctx context.Context) ([]WhitepaperTopic, error)
	ListWhitepaperTopicsWithCount(ctx context.Context) ([]ListWhitepaperTopicsWithCountRow, error)
	ListWhitepapersAdminFiltered(ctx context.Context, arg ListWhitepapersAdminFilteredParams) ([]ListWhitepapersAdminFilteredRow, error)
	RemoveProductFromSolution(ctx context.Context, arg RemoveProductFromSolutionParams) error
	RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error
	SearchBlogTags(ctx context.Context, name string) ([]BlogTag, error)
	SearchContactSubmissions(ctx context.Context, arg SearchContactSubmissionsParams) ([]SearchContactSubmissionsRow, error)
	SearchMediaFiles(ctx context.Context, arg SearchMediaFilesParams) ([]MediaFile, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchPublishedProducts(ctx context.Context, name string) ([]SearchPublishedProductsRow, error)
	UnsetPrimaryOfficeLocations(ctx context.Context) error
	UpdateAboutSettings(ctx context.Context, arg UpdateAboutSettingsParams) error
	UpdateBlogAuthor(ctx context.Context, arg UpdateBlogAuthorParams) (BlogAuthor, error)
	UpdateBlogCategory(ctx context.Context, arg UpdateBlogCategoryParams) (BlogCategory, error)
	UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) (BlogPost, error)
	UpdateBlogSettings(ctx context.Context, arg UpdateBlogSettingsParams) error
	UpdateBlogTag(ctx context.Context, arg UpdateBlogTagParams) (BlogTag, error)
	UpdateCTA(ctx context.Context, arg UpdateCTAParams) error
	UpdateCertification(ctx context.Context, arg UpdateCertificationParams) (Certification, error)
	UpdateContactSubmissionStatus(ctx context.Context, arg UpdateContactSubmissionStatusParams) error
	UpdateCoreValue(ctx context.Context, arg UpdateCoreValueParams) (CoreValue, error)
	UpdateFooterColumnItem(ctx context.Context, arg UpdateFooterColumnItemParams) error
	UpdateFooterSettings(ctx context.Context, arg UpdateFooterSettingsParams) error
	UpdateGlobalSettings(ctx context.Context, arg UpdateGlobalSettingsParams) error
	UpdateHeaderSettings(ctx context.Context, arg UpdateHeaderSettingsParams) error
	UpdateHero(ctx context.Context, arg UpdateHeroParams) error
	UpdateHomepageSettings(ctx context.Context, arg UpdateHomepageSettingsParams) error
	UpdateIndustry(ctx context.Context, arg UpdateIndustryParams) (Industry, error)
	UpdateLastLogin(ctx context.Context, id int64) error
	UpdateMediaFileAltText(ctx context.Context, arg UpdateMediaFileAltTextParams) error
	UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error)
	UpdateNavigationItem(ctx context.Context, arg UpdateNavigationItemParams) error
	UpdateNavigationItemOrder(ctx context.Context, arg UpdateNavigationItemOrderParams) error
	UpdateNavigationMenu(ctx context.Context, arg UpdateNavigationMenuParams) error
	UpdateOfficeLocation(ctx context.Context, arg UpdateOfficeLocationParams) error
	UpdatePageSection(ctx context.Context, arg UpdatePageSectionParams) error
	UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (Partner, error)
	UpdatePartnerTier(ctx context.Context, arg UpdatePartnerTierParams) (PartnerTier, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
	UpdateProductsSettings(ctx context.Context, arg UpdateProductsSettingsParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
	UpdateSolution(ctx context.Context, arg UpdateSolutionParams) error
	UpdateSolutionCTA(ctx context.Context, arg UpdateSolutionCTAParams) error
	UpdateSolutionChallenge(ctx context.Context, arg UpdateSolutionChallengeParams) error
	UpdateSolutionPageFeature(ctx context.Context, arg UpdateSolutionPageFeatureParams) error
	UpdateSolutionStat(ctx context.Context, arg UpdateSolutionStatParams) error
	UpdateSolutionsListingCTA(ctx context.Context, arg UpdateSolutionsListingCTAParams) error
	UpdateSolutionsSettings(ctx context.Context, arg UpdateSolutionsSettingsParams) error
	UpdateStat(ctx context.Context, arg UpdateStatParams) error
	UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) (PartnerTestimonial, error)
	UpdateTestimonialHomepage(ctx context.Context, arg UpdateTestimonialHomepageParams) error
	UpdateWhitepaper(ctx context.Context, arg UpdateWhitepaperParams) error
	UpdateWhitepaperTopic(ctx context.Context, arg UpdateWhitepaperTopicParams) (WhitepaperTopic, error)
	UpsertCompanyOverview(ctx context.Context, arg UpsertCompanyOverviewParams) (CompanyOverview, error)
	UpsertMissionVisionValues(ctx context.Context, arg UpsertMissionVisionValuesParams) (MissionVisionValue, error)
}

var _ Querier = (*Queries)(nil)
