package middleware

import (
	// log/slog is Go's structured logging package, providing high-performance structured
	// logging with support for key-value pairs. Used here to log non-fatal errors when
	// loading settings or footer data fails, allowing the application to continue serving
	// requests even if some template data is unavailable.
	"log/slog"

	// github.com/labstack/echo/v4 is the Echo web framework, providing middleware
	// interfaces, context objects for storing loaded data, and request context utilities.
	"github.com/labstack/echo/v4"

	// github.com/narendhupati/bluejay-cms/db/sqlc provides type-safe database query
	// methods generated by sqlc from SQL query files. The Queries object is used to
	// fetch application settings and footer navigation data from the database.
	"github.com/narendhupati/bluejay-cms/db/sqlc"
)

// SettingsLoader returns an Echo middleware that pre-loads application settings and footer
// navigation data from the database and makes them available to templates and handlers.
// This middleware runs on every request to ensure that templates always have access to:
//   - Site-wide settings (site name, logo, contact info, etc.)
//   - Footer navigation categories (product categories)
//   - Footer navigation solutions (published solution pages)
//   - Footer navigation resources (custom footer links)
//
// By loading this data in middleware rather than in each individual handler, we:
//  1. Reduce code duplication (DRY principle)
//  2. Ensure consistent data availability across all templates
//  3. Centralize the data loading logic for easier maintenance
//  4. Make it impossible to forget to load required template data
//
// The middleware is resilient to database errors: if any query fails, it logs a warning
// but continues processing the request. This ensures that temporary database issues don't
// bring down the entire site. Templates should handle missing data gracefully using
// conditional rendering (e.g., {{if .settings}}...{{end}}).
//
// Parameters:
//   - queries: A sqlc.Queries instance configured with a database connection. This object
//     provides type-safe methods for executing parameterized SQL queries defined in the
//     db/queries/ directory.
//
// Returns:
//   - echo.MiddlewareFunc: A middleware function that loads settings and footer data
//     for each request.
//
// Example usage:
//
//	queries := sqlc.New(db)
//	e.Use(middleware.SettingsLoader(queries))
//
// Accessing loaded data in handlers:
//
//	settings := c.Get("settings").(sqlc.Setting)
//	categories := c.Get("footer_categories").([]sqlc.ProductCategory)
//
// Accessing loaded data in templates:
//
//	<h1>{{.settings.SiteName}}</h1>
//	{{range .footer_categories}}
//	    <a href="/category/{{.Slug}}">{{.Name}}</a>
//	{{end}}
//
// Performance considerations:
//   - Executes 4 database queries on every request (potential performance bottleneck)
//   - For high-traffic sites, consider adding caching (in-memory or Redis)
//   - Footer data rarely changes, so aggressive caching (5-60 minutes) is appropriate
//   - Settings data might change more frequently (requires shorter cache TTL)
//   - Consider adding a cache invalidation mechanism when settings/footer data is updated
//
// Data loaded and context keys:
//   - "settings": Application-wide settings (sqlc.Setting)
//   - "footer_categories": Product categories for footer navigation ([]sqlc.ProductCategory)
//   - "footer_solutions": Published solution pages for footer navigation ([]sqlc.Solution)
//   - "footer_resources": Custom footer resource links ([]sqlc.PageSection)
func SettingsLoader(queries *sqlc.Queries) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			// Extract the request context, which carries deadlines, cancellation signals,
			// and request-scoped values. This context is passed to database queries to
			// enable request cancellation and timeout handling at the database level.
			ctx := c.Request().Context()

			// Load application-wide settings from the database.
			// Settings typically include: site name, logo URL, contact email, social media
			// links, analytics IDs, and other configuration that affects the entire site.
			//
			// GetSettings() executes a SELECT query (defined in db/queries/settings.sql)
			// that retrieves a single row from the settings table. Most applications have
			// only one settings row (global configuration).
			settings, err := queries.GetSettings(ctx)
			if err != nil {
				// Log a warning if settings fail to load, but don't fail the request.
				// This allows the site to remain operational even if the settings table
				// is temporarily unavailable or misconfigured. Templates should check
				// for the existence of settings data before using it.
				//
				// Uses structured logging with key-value pairs for better log aggregation
				// and filtering in production log management systems.
				slog.Warn("settings middleware: failed to load settings", "error", err)
			} else {
				// Store the loaded settings in the Echo context under the key "settings".
				// Templates and handlers can access this via {{.settings}} or c.Get("settings").
				c.Set("settings", settings)
			}

			// Load product categories for the footer navigation.
			// Categories are typically organized hierarchically (e.g., Electronics > Laptops)
			// and are displayed in the footer to help users discover products.
			//
			// ListProductCategories() executes a SELECT query that retrieves all active
			// product categories, typically ordered by display order or name.
			categories, err := queries.ListProductCategories(ctx)
			if err != nil {
				// Log a warning but continue. The footer will render without categories
				// if this fails. Templates should handle empty slices gracefully.
				slog.Warn("settings middleware: failed to load footer categories", "error", err)
			} else {
				// Store the categories in the context for template access.
				// Templates can iterate over this with {{range .footer_categories}}...{{end}}.
				c.Set("footer_categories", categories)
			}

			// Load published solution pages for the footer navigation.
			// Solutions are typically case studies, use cases, or solution-oriented content
			// pages (e.g., "E-commerce Solutions", "Enterprise Solutions").
			//
			// ListPublishedSolutions() retrieves only solutions with published=true, ensuring
			// that draft or unpublished solutions don't appear in the footer navigation.
			solutions, err := queries.ListPublishedSolutions(ctx)
			if err != nil {
				// Log a warning but continue. The footer will render without solutions
				// if this fails. Non-critical data loading should never break the request.
				slog.Warn("settings middleware: failed to load footer solutions", "error", err)
			} else {
				// Store the solutions in the context for template access.
				c.Set("footer_solutions", solutions)
			}

			// Load custom footer resource links (e.g., "About Us", "Privacy Policy", "Help").
			// The "footer" page section is a special section type used to store custom footer
			// links that don't fit into categories or solutions (informational pages, legal pages).
			//
			// ListPageSections() executes a SELECT query filtered by section_type="footer",
			// returning all page sections designated for footer display.
			resources, err := queries.ListPageSections(ctx, "footer")
			if err != nil {
				// Log a warning but continue. The footer will render without custom resource
				// links if this fails. Common footer links (categories, solutions) will still work.
				slog.Warn("settings middleware: failed to load footer resources", "error", err)
			} else {
				// Store the footer resources in the context for template access.
				c.Set("footer_resources", resources)
			}

			// All data loading is complete (successfully or with warnings logged).
			// Proceed to the next handler in the middleware chain. The loaded data is
			// now available in the Echo context for use by handlers and templates.
			return next(c)
		}
	}
}
