// Package admin provides HTTP handlers for the About section of the admin panel.
// This includes managing company overview, mission/vision/values, core values,
// milestones, and certifications.
package admin

import (
	// Standard library imports
	"database/sql" // SQL types for handling nullable database fields
	"log/slog"     // Structured logging for error and event tracking
	"net/http"     // HTTP status codes and request/response handling
	"strconv"      // String to int64 conversions for form values and URL params

	// Third-party imports
	"github.com/labstack/echo/v4" // Echo web framework for routing and context

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc"          // Generated sqlc queries for database operations
	"github.com/narendhupati/bluejay-cms/internal/services" // Cache service for invalidating page caches
)

// AboutHandler manages all admin operations related to the About page content.
// It handles CRUD operations for company overview, mission/vision/values,
// core values, milestones, and certifications.
type AboutHandler struct {
	queries *sqlc.Queries    // Database query interface generated by sqlc
	logger  *slog.Logger     // Structured logger for error and event logging
	cache   *services.Cache  // Cache service for invalidating page-level caches
}

// NewAboutHandler creates a new AboutHandler instance with required dependencies.
// Parameters:
//   - queries: sqlc-generated database query interface
//   - logger: structured logger for error and event tracking
//   - cache: cache service for page invalidation
func NewAboutHandler(queries *sqlc.Queries, logger *slog.Logger, cache *services.Cache) *AboutHandler {
	return &AboutHandler{queries: queries, logger: logger, cache: cache}
}

// ==================== COMPANY OVERVIEW ====================
// Company overview manages the primary "About Us" content including
// headline, tagline, descriptions, and hero/company images.

// OverviewEdit displays the company overview editing form.
// HTTP Method: GET
// Route: /admin/about/overview
// Template: admin/pages/about_overview_form.html (full page)
// HTMX: Not used - returns full page render
//
// This handler retrieves the current company overview data and renders
// the edit form. The overview is a singleton record (only one exists).
func (h *AboutHandler) OverviewEdit(c echo.Context) error {
	// Fetch the single company overview record from database
	overview, _ := h.queries.GetCompanyOverview(c.Request().Context())

	// Render the edit form template with current data
	return c.Render(http.StatusOK, "admin/pages/about_overview_form.html", map[string]interface{}{
		"Title": "Company Overview",
		"Item":  overview,
	})
}

// OverviewUpdate processes company overview form submissions.
// HTTP Method: POST
// Route: /admin/about/overview
// Template: None - redirects to GET /admin/about/overview
// HTMX: Not used - standard form submission with redirect
//
// This handler extracts form values, upserts the company overview record,
// invalidates the about page cache, logs the activity, and redirects back
// to the edit form.
func (h *AboutHandler) OverviewUpdate(c echo.Context) error {
	// Upsert (insert or update) the company overview with form data
	// sql.NullString is used for optional fields that can be NULL in database
	_, err := h.queries.UpsertCompanyOverview(c.Request().Context(), sqlc.UpsertCompanyOverviewParams{
		Headline:             c.FormValue("headline"),
		Tagline:              c.FormValue("tagline"),
		DescriptionMain:      c.FormValue("description_main"),
		DescriptionSecondary: sql.NullString{String: c.FormValue("description_secondary"), Valid: c.FormValue("description_secondary") != ""},
		DescriptionTertiary:  sql.NullString{String: c.FormValue("description_tertiary"), Valid: c.FormValue("description_tertiary") != ""},
		HeroImageUrl:         sql.NullString{String: c.FormValue("hero_image_url"), Valid: c.FormValue("hero_image_url") != ""},
		CompanyImageUrl:      sql.NullString{String: c.FormValue("company_image_url"), Valid: c.FormValue("company_image_url") != ""},
	})
	if err != nil {
		h.logger.Error("failed to upsert company overview", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached About page content since overview has changed
	h.cache.DeleteByPrefix("page:about")

	// Log the update activity for audit trail
	logActivity(c, "updated", "about", 0, "Overview", "Updated About Overview")

	// Redirect back to the overview edit page with SEE OTHER status
	return c.Redirect(http.StatusSeeOther, "/admin/about/overview")
}

// ==================== MISSION VISION VALUES ====================
// Mission, Vision, and Values manages the company's MVV statement,
// including mission text, vision text, values summary, and associated icons.

// MVVEdit displays the mission/vision/values editing form.
// HTTP Method: GET
// Route: /admin/about/mvv
// Template: admin/pages/about_mvv_form.html (full page)
// HTMX: Not used - returns full page render
//
// This handler retrieves the current MVV data and renders the edit form.
// Like the overview, MVV is a singleton record.
func (h *AboutHandler) MVVEdit(c echo.Context) error {
	// Fetch the single mission/vision/values record from database
	mvv, _ := h.queries.GetMissionVisionValues(c.Request().Context())

	// Render the edit form template with current MVV data
	return c.Render(http.StatusOK, "admin/pages/about_mvv_form.html", map[string]interface{}{
		"Title": "Mission, Vision & Values",
		"Item":  mvv,
	})
}

// MVVUpdate processes mission/vision/values form submissions.
// HTTP Method: POST
// Route: /admin/about/mvv
// Template: None - redirects to GET /admin/about/mvv
// HTMX: Not used - standard form submission with redirect
//
// This handler extracts form values, upserts the MVV record,
// invalidates the about page cache, logs the activity, and redirects.
func (h *AboutHandler) MVVUpdate(c echo.Context) error {
	// Upsert the mission/vision/values record with form data
	// ValuesSummary is optional and uses sql.NullString
	_, err := h.queries.UpsertMissionVisionValues(c.Request().Context(), sqlc.UpsertMissionVisionValuesParams{
		Mission:       c.FormValue("mission"),
		Vision:        c.FormValue("vision"),
		ValuesSummary: sql.NullString{String: c.FormValue("values_summary"), Valid: c.FormValue("values_summary") != ""},
		MissionIcon:   c.FormValue("mission_icon"),
		VisionIcon:    c.FormValue("vision_icon"),
		ValuesIcon:    c.FormValue("values_icon"),
	})
	if err != nil {
		h.logger.Error("failed to upsert mvv", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached About page content
	h.cache.DeleteByPrefix("page:about")

	// Log the update activity for audit trail
	logActivity(c, "updated", "about", 0, "MVV", "Updated About Mission/Vision/Values")

	// Redirect back to the MVV edit page
	return c.Redirect(http.StatusSeeOther, "/admin/about/mvv")
}

// ==================== CORE VALUES ====================
// Core values are individual value statements displayed on the About page.
// Each value has a title, description, icon, and display order.
// Multiple core values can exist and are sorted by display_order.

// CoreValuesList displays all core values in a list view.
// HTTP Method: GET
// Route: /admin/about/values
// Template: admin/pages/core_values_list.html (full page)
// HTMX: Not used - returns full page render
//
// This handler retrieves all core values ordered by display_order and
// renders them in a list view for browsing, editing, and deleting.
func (h *AboutHandler) CoreValuesList(c echo.Context) error {
	// Fetch all core values from database, ordered by display_order
	items, err := h.queries.ListCoreValues(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list core values", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the list template with all core values
	return c.Render(http.StatusOK, "admin/pages/core_values_list.html", map[string]interface{}{
		"Title": "Core Values",
		"Items": items,
	})
}

// CoreValueNew displays the form for creating a new core value.
// HTTP Method: GET
// Route: /admin/about/values/new
// Template: admin/pages/core_values_form.html (full page)
// HTMX: Not used - returns full page render
//
// This handler renders an empty form for creating a new core value.
// The form will POST to /admin/about/values when submitted.
func (h *AboutHandler) CoreValueNew(c echo.Context) error {
	// Render the form template with no existing item (new record)
	return c.Render(http.StatusOK, "admin/pages/core_values_form.html", map[string]interface{}{
		"Title":      "New Core Value",
		"FormAction": "/admin/about/values",
		"Item":       nil, // nil indicates this is a create operation
	})
}

// CoreValueCreate processes new core value form submissions.
// HTTP Method: POST
// Route: /admin/about/values
// Template: None - redirects to GET /admin/about/values
// HTMX: Not used - standard form submission with redirect
//
// This handler extracts form values, creates a new core value record,
// invalidates the about page cache, logs the activity, and redirects to the list.
func (h *AboutHandler) CoreValueCreate(c echo.Context) error {
	// Parse display_order from string to int64
	// Errors are silently ignored, defaulting to 0
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Insert the new core value into database
	_, err := h.queries.CreateCoreValue(c.Request().Context(), sqlc.CreateCoreValueParams{
		Title:        c.FormValue("title"),
		Description:  c.FormValue("description"),
		Icon:         c.FormValue("icon"),         // Icon class name (e.g., "fa-shield")
		DisplayOrder: order,                       // Controls sort order on frontend
	})
	if err != nil {
		h.logger.Error("failed to create core value", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached About page content
	h.cache.DeleteByPrefix("page:about")

	// Log the creation activity with the core value title
	logActivity(c, "created", "core_value", 0, c.FormValue("title"), "Created Core Value '%s'", c.FormValue("title"))

	// Redirect to the core values list page
	return c.Redirect(http.StatusSeeOther, "/admin/about/values")
}

// CoreValueEdit displays the form for editing an existing core value.
// HTTP Method: GET
// Route: /admin/about/values/:id/edit
// Template: admin/pages/core_values_form.html (full page)
// HTMX: Not used - returns full page render
//
// This handler retrieves a specific core value by ID and renders the edit form.
// The form will POST to /admin/about/values/:id when submitted.
func (h *AboutHandler) CoreValueEdit(c echo.Context) error {
	// Parse the ID parameter from the URL path
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch the core value record from database
	item, err := h.queries.GetCoreValue(c.Request().Context(), id)
	if err != nil {
		// Return 404 if core value not found
		return echo.NewHTTPError(http.StatusNotFound)
	}

	// Render the form template with existing core value data
	return c.Render(http.StatusOK, "admin/pages/core_values_form.html", map[string]interface{}{
		"Title":      "Edit Core Value",
		"FormAction": "/admin/about/values/" + c.Param("id"), // POST destination
		"Item":       item,                                    // Existing data for pre-filling form
	})
}

// CoreValueUpdate processes core value update form submissions.
// HTTP Method: POST
// Route: /admin/about/values/:id
// Template: None - redirects to GET /admin/about/values
// HTMX: Not used - standard form submission with redirect
//
// This handler extracts form values, updates the existing core value record,
// invalidates the about page cache, logs the activity, and redirects to the list.
func (h *AboutHandler) CoreValueUpdate(c echo.Context) error {
	// Parse the ID parameter from the URL path
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Parse display_order from form value
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Update the existing core value record in database
	_, err := h.queries.UpdateCoreValue(c.Request().Context(), sqlc.UpdateCoreValueParams{
		Title:        c.FormValue("title"),
		Description:  c.FormValue("description"),
		Icon:         c.FormValue("icon"),
		DisplayOrder: order,
		ID:           id, // WHERE clause identifier
	})
	if err != nil {
		h.logger.Error("failed to update core value", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached About page content
	h.cache.DeleteByPrefix("page:about")

	// Log the update activity with core value ID and title
	logActivity(c, "updated", "core_value", id, c.FormValue("title"), "Updated Core Value '%s'", c.FormValue("title"))

	// Redirect to the core values list page
	return c.Redirect(http.StatusSeeOther, "/admin/about/values")
}

// CoreValueDelete handles deletion of a core value.
// HTTP Method: DELETE
// Route: /admin/about/values/:id
// Template: None - returns HTTP 200 with no content (HTMX delete pattern)
// HTMX: Used - returns empty response, HTMX removes element from DOM
//
// This handler deletes a core value by ID, invalidates the about page cache,
// logs the activity, and returns a success response with no content.
// HTMX will automatically remove the deleted item from the list view.
func (h *AboutHandler) CoreValueDelete(c echo.Context) error {
	// Parse the ID parameter from the URL path
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Delete the core value from database
	if err := h.queries.DeleteCoreValue(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete core value", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached About page content
	h.cache.DeleteByPrefix("page:about")

	// Log the deletion activity with core value ID
	logActivity(c, "deleted", "core_value", id, "", "Deleted Core Value #%d", id)

	// Return 200 OK with no content - HTMX will handle DOM removal
	return c.NoContent(http.StatusOK)
}

// ==================== MILESTONES ====================
// Milestones represent key achievements or events in company history.
// Each milestone has a year, title, description, is_current flag, and display order.
// Multiple milestones can exist and are sorted by display_order.

// MilestonesList displays all milestones in a list view.
// HTTP Method: GET
// Route: /admin/about/milestones
// Template: admin/pages/milestones_list.html (full page)
// HTMX: Not used - returns full page render
//
// This handler retrieves all milestones ordered by display_order and
// renders them in a list view for browsing, editing, and deleting.
func (h *AboutHandler) MilestonesList(c echo.Context) error {
	// Fetch all milestones from database, ordered by display_order
	items, err := h.queries.ListMilestones(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list milestones", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the list template with all milestones
	return c.Render(http.StatusOK, "admin/pages/milestones_list.html", map[string]interface{}{
		"Title": "Milestones",
		"Items": items,
	})
}

// MilestoneNew displays the form for creating a new milestone.
// HTTP Method: GET
// Route: /admin/about/milestones/new
// Template: admin/pages/milestones_form.html (full page)
// HTMX: Not used - returns full page render
func (h *AboutHandler) MilestoneNew(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/milestones_form.html", map[string]interface{}{
		"Title":      "New Milestone",
		"FormAction": "/admin/about/milestones",
		"Item":       nil,
	})
}

// MilestoneCreate processes new milestone form submissions.
// HTTP Method: POST
// Route: /admin/about/milestones
// Template: None - redirects to GET /admin/about/milestones
// HTMX: Not used - standard form submission with redirect
//
// This handler parses year and is_current checkbox, creates the milestone,
// invalidates cache, logs activity, and redirects to the list.
func (h *AboutHandler) MilestoneCreate(c echo.Context) error {
	// Parse year and display_order from form values
	year, _ := strconv.ParseInt(c.FormValue("year"), 10, 64)
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Convert checkbox value to SQLite integer boolean (0 or 1)
	// Checkboxes send "on" when checked, nothing when unchecked
	isCurrent := int64(0)
	if c.FormValue("is_current") == "on" {
		isCurrent = 1
	}

	// Insert new milestone into database
	_, err := h.queries.CreateMilestone(c.Request().Context(), sqlc.CreateMilestoneParams{
		Year:         year,
		Title:        c.FormValue("title"),
		Description:  c.FormValue("description"),
		IsCurrent:    isCurrent, // Flag to highlight as current/ongoing milestone
		DisplayOrder: order,
	})
	if err != nil {
		h.logger.Error("failed to create milestone", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	h.cache.DeleteByPrefix("page:about")
	logActivity(c, "created", "milestone", 0, c.FormValue("title"), "Created Milestone '%s'", c.FormValue("title"))
	return c.Redirect(http.StatusSeeOther, "/admin/about/milestones")
}

// MilestoneEdit displays the form for editing an existing milestone.
// HTTP Method: GET
// Route: /admin/about/milestones/:id/edit
// Template: admin/pages/milestones_form.html (full page)
// HTMX: Not used - returns full page render
func (h *AboutHandler) MilestoneEdit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	item, err := h.queries.GetMilestone(c.Request().Context(), id)
	if err != nil {
		return echo.NewHTTPError(http.StatusNotFound)
	}
	return c.Render(http.StatusOK, "admin/pages/milestones_form.html", map[string]interface{}{
		"Title":      "Edit Milestone",
		"FormAction": "/admin/about/milestones/" + c.Param("id"),
		"Item":       item,
	})
}

// MilestoneUpdate processes milestone update form submissions.
// HTTP Method: POST
// Route: /admin/about/milestones/:id
// Template: None - redirects to GET /admin/about/milestones
// HTMX: Not used - standard form submission with redirect
func (h *AboutHandler) MilestoneUpdate(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	year, _ := strconv.ParseInt(c.FormValue("year"), 10, 64)
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Convert checkbox to integer boolean
	isCurrent := int64(0)
	if c.FormValue("is_current") == "on" {
		isCurrent = 1
	}

	// Update the existing milestone record
	_, err := h.queries.UpdateMilestone(c.Request().Context(), sqlc.UpdateMilestoneParams{
		Year:         year,
		Title:        c.FormValue("title"),
		Description:  c.FormValue("description"),
		IsCurrent:    isCurrent,
		DisplayOrder: order,
		ID:           id,
	})
	if err != nil {
		h.logger.Error("failed to update milestone", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	h.cache.DeleteByPrefix("page:about")
	logActivity(c, "updated", "milestone", id, c.FormValue("title"), "Updated Milestone '%s'", c.FormValue("title"))
	return c.Redirect(http.StatusSeeOther, "/admin/about/milestones")
}

// MilestoneDelete handles deletion of a milestone.
// HTTP Method: DELETE
// Route: /admin/about/milestones/:id
// Template: None - returns HTTP 200 with no content (HTMX delete pattern)
// HTMX: Used - returns empty response, HTMX removes element from DOM
func (h *AboutHandler) MilestoneDelete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	if err := h.queries.DeleteMilestone(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete milestone", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	h.cache.DeleteByPrefix("page:about")
	logActivity(c, "deleted", "milestone", id, "", "Deleted Milestone #%d", id)
	return c.NoContent(http.StatusOK)
}

// ==================== CERTIFICATIONS ====================
// Certifications represent industry certifications, awards, or accreditations.
// Each certification has a name, abbreviation, description, icon, and display order.

// CertificationsList displays all certifications in a list view.
// HTTP Method: GET
// Route: /admin/about/certifications
// Template: admin/pages/certifications_list.html (full page)
// HTMX: Not used - returns full page render
func (h *AboutHandler) CertificationsList(c echo.Context) error {
	items, err := h.queries.ListCertifications(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list certifications", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	return c.Render(http.StatusOK, "admin/pages/certifications_list.html", map[string]interface{}{
		"Title": "Certifications",
		"Items": items,
	})
}

// CertificationNew displays the form for creating a new certification.
// HTTP Method: GET
// Route: /admin/about/certifications/new
// Template: admin/pages/certifications_form.html (full page)
// HTMX: Not used - returns full page render
func (h *AboutHandler) CertificationNew(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/certifications_form.html", map[string]interface{}{
		"Title":      "New Certification",
		"FormAction": "/admin/about/certifications",
		"Item":       nil,
	})
}

// CertificationCreate processes new certification form submissions.
// HTTP Method: POST
// Route: /admin/about/certifications
// Template: None - redirects to GET /admin/about/certifications
// HTMX: Not used - standard form submission with redirect
//
// This handler creates a new certification with optional description and icon.
// Description and Icon use sql.NullString for nullable database fields.
func (h *AboutHandler) CertificationCreate(c echo.Context) error {
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Create certification with nullable description and icon fields
	_, err := h.queries.CreateCertification(c.Request().Context(), sqlc.CreateCertificationParams{
		Name:         c.FormValue("name"),         // Full name (e.g., "ISO 9001:2015")
		Abbreviation: c.FormValue("abbreviation"), // Short form (e.g., "ISO 9001")
		Description:  sql.NullString{String: c.FormValue("description"), Valid: c.FormValue("description") != ""},
		Icon:         sql.NullString{String: c.FormValue("icon"), Valid: c.FormValue("icon") != ""},
		DisplayOrder: order,
	})
	if err != nil {
		h.logger.Error("failed to create certification", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	h.cache.DeleteByPrefix("page:about")
	logActivity(c, "created", "certification", 0, c.FormValue("name"), "Created Certification '%s'", c.FormValue("name"))
	return c.Redirect(http.StatusSeeOther, "/admin/about/certifications")
}

// CertificationEdit displays the form for editing an existing certification.
// HTTP Method: GET
// Route: /admin/about/certifications/:id/edit
// Template: admin/pages/certifications_form.html (full page)
// HTMX: Not used - returns full page render
func (h *AboutHandler) CertificationEdit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	item, err := h.queries.GetCertification(c.Request().Context(), id)
	if err != nil {
		return echo.NewHTTPError(http.StatusNotFound)
	}
	return c.Render(http.StatusOK, "admin/pages/certifications_form.html", map[string]interface{}{
		"Title":      "Edit Certification",
		"FormAction": "/admin/about/certifications/" + c.Param("id"),
		"Item":       item,
	})
}

// CertificationUpdate processes certification update form submissions.
// HTTP Method: POST
// Route: /admin/about/certifications/:id
// Template: None - redirects to GET /admin/about/certifications
// HTMX: Not used - standard form submission with redirect
func (h *AboutHandler) CertificationUpdate(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Update certification with nullable description and icon fields
	_, err := h.queries.UpdateCertification(c.Request().Context(), sqlc.UpdateCertificationParams{
		Name:         c.FormValue("name"),
		Abbreviation: c.FormValue("abbreviation"),
		Description:  sql.NullString{String: c.FormValue("description"), Valid: c.FormValue("description") != ""},
		Icon:         sql.NullString{String: c.FormValue("icon"), Valid: c.FormValue("icon") != ""},
		DisplayOrder: order,
		ID:           id,
	})
	if err != nil {
		h.logger.Error("failed to update certification", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	h.cache.DeleteByPrefix("page:about")
	logActivity(c, "updated", "certification", id, c.FormValue("name"), "Updated Certification '%s'", c.FormValue("name"))
	return c.Redirect(http.StatusSeeOther, "/admin/about/certifications")
}

// CertificationDelete handles deletion of a certification.
// HTTP Method: DELETE
// Route: /admin/about/certifications/:id
// Template: None - returns HTTP 200 with no content (HTMX delete pattern)
// HTMX: Used - returns empty response, HTMX removes element from DOM
func (h *AboutHandler) CertificationDelete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	if err := h.queries.DeleteCertification(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete certification", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	h.cache.DeleteByPrefix("page:about")
	logActivity(c, "deleted", "certification", id, "", "Deleted Certification #%d", id)
	return c.NoContent(http.StatusOK)
}
