package admin

import (
	// Standard library imports for data handling and HTTP operations
	"database/sql" // Handles SQL NULL types for optional description field
	"log/slog"     // Structured logging for error tracking
	"net/http"     // HTTP status codes and error responses
	"strconv"      // String to integer conversions for IDs and sort_order

	// Third-party framework imports
	"github.com/labstack/echo/v4" // Echo web framework for routing and context handling

	// Internal application imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // Generated SQL queries via sqlc
)

// BlogCategoriesHandler manages all HTTP handlers for blog category CRUD operations.
// Categories are used to organize blog posts and can have custom colors for UI theming.
type BlogCategoriesHandler struct {
	queries *sqlc.Queries // Database query interface generated by sqlc
	logger  *slog.Logger  // Structured logger for error tracking
}

// NewBlogCategoriesHandler constructs a new BlogCategoriesHandler with required dependencies.
func NewBlogCategoriesHandler(queries *sqlc.Queries, logger *slog.Logger) *BlogCategoriesHandler {
	return &BlogCategoriesHandler{queries: queries, logger: logger}
}

// List handles GET /admin/blog-categories
// Renders the complete list of all blog categories without pagination.
// Template: admin/pages/blog_categories_list.html (full page)
// Categories are typically displayed in sort_order ascending.
func (h *BlogCategoriesHandler) List(c echo.Context) error {
	// Fetch all blog categories from the database
	items, err := h.queries.ListBlogCategories(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list blog categories", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the full list page
	return c.Render(http.StatusOK, "admin/pages/blog_categories_list.html", map[string]interface{}{
		"Title": "Blog Categories",
		"Items": items,
	})
}

// New handles GET /admin/blog-categories/new
// Renders the create blog category form with empty fields.
// Template: admin/pages/blog_categories_form.html (full page)
// Form fields include name, color_hex, description (optional), and sort_order.
func (h *BlogCategoriesHandler) New(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/blog_categories_form.html", map[string]interface{}{
		"Title":      "New Blog Category",
		"FormAction": "/admin/blog-categories",
		"Item":       nil, // No existing category data
	})
}

// Create handles POST /admin/blog-categories
// Processes the blog category creation form submission.
// Auto-generates slug from name. color_hex is used for brutalist UI styling (borders/accents).
// Redirects to /admin/blog-categories on success.
func (h *BlogCategoriesHandler) Create(c echo.Context) error {
	// Parse sort_order and optional description from form
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)
	desc := c.FormValue("description")

	// Insert the blog category into the database
	// Slug is auto-generated from name, color_hex is a hex color code (e.g., "#FF6B35")
	_, err := h.queries.CreateBlogCategory(c.Request().Context(), sqlc.CreateBlogCategoryParams{
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),           // Auto-generate URL-friendly slug
		ColorHex:    c.FormValue("color_hex"),                // Hex color for category theming (e.g., "#FF6B35")
		Description: sql.NullString{String: desc, Valid: desc != ""}, // NULL if empty
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to create blog category", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the creation activity for audit trail
	logActivity(c, "created", "blog_category", 0, c.FormValue("name"), "Created blog_category '%s'", c.FormValue("name"))
	return c.Redirect(http.StatusSeeOther, "/admin/blog-categories")
}

// Edit handles GET /admin/blog-categories/:id/edit
// Renders the edit blog category form pre-filled with existing category data.
// Template: admin/pages/blog_categories_form.html (full page)
// Returns 404 if category ID does not exist.
func (h *BlogCategoriesHandler) Edit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch the existing category or return 404 if not found
	item, err := h.queries.GetBlogCategory(c.Request().Context(), id)
	if err != nil {
		return echo.NewHTTPError(http.StatusNotFound, "Category not found")
	}

	// Render form with existing category data pre-filled
	return c.Render(http.StatusOK, "admin/pages/blog_categories_form.html", map[string]interface{}{
		"Title":      "Edit Blog Category",
		"FormAction": "/admin/blog-categories/" + c.Param("id"),
		"Item":       item, // Existing category data
	})
}

// Update handles POST /admin/blog-categories/:id
// Processes the blog category update form submission.
// Regenerates slug from name on each update. color_hex can be changed for UI rebranding.
// Redirects to /admin/blog-categories on success.
func (h *BlogCategoriesHandler) Update(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Parse form values (same as Create handler)
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)
	desc := c.FormValue("description")

	// Update the blog category in the database
	// Slug is regenerated from name on each update
	_, err := h.queries.UpdateBlogCategory(c.Request().Context(), sqlc.UpdateBlogCategoryParams{
		ID:          id,
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),           // Regenerate slug from updated name
		ColorHex:    c.FormValue("color_hex"),                // Update color hex for category theming
		Description: sql.NullString{String: desc, Valid: desc != ""}, // NULL if empty
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to update blog category", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the update activity for audit trail
	logActivity(c, "updated", "blog_category", id, c.FormValue("name"), "Updated blog_category '%s'", c.FormValue("name"))
	return c.Redirect(http.StatusSeeOther, "/admin/blog-categories")
}

// Delete handles DELETE /admin/blog-categories/:id
// Deletes a blog category from the database.
// HTMX behavior: Returns 200 OK with no content, triggering client-side row removal.
// Note: May fail if category is referenced by existing blog posts (foreign key constraint).
func (h *BlogCategoriesHandler) Delete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Attempt to delete the category
	// Will fail if category is referenced by blog posts due to foreign key constraints
	if err := h.queries.DeleteBlogCategory(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete blog category", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the deletion activity for audit trail
	logActivity(c, "deleted", "blog_category", id, "", "Deleted blog_category #%d", id)

	// Return empty 200 OK response for HTMX to process
	return c.NoContent(http.StatusOK)
}
