// Package admin provides HTTP handlers for the Contact section of the admin panel.
// This includes managing contact form submissions and office locations.
package admin

import (
	// Standard library imports
	"database/sql" // SQL types for handling nullable database fields
	"fmt"          // String formatting for building dynamic routes and messages
	"log/slog"     // Structured logging for error and event tracking
	"net/http"     // HTTP status codes and request/response handling
	"net/url"
	"strconv"
	"strings" // String to int64 conversions for form values and URL params

	// Third-party imports
	"github.com/labstack/echo/v4" // Echo web framework for routing and context

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc"           // Generated sqlc queries for database operations
	"github.com/narendhupati/bluejay-cms/internal/services" // Cache service for invalidating page caches
)

// AdminContactHandler manages all admin operations related to contact form submissions
// and office locations. It handles viewing, filtering, status updates, and deletion
// of contact submissions, as well as CRUD operations for office locations.
type AdminContactHandler struct {
	queries *sqlc.Queries   // Database query interface generated by sqlc
	logger  *slog.Logger    // Structured logger for error and event logging
	cache   *services.Cache // Cache service for invalidating page-level caches
}

// NewAdminContactHandler creates a new AdminContactHandler instance with required dependencies.
// Parameters:
//   - queries: sqlc-generated database query interface
//   - logger: structured logger for error and event tracking
//   - cache: cache service for page invalidation
func NewAdminContactHandler(queries *sqlc.Queries, logger *slog.Logger, cache *services.Cache) *AdminContactHandler {
	return &AdminContactHandler{
		queries: queries,
		logger:  logger,
		cache:   cache,
	}
}

// ==================== CONTACT SUBMISSIONS ====================
// Contact submissions are form entries from the public-facing contact page.
// Each submission includes name, email, phone, company, inquiry type, message,
// status (new/read/replied/closed), and submission type (contact/rfq).

const contactInboxPath = "/admin/contact/submissions"

// contactQueue accepts only inbox filters, never an arbitrary redirect target.
type contactQueue struct {
	status, kind, search string
	page                 int64
}

func parseContactQueue(values url.Values) contactQueue {
	q := contactQueue{page: 1, search: values.Get("search")}
	switch values.Get("status") {
	case "new", "read", "replied", "closed":
		q.status = values.Get("status")
	}
	switch values.Get("type") {
	case "contact", "rfq":
		q.kind = values.Get("type")
	}
	if page, err := strconv.ParseInt(values.Get("page"), 10, 64); err == nil && page > 0 && page <= 1000000 {
		q.page = page
	}
	return q
}

func submissionReturnQueue(raw string) contactQueue {
	u, err := url.Parse(raw)
	if err != nil || u.IsAbs() || u.Host != "" || u.Path != contactInboxPath || u.Fragment != "" {
		return parseContactQueue(nil)
	}
	return parseContactQueue(u.Query())
}

func (q contactQueue) listURL() string {
	values := url.Values{"page": {strconv.FormatInt(q.page, 10)}}
	if q.status != "" {
		values.Set("status", q.status)
	}
	if q.kind != "" {
		values.Set("type", q.kind)
	}
	if q.search != "" {
		values.Set("search", q.search)
	}
	return contactInboxPath + "?" + values.Encode()
}

func (q contactQueue) detailURL(id int64) string {
	return fmt.Sprintf("%s/%d?%s", contactInboxPath, id, url.Values{"return_to": {q.listURL()}}.Encode())
}

// ListSubmissions applies the same search/status/type scope to rows, totals and detail links.
func (h *AdminContactHandler) ListSubmissions(c echo.Context) error {
	queue := parseContactQueue(c.QueryParams())
	ctx := c.Request().Context()
	const perPage int64 = 25
	count, err := h.queries.CountFilteredContactSubmissions(ctx, sqlc.CountFilteredContactSubmissionsParams{
		FilterStatus: queue.status, FilterType: queue.kind, FilterSearch: queue.search,
	})
	if err != nil {
		h.logger.Error("Failed to count contact submissions", "error", err)
		return renderOperationError(c, "Contact inbox unavailable", "We could not load the inbox. Try again, or contact your site administrator if this continues.", contactInboxPath)
	}
	totalPages := (count + perPage - 1) / perPage
	if totalPages > 0 && queue.page > totalPages {
		queue.page = totalPages
	}
	if totalPages == 0 {
		queue.page = 1
	}
	submissions, err := h.queries.ListFilteredContactSubmissions(ctx, sqlc.ListFilteredContactSubmissionsParams{
		FilterStatus: queue.status, FilterType: queue.kind, FilterSearch: queue.search,
		PageLimit: perPage, PageOffset: (queue.page - 1) * perPage,
	})
	if err != nil {
		h.logger.Error("Failed to list contact submissions", "error", err)
		return renderOperationError(c, "Contact inbox unavailable", "We could not load the inbox. Try again, or contact your site administrator if this continues.", contactInboxPath)
	}
	totalAll, _ := h.queries.CountContactSubmissions(ctx)
	totalContact, _ := h.queries.CountContactSubmissionsByType(ctx, "contact")
	totalRFQ, _ := h.queries.CountContactSubmissionsByType(ctx, "rfq")
	newCount, _ := h.queries.CountContactSubmissionsByStatus(ctx, "new")
	detailURLs := make(map[int64]string, len(submissions))
	for _, item := range submissions {
		detailURLs[item.ID] = queue.detailURL(item.ID)
	}
	previous, next := queue, queue
	previous.page--
	next.page++
	all, contact, rfq := queue, queue, queue
	all.kind, contact.kind, rfq.kind = "", "contact", "rfq"
	all.page, contact.page, rfq.page = 1, 1, 1
	return c.Render(http.StatusOK, "admin/pages/contact_submissions_list.html", map[string]interface{}{
		"Title": "Contact Submissions", "Submissions": submissions,
		"Page": int(queue.page), "TotalPages": totalPages, "TotalCount": count,
		"Status": queue.status, "Type": queue.kind, "Search": queue.search,
		"TotalAll": totalAll, "TotalContact": totalContact, "TotalRFQ": totalRFQ, "NewCount": newCount,
		"ReturnURL": queue.listURL(), "DetailURLs": detailURLs,
		"PreviousPageURL": previous.listURL(), "NextPageURL": next.listURL(),
		"AllTypeURL": all.listURL(), "ContactTypeURL": contact.listURL(), "RFQTypeURL": rfq.listURL(),
	})
}

// ViewSubmission displays a single contact submission in detail view.
// HTTP Method: GET
// Route: /admin/contact/submissions/:id
// Template: admin/pages/contact_submission_detail.html (full page)
// HTMX: Not used - returns full page render
//
// This handler retrieves a specific submission by ID and provides prev/next
// navigation IDs for browsing through submissions sequentially.
func (h *AdminContactHandler) ViewSubmission(c echo.Context) error {
	// Parse submission ID from URL parameter
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return c.String(http.StatusBadRequest, "Invalid submission ID")
	}

	ctx := c.Request().Context()

	// Fetch the full submission record from database
	submission, err := h.queries.GetContactSubmissionByID(ctx, id)
	if err != nil {
		h.logger.Error("Failed to get contact submission", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to load submission")
	}

	queue := submissionReturnQueue(c.QueryParam("return_to"))
	prevID, prevErr := h.queries.GetPreviousFilteredSubmissionID(ctx, sqlc.GetPreviousFilteredSubmissionIDParams{
		CurrentID: id, FilterStatus: queue.status, FilterType: queue.kind, FilterSearch: queue.search,
	})
	nextID, nextErr := h.queries.GetNextFilteredSubmissionID(ctx, sqlc.GetNextFilteredSubmissionIDParams{
		CurrentID: id, FilterStatus: queue.status, FilterType: queue.kind, FilterSearch: queue.search,
	})
	for _, navErr := range []error{prevErr, nextErr} {
		if navErr != nil && navErr != sql.ErrNoRows {
			h.logger.Error("Failed to load contact queue navigation", "error", navErr)
			return renderOperationError(c, "Contact queue unavailable", "We could not load this queue. Return to the inbox and try again.", queue.listURL())
		}
	}
	return c.Render(http.StatusOK, "admin/pages/contact_submission_detail.html", map[string]interface{}{
		"Title": "Contact Submission", "Submission": submission,
		"PrevID": prevID, "NextID": nextID,
		"PrevURL": queue.detailURL(prevID), "NextURL": queue.detailURL(nextID), "ReturnURL": queue.listURL(),
	})
}

// UpdateSubmissionStatus updates the status and notes of a contact submission.
// HTTP Method: POST
// Route: /admin/contact/submissions/:id/status
// Template: None - redirects to GET /admin/contact/submissions/:id
// HTMX: Not used - standard form submission with redirect
//
// This handler allows changing the submission status (new → reviewed → responded → archived)
// and optionally adding internal notes visible only to admins.
func (h *AdminContactHandler) UpdateSubmissionStatus(c echo.Context) error {
	// Parse submission ID from URL parameter
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return c.String(http.StatusBadRequest, "Invalid submission ID")
	}

	// Extract status and notes from form submission
	status := c.FormValue("status") // e.g., "reviewed", "responded", "archived"
	notes := c.FormValue("notes")   // Optional internal notes

	// Update the submission status and notes in database
	err = h.queries.UpdateContactSubmissionStatus(c.Request().Context(), sqlc.UpdateContactSubmissionStatusParams{
		Status: status,
		Notes:  sql.NullString{String: notes, Valid: notes != ""}, // NULL if notes are empty
		ID:     id,
	})
	if err != nil {
		h.logger.Error("Failed to update submission status", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to update status")
	}

	// Log the status update activity for audit trail
	logActivity(c, "updated", "contact_submission", id, "", "Updated Contact Submission #%d status", id)

	// Redirect back to the submission detail page
	return c.Redirect(http.StatusSeeOther, submissionReturnQueue(c.FormValue("return_to")).detailURL(id))
}

// BulkMarkRead marks all new submissions as read/reviewed in a single operation.
// HTTP Method: POST
// Route: /admin/contact/submissions/bulk-mark-read
// Template: None - redirects to GET /admin/contact/submissions
// HTMX: Not used - standard form submission with redirect
//
// This is a bulk operation that updates all submissions with status="new" to status="reviewed".
// Useful for clearing the "new submissions" badge when reviewing multiple items at once.
func (h *AdminContactHandler) BulkMarkRead(c echo.Context) error {
	// Update all submissions with status="new" to status="reviewed"
	err := h.queries.BulkMarkContactSubmissionsRead(c.Request().Context())
	if err != nil {
		h.logger.Error("Failed to bulk mark submissions as read", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to update")
	}

	// Redirect back to the submissions list
	return c.Redirect(http.StatusSeeOther, "/admin/contact/submissions")
}

// DeleteSubmission handles deletion of a contact submission.
// HTTP Method: DELETE
// Route: /admin/contact/submissions/:id
// Template: None - returns HTTP 200 with no content (HTMX delete pattern)
// HTMX: Used - returns empty response, HTMX removes element from DOM
//
// This permanently deletes a contact submission from the database.
func (h *AdminContactHandler) DeleteSubmission(c echo.Context) error {
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return c.String(http.StatusBadRequest, "Invalid submission ID")
	}

	// Permanently delete the submission from database
	err = h.queries.DeleteContactSubmission(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("Failed to delete contact submission", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to delete submission")
	}

	// Log the deletion activity for audit trail
	logActivity(c, "deleted", "contact_submission", id, "", "Deleted Contact Submission #%d", id)

	// Return 200 OK with no content - HTMX will handle DOM removal
	return c.NoContent(http.StatusOK)
}

// ==================== OFFICE LOCATIONS ====================
// Office locations represent physical company offices displayed on the contact page.
// Each location has address, phone, email, is_primary flag, is_active flag, and display order.

// ListOffices displays all office locations in a list view.
// HTTP Method: GET
// Route: /admin/contact/offices
// Template: admin/pages/office_locations_list.html (full page)
// HTMX: Not used - returns full page render
func (h *AdminContactHandler) ListOffices(c echo.Context) error {
	// Fetch all office locations from database, ordered by display_order
	offices, err := h.queries.ListAllOfficeLocations(c.Request().Context())
	if err != nil {
		h.logger.Error("Failed to list office locations", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to load offices")
	}

	// Render the list template with all office locations
	return c.Render(http.StatusOK, "admin/pages/office_locations_list.html", map[string]interface{}{
		"Title":   "Office Locations",
		"Offices": offices,
	})
}

// NewOffice displays the form for creating a new office location.
// HTTP Method: GET
// Route: /admin/contact/offices/new
// Template: admin/pages/office_locations_form.html (full page)
// HTMX: Not used - returns full page render
func (h *AdminContactHandler) NewOffice(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/office_locations_form.html", map[string]interface{}{
		"Title":      "New Office Location",
		"FormAction": "/admin/contact/offices",
		"Item":       nil,
		"IsNew":      true, // Flag for template to show "Create" vs "Update" button
	})
}

// CreateOffice handles office location creation.
// HTTP Method: POST
// Route: /admin/contact/offices
// Template: None - redirects to GET /admin/contact/offices
// HTMX: Not used - standard form submission with redirect
//
// This handler creates a new office location with full address, contact info,
// and flags for primary/active status. If marked as primary, it automatically
// unsets the primary flag on all other offices to ensure only one primary location.
func (h *AdminContactHandler) CreateOffice(c echo.Context) error {
	// Extract all address and contact form fields
	name := c.FormValue("name")                  // Office name (e.g., "Headquarters")
	addressLine1 := c.FormValue("address_line1") // Street address
	addressLine2 := c.FormValue("address_line2") // Suite/building/floor (optional)
	city := c.FormValue("city")
	state := c.FormValue("state")            // State/province
	postalCode := c.FormValue("postal_code") // ZIP/postal code
	country := c.FormValue("country")
	phone := c.FormValue("phone") // Office phone number
	email := c.FormValue("email") // Office email
	mapURL := strings.TrimSpace(c.FormValue("map_url"))
	if !services.ValidOfficeMapURL(mapURL) {
		return h.invalidOfficeMap(c, 0)
	}

	// Convert checkbox values to SQLite integer booleans (0 or 1)
	isPrimary := int64(0)
	if v := c.FormValue("is_primary"); v == "on" || v == "1" {
		isPrimary = 1 // Mark as primary location (shown first on contact page)
	}

	isActive := int64(0)
	if v := c.FormValue("is_active"); v == "on" || v == "1" {
		isActive = 1 // Active offices are displayed on public contact page
	}

	// Parse display order with default of 0 if empty or invalid
	displayOrder := int64(0)
	if v := c.FormValue("display_order"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			displayOrder = parsed
		}
	}

	// Enforce single primary location constraint
	// If this office is being marked as primary, unset primary flag on all others
	if isPrimary == 1 {
		err := h.queries.UnsetPrimaryOfficeLocations(c.Request().Context())
		if err != nil {
			h.logger.Error("Failed to unset primary office locations", "error", err)
		}
	}

	// Build parameters for office creation
	// addressLine2, phone, and email are optional and use sql.NullString
	params := sqlc.CreateOfficeLocationParams{
		Name:         name,
		AddressLine1: addressLine1,
		AddressLine2: sql.NullString{String: addressLine2, Valid: addressLine2 != ""},
		City:         city,
		State:        state,
		PostalCode:   postalCode,
		Country:      country,
		Phone:        sql.NullString{String: phone, Valid: phone != ""},
		Email:        sql.NullString{String: email, Valid: email != ""},
		MapUrl:       mapURL,
		IsPrimary:    isPrimary,
		IsActive:     isActive,
		DisplayOrder: displayOrder,
	}

	// Insert the new office location into database
	_, err := h.queries.CreateOfficeLocation(c.Request().Context(), params)
	if err != nil {
		h.logger.Error("Failed to create office location", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to create office")
	}

	// Invalidate cached Contact page content
	h.cache.DeleteByPrefix("page:contact")

	// Log the creation activity with office name
	logActivity(c, "created", "office", 0, c.FormValue("name"), "Created Office '%s'", c.FormValue("name"))

	// Redirect to the office locations list
	return c.Redirect(http.StatusSeeOther, "/admin/contact/offices")
}

// EditOffice displays the form for editing an existing office location.
// HTTP Method: GET
// Route: /admin/contact/offices/:id/edit
// Template: admin/pages/office_locations_form.html (full page)
// HTMX: Not used - returns full page render
func (h *AdminContactHandler) EditOffice(c echo.Context) error {
	// Parse office ID from URL parameter
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return c.String(http.StatusBadRequest, "Invalid office ID")
	}

	// Fetch the existing office location from database
	office, err := h.queries.GetOfficeLocationByID(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("Failed to get office location", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to load office")
	}

	// Render the form template with existing office data
	return c.Render(http.StatusOK, "admin/pages/office_locations_form.html", map[string]interface{}{
		"Title":      "Edit Office Location",
		"FormAction": fmt.Sprintf("/admin/contact/offices/%d", id), // POST destination
		"Item":       office,                                       // Existing data for pre-filling form
		"IsNew":      false,                                        // Flag for template to show "Update" button
	})
}

// UpdateOffice handles office location updates.
// HTTP Method: POST
// Route: /admin/contact/offices/:id
// Template: None - redirects to GET /admin/contact/offices
// HTMX: Not used - standard form submission with redirect
//
// This handler updates an existing office location. Like CreateOffice,
// it enforces the single primary location constraint.
func (h *AdminContactHandler) UpdateOffice(c echo.Context) error {
	// Parse office ID from URL parameter
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return c.String(http.StatusBadRequest, "Invalid office ID")
	}

	// Extract all form fields (same as CreateOffice)
	name := c.FormValue("name")
	addressLine1 := c.FormValue("address_line1")
	addressLine2 := c.FormValue("address_line2")
	city := c.FormValue("city")
	state := c.FormValue("state")
	postalCode := c.FormValue("postal_code")
	country := c.FormValue("country")
	phone := c.FormValue("phone")
	email := c.FormValue("email")
	mapURL := strings.TrimSpace(c.FormValue("map_url"))
	if !services.ValidOfficeMapURL(mapURL) {
		return h.invalidOfficeMap(c, id)
	}

	// Convert checkbox values to integer booleans
	isPrimary := int64(0)
	if v := c.FormValue("is_primary"); v == "on" || v == "1" {
		isPrimary = 1
	}

	isActive := int64(0)
	if v := c.FormValue("is_active"); v == "on" || v == "1" {
		isActive = 1
	}

	displayOrder := int64(0)
	if v := c.FormValue("display_order"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			displayOrder = parsed
		}
	}

	// Enforce single primary location constraint (same as CreateOffice)
	if isPrimary == 1 {
		err := h.queries.UnsetPrimaryOfficeLocations(c.Request().Context())
		if err != nil {
			h.logger.Error("Failed to unset primary office locations", "error", err)
		}
	}

	// Build parameters for office update
	params := sqlc.UpdateOfficeLocationParams{
		Name:         name,
		AddressLine1: addressLine1,
		AddressLine2: sql.NullString{String: addressLine2, Valid: addressLine2 != ""},
		City:         city,
		State:        state,
		PostalCode:   postalCode,
		Country:      country,
		Phone:        sql.NullString{String: phone, Valid: phone != ""},
		Email:        sql.NullString{String: email, Valid: email != ""},
		MapUrl:       mapURL,
		IsPrimary:    isPrimary,
		IsActive:     isActive,
		DisplayOrder: displayOrder,
		ID:           id, // WHERE clause identifier
	}

	// Update the existing office location in database
	err = h.queries.UpdateOfficeLocation(c.Request().Context(), params)
	if err != nil {
		h.logger.Error("Failed to update office location", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to update office")
	}

	// Invalidate cached Contact page content
	h.cache.DeleteByPrefix("page:contact")

	// Log the update activity with office ID and name
	logActivity(c, "updated", "office", id, c.FormValue("name"), "Updated Office '%s'", c.FormValue("name"))

	// Redirect to the office locations list
	return c.Redirect(http.StatusSeeOther, "/admin/contact/offices")
}

// DeleteOffice handles deletion of an office location.
// HTTP Method: DELETE
// Route: /admin/contact/offices/:id
// Template: None - returns HTTP 200 with no content (HTMX delete pattern)
// HTMX: Used - returns empty response, HTMX removes element from DOM
func (h *AdminContactHandler) DeleteOffice(c echo.Context) error {
	// Parse office ID from URL parameter
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return c.String(http.StatusBadRequest, "Invalid office ID")
	}

	// Permanently delete the office location from database
	err = h.queries.DeleteOfficeLocation(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("Failed to delete office location", "error", err)
		return c.String(http.StatusInternalServerError, "Failed to delete office")
	}

	// Invalidate cached Contact page content
	h.cache.DeleteByPrefix("page:contact")

	// Log the deletion activity with office ID
	logActivity(c, "deleted", "office", id, "", "Deleted Office #%d", id)

	// Return 200 OK with no content - HTMX will handle DOM removal
	return c.NoContent(http.StatusOK)
}

// Re-render invalid map input without discarding the rest of the office form.
func (h *AdminContactHandler) invalidOfficeMap(c echo.Context, id int64) error {
	item := sqlc.GetOfficeLocationByIDRow{
		ID: id, Name: c.FormValue("name"), AddressLine1: c.FormValue("address_line1"),
		AddressLine2: sql.NullString{String: c.FormValue("address_line2"), Valid: true},
		City:         c.FormValue("city"), State: c.FormValue("state"), PostalCode: c.FormValue("postal_code"), Country: c.FormValue("country"),
		Phone: sql.NullString{String: c.FormValue("phone"), Valid: true}, Email: sql.NullString{String: c.FormValue("email"), Valid: true}, MapUrl: c.FormValue("map_url"),
	}
	item.DisplayOrder, _ = strconv.ParseInt(c.FormValue("display_order"), 10, 64)
	if v := c.FormValue("is_primary"); v == "1" || v == "on" {
		item.IsPrimary = 1
	}
	if v := c.FormValue("is_active"); v == "1" || v == "on" {
		item.IsActive = 1
	}
	title, action := "New Office Location", "/admin/contact/offices"
	if id != 0 {
		title = "Edit Office Location"
		action = fmt.Sprintf("/admin/contact/offices/%d", id)
	}
	return c.Render(http.StatusBadRequest, "admin/pages/office_locations_form.html", map[string]interface{}{
		"Title": title, "FormAction": action, "Item": item, "IsNew": id == 0,
		"Error": "Enter a Google Maps HTTPS link (including a share or embed URL), or leave Map URL blank to use the office address.",
	})
}
