// Package admin provides HTTP handlers for the admin panel's footer management functionality.
// This file handles the configuration of the website footer, including multi-column layouts,
// footer links, legal links, social media settings, and copyright text.
package admin

import (
	// Standard library imports
	"fmt"      // String formatting for dynamic field names
	"log/slog" // Structured logging for error and debug output
	"net/http" // HTTP status codes and request/response handling
	"strconv"  // String to integer conversion for parsing form values

	// Third-party framework
	"github.com/labstack/echo/v4" // Echo web framework for routing and context handling

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // Database query layer generated by sqlc
)

// FooterHandler manages footer configuration for the website.
// It provides endpoints to view and update footer settings including column layout,
// footer links, legal links, social media visibility, and copyright information.
type FooterHandler struct {
	queries *sqlc.Queries // Database query interface for footer operations
	logger  *slog.Logger  // Structured logger for error tracking
}

// FooterColumnData is a template-friendly struct for each footer column.
// It aggregates column metadata and associated links for easy rendering in templates.
// Each footer can have 2-4 columns, each containing either links or rich text content.
type FooterColumnData struct {
	Heading string            // Column heading text (e.g., "Quick Links", "About Us")
	Type    string            // Column type: "links" or "text" (rich content)
	Content string            // Rich text content (used when Type is "text")
	Links   []sqlc.FooterLink // List of links (used when Type is "links")
}

// NewFooterHandler creates and initializes a new FooterHandler instance.
// It requires database queries interface and a logger for operation tracking.
//
// Parameters:
//   - queries: Database query layer for executing footer settings operations
//   - logger: Structured logger for error and activity logging
//
// Returns a fully initialized FooterHandler ready to handle HTTP requests.
func NewFooterHandler(queries *sqlc.Queries, logger *slog.Logger) *FooterHandler {
	return &FooterHandler{queries: queries, logger: logger}
}

// Edit renders the footer configuration form page.
//
// HTTP Method: GET
// Route: /admin/footer
// HTMX: Returns full page (not a fragment)
// Template: admin/pages/footer_form.html
//
// This handler retrieves and organizes all footer-related data for display in an editable form.
// It performs multiple database queries to fetch:
//   - Global footer settings (columns count, background style, social media settings, copyright)
//   - Footer column items (headings, types, content)
//   - Footer links organized by column
//   - Legal links (privacy policy, terms of service, etc.)
//
// The data is reorganized into a template-friendly structure that always provides 4 column slots,
// making it easy to render a consistent form interface regardless of how many columns are active.
//
// Query Parameters:
//   - saved: Set to "1" to display a success message after form submission
//
// Returns:
//   - 200 OK with rendered HTML form on success
//   - 500 Internal Server Error if any database query fails
func (h *FooterHandler) Edit(c echo.Context) error {
	ctx := c.Request().Context()

	// Retrieve global footer settings (columns count, background style, etc.)
	settings, err := h.queries.GetSettings(ctx)
	if err != nil {
		h.logger.Error("failed to load settings", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Retrieve all footer column items (metadata for each column)
	columnItems, err := h.queries.ListFooterColumnItems(ctx)
	if err != nil {
		h.logger.Error("failed to load footer column items", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Retrieve all footer links across all columns
	allLinks, err := h.queries.ListAllFooterLinks(ctx)
	if err != nil {
		h.logger.Error("failed to load footer links", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Retrieve legal links (displayed separately in footer bottom)
	legalLinks, err := h.queries.ListFooterLegalLinks(ctx)
	if err != nil {
		h.logger.Error("failed to load footer legal links", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Build links map keyed by column_item_id for quick lookup
	// This groups all links under their parent column
	linksMap := make(map[int64][]sqlc.FooterLink)
	for _, link := range allLinks {
		linksMap[link.ColumnItemID] = append(linksMap[link.ColumnItemID], link)
	}

	// Build columns map keyed by column_index (0-3)
	// This allows direct access to column data by position
	columnsMap := make(map[int64]sqlc.FooterColumnItem)
	for _, item := range columnItems {
		columnsMap[item.ColumnIndex] = item
	}

	// Build template-friendly ColumnData slice (always 4 entries)
	// This ensures the form always renders 4 column slots, even if some are empty
	// Empty slots default to "links" type for consistent UI behavior
	columnData := make([]FooterColumnData, 4)
	for i := 0; i < 4; i++ {
		col, ok := columnsMap[int64(i)]
		if ok {
			// Column exists in database, populate with actual data
			columnData[i] = FooterColumnData{
				Heading: col.Heading,
				Type:    col.Type,
				Content: col.Content,
				Links:   linksMap[col.ID], // Attach associated links
			}
		} else {
			// Column doesn't exist, provide default empty state
			columnData[i] = FooterColumnData{
				Type: "links", // Default to links type for empty columns
			}
		}
	}

	// Check if this is a redirect after successful save operation
	saved := c.QueryParam("saved") == "1"

	// Render the footer configuration form with all organized data
	return c.Render(http.StatusOK, "admin/pages/footer_form.html", map[string]interface{}{
		"Title":      "Footer Management",
		"Settings":   settings,    // Global footer settings
		"Saved":      saved,       // Success flag to show confirmation message
		"ColumnData": columnData,  // Organized column data (always 4 slots)
		"LegalLinks": legalLinks,  // Legal/compliance links for footer bottom
	})
}

// Update processes the footer configuration form submission and saves changes to the database.
//
// HTTP Method: POST
// Route: /admin/footer
// HTMX: Not used for this endpoint (standard form POST)
// Template: None (redirects to Edit handler)
//
// This handler performs a complex update operation that includes:
//   1. Updating global footer settings (columns count, background style, social media, copyright)
//   2. Deleting all existing column items and their associated links
//   3. Recreating column items based on form data
//   4. Creating new links for each column (if column type is "links")
//   5. Deleting and recreating legal links
//
// The delete-and-recreate approach simplifies handling of dynamic form arrays and ensures
// data consistency without complex diff logic.
//
// Form Fields:
//   - footer_columns: Number of columns to display (2-4, defaults to 4)
//   - footer_bg_style: Background styling class/identifier
//   - footer_show_social: Checkbox for social media icons visibility
//   - footer_social_style: Social media icons display style
//   - footer_copyright: Copyright text displayed in footer
//   - col_{N}_type: Type for column N ("links" or "text")
//   - col_{N}_heading: Heading text for column N
//   - col_{N}_content: Rich text content for column N (if type is "text")
//   - col_{N}_link_label[]: Array of link labels for column N (if type is "links")
//   - col_{N}_link_url[]: Array of link URLs for column N (if type is "links")
//   - legal_link_label[]: Array of legal link labels
//   - legal_link_url[]: Array of legal link URLs
//
// Returns:
//   - 303 See Other redirect to /admin/footer?saved=1 on success
//   - 500 Internal Server Error if any database operation fails
func (h *FooterHandler) Update(c echo.Context) error {
	ctx := c.Request().Context()

	// Parse and validate footer columns count (must be between 2 and 4)
	footerColumns, _ := strconv.ParseInt(c.FormValue("footer_columns"), 10, 64)
	if footerColumns < 2 || footerColumns > 4 {
		footerColumns = 4 // Default to maximum columns if invalid
	}

	// Parse social media visibility toggle (checkbox converts to int64 for SQLite)
	var footerShowSocial int64
	if c.FormValue("footer_show_social") == "on" {
		footerShowSocial = 1
	}

	// Update global footer settings in database
	err := h.queries.UpdateFooterSettings(ctx, sqlc.UpdateFooterSettingsParams{
		FooterColumns:     footerColumns,
		FooterBgStyle:     c.FormValue("footer_bg_style"),
		FooterShowSocial:  footerShowSocial,
		FooterSocialStyle: c.FormValue("footer_social_style"),
		FooterCopyright:   c.FormValue("footer_copyright"),
	})
	if err != nil {
		h.logger.Error("failed to update footer settings", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Delete all existing column items and their associated links
	// This approach is simpler than updating existing items and handling additions/deletions
	existingItems, err := h.queries.ListFooterColumnItems(ctx)
	if err != nil {
		h.logger.Error("failed to list existing column items", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	for _, item := range existingItems {
		// Delete links first (foreign key constraint)
		_ = h.queries.DeleteFooterLinksByColumnItem(ctx, item.ID)
		// Then delete the column item itself
		_ = h.queries.DeleteFooterColumnItem(ctx, item.ID)
	}

	// Create new column items based on form data
	// Only create columns up to the specified footerColumns count
	for i := int64(0); i < footerColumns; i++ {
		// Form fields are namespaced with column index (e.g., "col_0_type", "col_1_heading")
		prefix := fmt.Sprintf("col_%d_", i)
		colType := c.FormValue(prefix + "type")
		if colType == "" {
			colType = "links" // Default to links type if not specified
		}

		heading := c.FormValue(prefix + "heading")
		content := c.FormValue(prefix + "content") // Only used if type is "text"

		// Create the column item record
		colItem, err := h.queries.CreateFooterColumnItem(ctx, sqlc.CreateFooterColumnItemParams{
			ColumnIndex: i,       // Position in footer layout (0-3)
			Type:        colType, // "links" or "text"
			Heading:     heading,
			Content:     content,
			SortOrder:   i, // Same as column index for consistent ordering
		})
		if err != nil {
			h.logger.Error("failed to create footer column item", "error", err)
			return echo.NewHTTPError(http.StatusInternalServerError)
		}

		// If column type is "links", create link records from form arrays
		// Links are submitted as parallel arrays: link_label[] and link_url[]
		if colType == "links" {
			labels := c.Request().Form[prefix+"link_label[]"]
			urls := c.Request().Form[prefix+"link_url[]"]
			// Iterate through both arrays simultaneously
			for j := 0; j < len(labels) && j < len(urls); j++ {
				// Skip empty entries (user may have added but not filled in a link row)
				if labels[j] == "" && urls[j] == "" {
					continue
				}
				_, err := h.queries.CreateFooterLink(ctx, sqlc.CreateFooterLinkParams{
					ColumnItemID: colItem.ID, // Associate with parent column
					Label:        labels[j],
					Url:          urls[j],
					SortOrder:    int64(j), // Preserve order from form
				})
				if err != nil {
					h.logger.Error("failed to create footer link", "error", err)
					// Continue processing other links even if one fails
				}
			}
		}
	}

	// Update legal links section (privacy policy, terms, etc.)
	// Delete all existing legal links first
	_ = h.queries.DeleteAllFooterLegalLinks(ctx)

	// Create new legal links from form arrays
	legalLabels := c.Request().Form["legal_link_label[]"]
	legalUrls := c.Request().Form["legal_link_url[]"]
	for i := 0; i < len(legalLabels) && i < len(legalUrls); i++ {
		// Skip empty entries
		if legalLabels[i] == "" && legalUrls[i] == "" {
			continue
		}
		_, err := h.queries.CreateFooterLegalLink(ctx, sqlc.CreateFooterLegalLinkParams{
			Label:     legalLabels[i],
			Url:       legalUrls[i],
			SortOrder: int64(i), // Preserve order from form
		})
		if err != nil {
			h.logger.Error("failed to create legal link", "error", err)
			// Continue processing other links even if one fails
		}
	}

	// Log the update activity for audit trail
	logActivity(c, "updated", "footer", 0, "", "Updated Footer Settings")

	// Redirect back to the edit form with saved parameter to show success message
	return c.Redirect(http.StatusSeeOther, "/admin/footer?saved=1")
}
