// Package admin provides HTTP handlers for the admin panel's header management functionality.
// This file handles the configuration of the website header, including logo, navigation items,
// call-to-action buttons, and visibility toggles for navigation sections.
package admin

import (
	// Standard library imports
	"log/slog" // Structured logging for error and debug output
	"net/http" // HTTP status codes and request/response handling

	// Third-party framework
	"github.com/labstack/echo/v4" // Echo web framework for routing and context handling

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // Database query layer generated by sqlc
)

// HeaderHandler manages header configuration for the website.
// It provides endpoints to view and update header settings including logo,
// CTA buttons, contact information visibility, and navigation menu items.
type HeaderHandler struct {
	queries *sqlc.Queries // Database query interface for settings operations
	logger  *slog.Logger  // Structured logger for error tracking
}

// NewHeaderHandler creates and initializes a new HeaderHandler instance.
// It requires database queries interface and a logger for operation tracking.
//
// Parameters:
//   - queries: Database query layer for executing header settings operations
//   - logger: Structured logger for error and activity logging
//
// Returns a fully initialized HeaderHandler ready to handle HTTP requests.
func NewHeaderHandler(queries *sqlc.Queries, logger *slog.Logger) *HeaderHandler {
	return &HeaderHandler{queries: queries, logger: logger}
}

// Edit renders the header configuration form page.
//
// HTTP Method: GET
// Route: /admin/header
// HTMX: Returns full page (not a fragment)
// Template: admin/pages/header_form.html
//
// This handler retrieves all current header settings from the database and displays
// them in an editable form. The form includes fields for:
//   - Header logo path and alt text
//   - CTA button configuration (enabled, text, URL, style)
//   - Contact information visibility (phone, email, social media)
//   - Navigation menu item visibility and labels
//
// Query Parameters:
//   - saved: Set to "1" to display a success message after form submission
//
// Returns:
//   - 200 OK with rendered HTML form on success
//   - 500 Internal Server Error if database query fails
func (h *HeaderHandler) Edit(c echo.Context) error {
	// Retrieve current header settings from database
	settings, err := h.queries.GetSettings(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to load settings", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Check if this is a redirect after successful save operation
	saved := c.QueryParam("saved") == "1"

	// Render the header configuration form with current settings
	return c.Render(http.StatusOK, "admin/pages/header_form.html", map[string]interface{}{
		"Title":    "Header Management",
		"Settings": settings, // Current header configuration data
		"Saved":    saved,    // Success flag to show confirmation message
	})
}

// Update processes the header configuration form submission and saves changes to the database.
//
// HTTP Method: POST
// Route: /admin/header
// HTMX: Not used for this endpoint (standard form POST)
// Template: None (redirects to Edit handler)
//
// This handler parses form data from the header configuration form and updates the database
// with new settings. It handles:
//   - Logo configuration (path and alt text)
//   - CTA button settings (enable/disable, text, URL, style)
//   - Contact information visibility toggles (phone, email, social media)
//   - Navigation menu visibility and custom labels for all nav sections
//
// Form Fields:
//   - header_logo_path, header_logo_alt: Logo configuration
//   - header_cta_enabled, header_cta_text, header_cta_url, header_cta_style: CTA button settings
//   - header_show_phone, header_show_email, header_show_social: Contact visibility toggles
//   - header_social_style: Social media icons display style
//   - show_nav_*: Boolean toggles for each navigation section visibility
//   - nav_label_*: Custom labels for each navigation section
//
// Note: Checkbox values are converted from "on" string to boolean.
// After successful update, logs the activity and redirects back to the edit form with saved=1.
//
// Returns:
//   - 303 See Other redirect to /admin/header?saved=1 on success
//   - 500 Internal Server Error if database update fails
func (h *HeaderHandler) Update(c echo.Context) error {
	// Parse all form fields and update header settings in the database
	// Checkbox fields: value "on" indicates checked, missing/empty indicates unchecked
	err := h.queries.UpdateHeaderSettings(c.Request().Context(), sqlc.UpdateHeaderSettingsParams{
		// Logo configuration
		HeaderLogoPath: c.FormValue("header_logo_path"),
		HeaderLogoAlt:  c.FormValue("header_logo_alt"),

		// CTA (Call-to-Action) button configuration
		HeaderCtaEnabled: c.FormValue("header_cta_enabled") == "on", // Convert checkbox to boolean
		HeaderCtaText:    c.FormValue("header_cta_text"),
		HeaderCtaUrl:     c.FormValue("header_cta_url"),
		HeaderCtaStyle:   c.FormValue("header_cta_style"),

		// Contact information visibility toggles
		HeaderShowPhone:  c.FormValue("header_show_phone") == "on",  // Show/hide phone number
		HeaderShowEmail:  c.FormValue("header_show_email") == "on",  // Show/hide email address
		HeaderShowSocial: c.FormValue("header_show_social") == "on", // Show/hide social media icons
		HeaderSocialStyle: c.FormValue("header_social_style"),       // Icon style (e.g., "simple", "colored")

		// Navigation menu visibility toggles for each section
		ShowNavProducts:    c.FormValue("show_nav_products") == "on",
		ShowNavSolutions:   c.FormValue("show_nav_solutions") == "on",
		ShowNavCaseStudies: c.FormValue("show_nav_case_studies") == "on",
		ShowNavAbout:       c.FormValue("show_nav_about") == "on",
		ShowNavBlog:        c.FormValue("show_nav_blog") == "on",
		ShowNavWhitepapers: c.FormValue("show_nav_whitepapers") == "on",
		ShowNavPartners:    c.FormValue("show_nav_partners") == "on",
		ShowNavContact:     c.FormValue("show_nav_contact") == "on",

		// Custom labels for each navigation section (allows renaming menu items)
		NavLabelProducts:    c.FormValue("nav_label_products"),
		NavLabelSolutions:   c.FormValue("nav_label_solutions"),
		NavLabelCaseStudies: c.FormValue("nav_label_case_studies"),
		NavLabelAbout:       c.FormValue("nav_label_about"),
		NavLabelBlog:        c.FormValue("nav_label_blog"),
		NavLabelWhitepapers: c.FormValue("nav_label_whitepapers"),
		NavLabelPartners:    c.FormValue("nav_label_partners"),
		NavLabelContact:     c.FormValue("nav_label_contact"),
	})

	if err != nil {
		h.logger.Error("failed to update header settings", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the update activity for audit trail (uses helper function from activity.go)
	logActivity(c, "updated", "header", 0, "", "Updated Header Settings")

	// Redirect back to the edit form with saved parameter to show success message
	return c.Redirect(http.StatusSeeOther, "/admin/header?saved=1")
}
