// Package admin provides HTTP handlers for the Homepage section of the admin panel.
// This includes managing heroes, stats, testimonials, CTAs, and homepage settings.
package admin

import (
	// Standard library imports
	"database/sql" // SQL types for handling nullable database fields
	"fmt"          // String formatting for building dynamic routes
	"log/slog"     // Structured logging for error and event tracking
	"net/http"     // HTTP status codes and request/response handling
	"strconv"      // String to int64 conversions for form values and URL params
	"strings"      // String manipulation for trimming and parsing form values

	// Third-party imports
	"github.com/labstack/echo/v4" // Echo web framework for routing and context

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // Generated sqlc queries for database operations
)

// HomepageHandler manages all admin operations related to the Homepage content.
// It handles CRUD operations for homepage heroes, stats, testimonials, CTAs,
// and global homepage settings. Note: This handler does not use a cache service
// since homepage content changes are immediate.
type HomepageHandler struct {
	queries *sqlc.Queries // Database query interface generated by sqlc
	logger  *slog.Logger  // Structured logger for error and event logging
}

// NewHomepageHandler creates a new HomepageHandler instance with required dependencies.
// Parameters:
//   - queries: sqlc-generated database query interface
//   - logger: structured logger for error and event tracking
func NewHomepageHandler(queries *sqlc.Queries, logger *slog.Logger) *HomepageHandler {
	return &HomepageHandler{queries: queries, logger: logger}
}

// ==================== HEROES ====================
// Homepage heroes are large banner/carousel items displayed at the top of the homepage.
// Each hero includes headline, subheadline, optional badge, CTA buttons, background image,
// is_active flag, and display order. Multiple heroes can exist for carousel rotation.

// HeroesList displays all homepage heroes in a list view.
// HTTP Method: GET
// Route: /admin/homepage/heroes
// Template: admin/pages/homepage_heroes_list.html (full page)
// HTMX: Not used - returns full page render
//
// This handler retrieves all heroes ordered by display_order and renders them
// in a list view for browsing, editing, and deleting.
func (h *HomepageHandler) HeroesList(c echo.Context) error {
	// Fetch all heroes from database, ordered by display_order
	items, err := h.queries.ListAllHeroes(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list heroes", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the list template with all heroes
	return c.Render(http.StatusOK, "admin/pages/homepage_heroes_list.html", map[string]interface{}{
		"Title": "Homepage Heroes",
		"Items": items,
	})
}

// HeroNew displays the form for creating a new homepage hero.
// HTTP Method: GET
// Route: /admin/homepage/heroes/new
// Template: admin/pages/homepage_hero_form.html (full page)
// HTMX: Not used - returns full page render
func (h *HomepageHandler) HeroNew(c echo.Context) error {
	// Render form with empty hero struct for new record
	return c.Render(http.StatusOK, "admin/pages/homepage_hero_form.html", map[string]interface{}{
		"Title": "New Hero",
		"Item":  sqlc.HomepageHero{}, // Empty struct for new hero
	})
}

// HeroCreate processes new homepage hero form submissions.
// HTTP Method: POST
// Route: /admin/homepage/heroes
// Template: None - redirects to GET /admin/homepage/heroes
// HTMX: Not used - standard form submission with redirect
//
// This handler creates a new hero with headline, subheadline, optional badge,
// primary and optional secondary CTAs, optional background image, is_active flag,
// and display order for carousel sequencing.
func (h *HomepageHandler) HeroCreate(c echo.Context) error {
	// Parse display_order and is_active checkbox from form
	displayOrder, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1 // Active heroes are visible on homepage
	}
	// Create new hero record with form data
	// Optional fields (badge, secondary CTA, background image) use sql.NullString
	_, err := h.queries.CreateHero(c.Request().Context(), sqlc.CreateHeroParams{
		Headline:         c.FormValue("headline"),         // Main heading text
		Subheadline:      c.FormValue("subheadline"),      // Supporting text
		BadgeText:        sql.NullString{String: c.FormValue("badge_text"), Valid: c.FormValue("badge_text") != ""},       // Optional badge/label
		PrimaryCtaText:   c.FormValue("primary_cta_text"), // Primary button text (required)
		PrimaryCtaUrl:    c.FormValue("primary_cta_url"),  // Primary button URL (required)
		SecondaryCtaText: sql.NullString{String: c.FormValue("secondary_cta_text"), Valid: c.FormValue("secondary_cta_text") != ""}, // Optional secondary button text
		SecondaryCtaUrl:  sql.NullString{String: c.FormValue("secondary_cta_url"), Valid: c.FormValue("secondary_cta_url") != ""},   // Optional secondary button URL
		BackgroundImage:  sql.NullString{String: c.FormValue("background_image"), Valid: c.FormValue("background_image") != ""},     // Optional hero background image URL
		IsActive:         isActive,
		DisplayOrder:     displayOrder, // Controls carousel order
	})
	if err != nil {
		h.logger.Error("failed to create hero", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the creation activity with hero headline
	logActivity(c, "created", "hero", 0, c.FormValue("headline"), "Created Hero '%s'", c.FormValue("headline"))

	// Redirect to the heroes list page
	return c.Redirect(http.StatusSeeOther, "/admin/homepage/heroes")
}

// HeroEdit displays the form for editing an existing homepage hero.
// HTTP Method: GET
// Route: /admin/homepage/heroes/:id/edit
// Template: admin/pages/homepage_hero_form.html (full page)
// HTMX: Not used - returns full page render
//
// Query params: saved=1 (shows success message after update)
func (h *HomepageHandler) HeroEdit(c echo.Context) error {
	// Parse hero ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch the existing hero from database
	item, err := h.queries.GetHero(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to get hero", "error", err)
		return echo.NewHTTPError(http.StatusNotFound)
	}

	// Check for "saved" query parameter to show success message
	saved := c.QueryParam("saved") == "1"

	// Render the form template with existing hero data
	return c.Render(http.StatusOK, "admin/pages/homepage_hero_form.html", map[string]interface{}{
		"Title": "Edit Hero",
		"Item":  item,
		"Saved": saved, // Template shows success message if true
	})
}

// HeroUpdate processes homepage hero update form submissions.
// HTTP Method: POST
// Route: /admin/homepage/heroes/:id
// Template: None - redirects to GET /admin/homepage/heroes/:id/edit?saved=1
// HTMX: Not used - standard form submission with redirect
//
// After successful update, redirects back to the edit form with saved=1 query param
// to show a success message while keeping the user on the edit page.
func (h *HomepageHandler) HeroUpdate(c echo.Context) error {
	// Parse hero ID and form values
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	displayOrder, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1
	}

	// Update the existing hero record with form data
	err := h.queries.UpdateHero(c.Request().Context(), sqlc.UpdateHeroParams{
		ID:               id,
		Headline:         c.FormValue("headline"),
		Subheadline:      c.FormValue("subheadline"),
		BadgeText:        sql.NullString{String: c.FormValue("badge_text"), Valid: c.FormValue("badge_text") != ""},
		PrimaryCtaText:   c.FormValue("primary_cta_text"),
		PrimaryCtaUrl:    c.FormValue("primary_cta_url"),
		SecondaryCtaText: sql.NullString{String: c.FormValue("secondary_cta_text"), Valid: c.FormValue("secondary_cta_text") != ""},
		SecondaryCtaUrl:  sql.NullString{String: c.FormValue("secondary_cta_url"), Valid: c.FormValue("secondary_cta_url") != ""},
		BackgroundImage:  sql.NullString{String: c.FormValue("background_image"), Valid: c.FormValue("background_image") != ""},
		IsActive:         isActive,
		DisplayOrder:     displayOrder,
	})
	if err != nil {
		h.logger.Error("failed to update hero", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the update activity
	logActivity(c, "updated", "hero", id, c.FormValue("headline"), "Updated Hero '%s'", c.FormValue("headline"))

	// Redirect back to edit form with saved=1 to show success message
	return c.Redirect(http.StatusSeeOther, fmt.Sprintf("/admin/homepage/heroes/%d/edit?saved=1", id))
}

// HeroDelete handles deletion of a homepage hero.
// HTTP Method: DELETE
// Route: /admin/homepage/heroes/:id
// Template: None - returns HTTP 200 with no content (HTMX delete pattern)
// HTMX: Used - returns empty response, HTMX removes element from DOM
func (h *HomepageHandler) HeroDelete(c echo.Context) error {
	// Parse hero ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Delete the hero from database
	err := h.queries.DeleteHero(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to delete hero", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the deletion activity
	logActivity(c, "deleted", "hero", id, "", "Deleted Hero #%d", id)

	// Return 200 OK with no content - HTMX will handle DOM removal
	return c.NoContent(http.StatusOK)
}

// ==================== STATS ====================
// Homepage stats are numeric highlights displayed on the homepage (e.g., "500+ Projects").
// Each stat includes a value (e.g., "500+"), label (e.g., "Projects Completed"),
// is_active flag, and display order.

// StatsList displays all homepage stats in a list view.
// HTTP Method: GET
// Route: /admin/homepage/stats
// Template: admin/pages/homepage_stats_list.html (full page)
// HTMX: Not used - returns full page render
func (h *HomepageHandler) StatsList(c echo.Context) error {
	// Fetch all stats from database, ordered by display_order
	items, err := h.queries.ListAllStats(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list stats", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	return c.Render(http.StatusOK, "admin/pages/homepage_stats_list.html", map[string]interface{}{
		"Title": "Homepage Stats",
		"Items": items,
	})
}

// StatNew displays the form for creating a new homepage stat.
// Route pattern follows: GET /admin/homepage/stats/new
func (h *HomepageHandler) StatNew(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/homepage_stat_form.html", map[string]interface{}{
		"Title": "New Stat",
		"Item":  sqlc.HomepageStat{},
	})
}

// StatCreate processes new stat form submissions.
// Route pattern follows: POST /admin/homepage/stats
func (h *HomepageHandler) StatCreate(c echo.Context) error {
	displayOrder, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1
	}

	// Create new stat with value (e.g., "500+") and label (e.g., "Projects")
	_, err := h.queries.CreateStat(c.Request().Context(), sqlc.CreateStatParams{
		StatValue:    c.FormValue("stat_value"), // Numeric display (e.g., "500+", "98%")
		StatLabel:    c.FormValue("stat_label"), // Description (e.g., "Projects Completed")
		DisplayOrder: displayOrder,
		IsActive:     isActive,
	})
	if err != nil {
		h.logger.Error("failed to create stat", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "created", "stat", 0, c.FormValue("stat_label"), "Created Stat '%s'", c.FormValue("stat_label"))
	return c.Redirect(http.StatusSeeOther, "/admin/homepage/stats")
}

// StatEdit displays the form for editing an existing stat.
// Route pattern follows: GET /admin/homepage/stats/:id/edit?saved=1
func (h *HomepageHandler) StatEdit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	item, err := h.queries.GetStat(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to get stat", "error", err)
		return echo.NewHTTPError(http.StatusNotFound)
	}
	saved := c.QueryParam("saved") == "1"
	return c.Render(http.StatusOK, "admin/pages/homepage_stat_form.html", map[string]interface{}{
		"Title": "Edit Stat",
		"Item":  item,
		"Saved": saved,
	})
}

// StatUpdate processes stat update form submissions.
// Route pattern follows: POST /admin/homepage/stats/:id
// Redirects to edit form with saved=1 after successful update.
func (h *HomepageHandler) StatUpdate(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	displayOrder, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1
	}
	err := h.queries.UpdateStat(c.Request().Context(), sqlc.UpdateStatParams{
		ID:           id,
		StatValue:    c.FormValue("stat_value"),
		StatLabel:    c.FormValue("stat_label"),
		DisplayOrder: displayOrder,
		IsActive:     isActive,
	})
	if err != nil {
		h.logger.Error("failed to update stat", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "updated", "stat", id, c.FormValue("stat_label"), "Updated Stat '%s'", c.FormValue("stat_label"))
	return c.Redirect(http.StatusSeeOther, fmt.Sprintf("/admin/homepage/stats/%d/edit?saved=1", id))
}

// StatDelete handles deletion of a stat.
// Route pattern follows: DELETE /admin/homepage/stats/:id
// HTMX delete pattern - returns 200 OK with no content.
func (h *HomepageHandler) StatDelete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	err := h.queries.DeleteStat(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to delete stat", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "deleted", "stat", id, "", "Deleted Stat #%d", id)
	return c.NoContent(http.StatusOK)
}

// ==================== TESTIMONIALS ====================
// Homepage testimonials are customer/client reviews displayed on the homepage.
// Each testimonial includes quote text, author name, optional author title/company/image,
// star rating (1-5), is_active flag, and display order.
//
// All testimonial handlers follow the same CRUD pattern as heroes and stats:
// - List: GET /admin/homepage/testimonials - full page list view
// - New: GET /admin/homepage/testimonials/new - empty form
// - Create: POST /admin/homepage/testimonials - creates and redirects to list
// - Edit: GET /admin/homepage/testimonials/:id/edit - form with saved query param
// - Update: POST /admin/homepage/testimonials/:id - updates and redirects to edit?saved=1
// - Delete: DELETE /admin/homepage/testimonials/:id - HTMX delete with no content response

// TestimonialsList displays all homepage testimonials in a list view.
// HTTP Method: GET
// Route: /admin/homepage/testimonials
// Template: admin/pages/homepage_testimonials_list.html (full page)
// HTMX: Not used - returns full page render
func (h *HomepageHandler) TestimonialsList(c echo.Context) error {
	items, err := h.queries.ListAllTestimonialsHomepage(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list testimonials", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	return c.Render(http.StatusOK, "admin/pages/homepage_testimonials_list.html", map[string]interface{}{
		"Title": "Homepage Testimonials",
		"Items": items,
	})
}

func (h *HomepageHandler) TestimonialNew(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/homepage_testimonial_form.html", map[string]interface{}{
		"Title": "New Testimonial",
		"Item":  sqlc.HomepageTestimonial{},
	})
}

func (h *HomepageHandler) TestimonialCreate(c echo.Context) error {
	displayOrder, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)
	rating, _ := strconv.ParseInt(c.FormValue("rating"), 10, 64)
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1
	}
	_, err := h.queries.CreateTestimonialHomepage(c.Request().Context(), sqlc.CreateTestimonialHomepageParams{
		Quote:         c.FormValue("quote"),
		AuthorName:    c.FormValue("author_name"),
		AuthorTitle:   sql.NullString{String: c.FormValue("author_title"), Valid: c.FormValue("author_title") != ""},
		AuthorCompany: sql.NullString{String: c.FormValue("author_company"), Valid: c.FormValue("author_company") != ""},
		AuthorImage:   sql.NullString{String: c.FormValue("author_image"), Valid: c.FormValue("author_image") != ""},
		Rating:        rating,
		DisplayOrder:  displayOrder,
		IsActive:      isActive,
	})
	if err != nil {
		h.logger.Error("failed to create testimonial", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "created", "testimonial", 0, c.FormValue("author_name"), "Created Testimonial by '%s'", c.FormValue("author_name"))
	return c.Redirect(http.StatusSeeOther, "/admin/homepage/testimonials")
}

func (h *HomepageHandler) TestimonialEdit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	item, err := h.queries.GetTestimonialHomepage(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to get testimonial", "error", err)
		return echo.NewHTTPError(http.StatusNotFound)
	}
	saved := c.QueryParam("saved") == "1"
	return c.Render(http.StatusOK, "admin/pages/homepage_testimonial_form.html", map[string]interface{}{
		"Title": "Edit Testimonial",
		"Item":  item,
		"Saved": saved,
	})
}

func (h *HomepageHandler) TestimonialUpdate(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	displayOrder, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)
	rating, _ := strconv.ParseInt(c.FormValue("rating"), 10, 64)
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1
	}
	err := h.queries.UpdateTestimonialHomepage(c.Request().Context(), sqlc.UpdateTestimonialHomepageParams{
		ID:            id,
		Quote:         c.FormValue("quote"),
		AuthorName:    c.FormValue("author_name"),
		AuthorTitle:   sql.NullString{String: c.FormValue("author_title"), Valid: c.FormValue("author_title") != ""},
		AuthorCompany: sql.NullString{String: c.FormValue("author_company"), Valid: c.FormValue("author_company") != ""},
		AuthorImage:   sql.NullString{String: c.FormValue("author_image"), Valid: c.FormValue("author_image") != ""},
		Rating:        rating,
		DisplayOrder:  displayOrder,
		IsActive:      isActive,
	})
	if err != nil {
		h.logger.Error("failed to update testimonial", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "updated", "testimonial", id, c.FormValue("author_name"), "Updated Testimonial by '%s'", c.FormValue("author_name"))
	return c.Redirect(http.StatusSeeOther, fmt.Sprintf("/admin/homepage/testimonials/%d/edit?saved=1", id))
}

func (h *HomepageHandler) TestimonialDelete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	err := h.queries.DeleteTestimonialHomepage(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to delete testimonial", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "deleted", "testimonial", id, "", "Deleted Testimonial #%d", id)
	return c.NoContent(http.StatusOK)
}

// ==================== CTA ====================
// Homepage CTAs (Call-to-Action) are promotional banners displayed on the homepage.
// Each CTA includes headline, optional description, primary CTA button, optional secondary CTA,
// optional background style/class, and is_active flag.
//
// All CTA handlers follow the same CRUD pattern as other homepage sections:
// - List: GET /admin/homepage/cta - full page list view
// - New: GET /admin/homepage/cta/new - empty form
// - Create: POST /admin/homepage/cta - creates and redirects to list
// - Edit: GET /admin/homepage/cta/:id/edit - form with saved query param
// - Update: POST /admin/homepage/cta/:id - updates and redirects to edit?saved=1
// - Delete: DELETE /admin/homepage/cta/:id - HTMX delete with no content response

// CTAList displays all homepage CTAs in a list view.
// HTTP Method: GET
// Route: /admin/homepage/cta
// Template: admin/pages/homepage_cta_list.html (full page)
// HTMX: Not used - returns full page render
func (h *HomepageHandler) CTAList(c echo.Context) error {
	items, err := h.queries.ListAllCTAs(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list CTAs", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	return c.Render(http.StatusOK, "admin/pages/homepage_cta_list.html", map[string]interface{}{
		"Title": "Homepage CTAs",
		"Items": items,
	})
}

func (h *HomepageHandler) CTANew(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/homepage_cta_form.html", map[string]interface{}{
		"Title": "New CTA",
		"Item":  sqlc.HomepageCtum{},
	})
}

func (h *HomepageHandler) CTACreate(c echo.Context) error {
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1
	}
	_, err := h.queries.CreateCTA(c.Request().Context(), sqlc.CreateCTAParams{
		Headline:         c.FormValue("headline"),
		Description:      sql.NullString{String: c.FormValue("description"), Valid: c.FormValue("description") != ""},
		PrimaryCtaText:   c.FormValue("primary_cta_text"),
		PrimaryCtaUrl:    c.FormValue("primary_cta_url"),
		SecondaryCtaText: sql.NullString{String: c.FormValue("secondary_cta_text"), Valid: c.FormValue("secondary_cta_text") != ""},
		SecondaryCtaUrl:  sql.NullString{String: c.FormValue("secondary_cta_url"), Valid: c.FormValue("secondary_cta_url") != ""},
		BackgroundStyle:  sql.NullString{String: c.FormValue("background_style"), Valid: c.FormValue("background_style") != ""},
		IsActive:         isActive,
	})
	if err != nil {
		h.logger.Error("failed to create CTA", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "created", "cta", 0, c.FormValue("headline"), "Created CTA '%s'", c.FormValue("headline"))
	return c.Redirect(http.StatusSeeOther, "/admin/homepage/cta")
}

func (h *HomepageHandler) CTAEdit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	item, err := h.queries.GetCTA(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to get CTA", "error", err)
		return echo.NewHTTPError(http.StatusNotFound)
	}
	saved := c.QueryParam("saved") == "1"
	return c.Render(http.StatusOK, "admin/pages/homepage_cta_form.html", map[string]interface{}{
		"Title": "Edit CTA",
		"Item":  item,
		"Saved": saved,
	})
}

func (h *HomepageHandler) CTAUpdate(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	var isActive int64
	if c.FormValue("is_active") == "on" {
		isActive = 1
	}
	err := h.queries.UpdateCTA(c.Request().Context(), sqlc.UpdateCTAParams{
		ID:               id,
		Headline:         c.FormValue("headline"),
		Description:      sql.NullString{String: c.FormValue("description"), Valid: c.FormValue("description") != ""},
		PrimaryCtaText:   c.FormValue("primary_cta_text"),
		PrimaryCtaUrl:    c.FormValue("primary_cta_url"),
		SecondaryCtaText: sql.NullString{String: c.FormValue("secondary_cta_text"), Valid: c.FormValue("secondary_cta_text") != ""},
		SecondaryCtaUrl:  sql.NullString{String: c.FormValue("secondary_cta_url"), Valid: c.FormValue("secondary_cta_url") != ""},
		BackgroundStyle:  sql.NullString{String: c.FormValue("background_style"), Valid: c.FormValue("background_style") != ""},
		IsActive:         isActive,
	})
	if err != nil {
		h.logger.Error("failed to update CTA", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "updated", "cta", id, c.FormValue("headline"), "Updated CTA '%s'", c.FormValue("headline"))
	return c.Redirect(http.StatusSeeOther, fmt.Sprintf("/admin/homepage/cta/%d/edit?saved=1", id))
}

func (h *HomepageHandler) CTADelete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	err := h.queries.DeleteCTA(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to delete CTA", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "deleted", "cta", id, "", "Deleted CTA #%d", id)
	return c.NoContent(http.StatusOK)
}

// ==================== SETTINGS ====================
// Homepage settings control global display options for the homepage.
// Settings include visibility toggles for each section (heroes/stats/testimonials/CTA),
// maximum item counts for each section, and hero carousel autoplay configuration.

// Settings displays the homepage settings form.
// HTTP Method: GET
// Route: /admin/homepage/settings
// Template: admin/pages/homepage_settings.html (full page)
// HTMX: Not used - returns full page render
//
// Query params: saved=1 (shows success message after update)
// This is a singleton record - only one settings record exists in the database.
func (h *HomepageHandler) Settings(c echo.Context) error {
	// Fetch the single homepage settings record from database
	settings, err := h.queries.GetSettings(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to load settings", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Check for "saved" query parameter to show success message
	saved := c.QueryParam("saved") == "1"

	// Render the settings form template
	return c.Render(http.StatusOK, "admin/pages/homepage_settings.html", map[string]interface{}{
		"Title":    "Homepage Settings",
		"Settings": settings,
		"Saved":    saved, // Template shows success message if true
	})
}

// UpdateSettings processes homepage settings form submissions.
// HTTP Method: POST
// Route: /admin/homepage/settings
// Template: None - redirects to GET /admin/homepage/settings?saved=1
// HTMX: Not used - standard form submission with redirect
//
// This handler updates the homepage settings singleton record, controlling:
// - Section visibility: show/hide heroes, stats, testimonials, CTA
// - Item limits: max number of items to display for each section
// - Hero carousel: autoplay enabled and interval in seconds
func (h *HomepageHandler) UpdateSettings(c echo.Context) error {
	// Helper function to parse integer fields with default fallback
	// Handles empty strings and parse errors gracefully
	parseIntField := func(field string, defaultVal int64) int64 {
		v := strings.TrimSpace(c.FormValue(field))
		if v == "" {
			return defaultVal
		}
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return defaultVal
		}
		return n
	}

	// Helper function to convert checkbox values to integer booleans
	boolToInt := func(field string) int64 {
		if c.FormValue(field) == "on" {
			return 1
		}
		return 0
	}

	// Update the homepage settings record with form values
	err := h.queries.UpdateHomepageSettings(c.Request().Context(), sqlc.UpdateHomepageSettingsParams{
		HomepageShowHeroes:       boolToInt("homepage_show_heroes"),       // Toggle heroes section visibility
		HomepageShowStats:        boolToInt("homepage_show_stats"),        // Toggle stats section visibility
		HomepageShowTestimonials: boolToInt("homepage_show_testimonials"), // Toggle testimonials section visibility
		HomepageShowCta:          boolToInt("homepage_show_cta"),          // Toggle CTA section visibility
		HomepageMaxHeroes:        parseIntField("homepage_max_heroes", 5), // Max heroes to display (default: 5)
		HomepageMaxStats:         parseIntField("homepage_max_stats", 6),  // Max stats to display (default: 6)
		HomepageMaxTestimonials:  parseIntField("homepage_max_testimonials", 3), // Max testimonials (default: 3)
		HomepageHeroAutoplay:     boolToInt("homepage_hero_autoplay"),             // Enable hero carousel autoplay
		HomepageHeroInterval:     parseIntField("homepage_hero_interval", 5),      // Autoplay interval in seconds (default: 5)
	})
	if err != nil {
		h.logger.Error("failed to update homepage settings", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log the settings update activity
	logActivity(c, "updated", "homepage_settings", 0, "", "Updated Homepage Settings")

	// Redirect back to settings page with saved=1 to show success message
	return c.Redirect(http.StatusSeeOther, "/admin/homepage/settings?saved=1")
}
