// Package admin provides HTTP handlers for the admin panel's industry management.
// Industries represent business sectors/verticals served by the platform (e.g., "Healthcare", "Finance").
package admin

import (
	// Standard library imports for logging, HTTP handling, and type conversions
	"log/slog"  // Structured logging for error and info messages
	"net/http"  // HTTP status codes and request/response handling
	"strconv"   // String to integer conversions for form values and URL parameters

	// Third-party imports
	"github.com/labstack/echo/v4" // Echo web framework for HTTP routing and context

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // sqlc-generated database query methods
)

// IndustriesHandler manages HTTP requests for industry CRUD operations.
// Industries are business sectors/verticals that can be associated with content,
// partners, or other entities (e.g., "Healthcare", "Finance", "Manufacturing").
// It depends on database queries and structured logging.
type IndustriesHandler struct {
	queries *sqlc.Queries  // Database query interface generated by sqlc
	logger  *slog.Logger   // Structured logger for error tracking and debugging
}

// NewIndustriesHandler constructs a new IndustriesHandler with required dependencies.
// This constructor is called during application initialization to wire up the handler
// with database access and logging capabilities.
func NewIndustriesHandler(queries *sqlc.Queries, logger *slog.Logger) *IndustriesHandler {
	return &IndustriesHandler{queries: queries, logger: logger}
}

// List displays the industries list page.
//
// HTTP Method: GET
// Route: /admin/industries
// Template: admin/pages/industries_list.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Business Logic:
//   - Retrieves all industries from the database ordered by sort_order
//   - No filtering or pagination implemented (industries are typically a small dataset)
//   - Industries are displayed in order to allow admin to manage business sectors
func (h *IndustriesHandler) List(c echo.Context) error {
	// Fetch all industries from the database (ordered by sort_order)
	items, err := h.queries.ListIndustries(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list industries", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the full industries list page
	return c.Render(http.StatusOK, "admin/pages/industries_list.html", map[string]interface{}{
		"Title": "Industries",
		"Items": items,  // List of all industries
	})
}

// New renders the form for creating a new industry.
//
// HTTP Method: GET
// Route: /admin/industries/new
// Template: admin/pages/industries_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Business Logic:
//   - Sets Item to nil to indicate form is in "create" mode
//   - FormAction points to POST /admin/industries for form submission
//   - No additional data needed as industry fields are simple (name, slug, icon, description, sort_order)
func (h *IndustriesHandler) New(c echo.Context) error {
	// Render the industry form in "create" mode
	return c.Render(http.StatusOK, "admin/pages/industries_form.html", map[string]interface{}{
		"Title":      "New Industry",
		"FormAction": "/admin/industries",  // POST endpoint for creating new industry
		"Item":       nil,                  // nil signals "create" mode to the template
	})
}

// Create processes the form submission to create a new industry.
//
// HTTP Method: POST
// Route: /admin/industries
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// Form Fields:
//   - name (required): Industry display name (e.g., "Healthcare", "Finance")
//   - icon (required): Icon class or identifier for visual representation
//   - description (required): Industry description text
//   - sort_order (required): Numeric order for displaying industries
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for sort_order)
//   - Auto-generates slug from name using makeSlug helper function
//   - Slug is used for URL-friendly industry identification
//   - Logs admin activity for audit trail
//   - Redirects to industries list on success (303 See Other)
func (h *IndustriesHandler) Create(c echo.Context) error {
	// Convert sort_order from string to int64
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)

	// Create new industry with form data
	_, err := h.queries.CreateIndustry(c.Request().Context(), sqlc.CreateIndustryParams{
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),  // Auto-generate URL-friendly slug from name
		Icon:        c.FormValue("icon"),
		Description: c.FormValue("description"),
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to create industry", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log admin activity for audit trail (0 = no ID yet for new record)
	logActivity(c, "created", "industry", 0, c.FormValue("name"), "Created Industry '%s'", c.FormValue("name"))

	// Redirect to industries list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/industries")
}

// Edit renders the form for editing an existing industry.
//
// HTTP Method: GET
// Route: /admin/industries/:id/edit
// Template: admin/pages/industries_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// URL Parameters:
//   - id: Industry ID to edit
//
// Business Logic:
//   - Fetches the industry by ID from the database
//   - Returns 404 with message if industry not found
//   - Sets Item to the existing industry data for form pre-population
//   - FormAction points to POST /admin/industries/:id for form submission
func (h *IndustriesHandler) Edit(c echo.Context) error {
	// Parse industry ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch existing industry data
	item, err := h.queries.GetIndustry(c.Request().Context(), id)
	if err != nil {
		// Return 404 with descriptive message if industry doesn't exist
		return echo.NewHTTPError(http.StatusNotFound, "Industry not found")
	}

	// Render the same form template as New, but with existing data
	return c.Render(http.StatusOK, "admin/pages/industries_form.html", map[string]interface{}{
		"Title":      "Edit Industry",
		"FormAction": "/admin/industries/" + c.Param("id"),  // POST endpoint for updating
		"Item":       item,                                  // Existing industry data for form pre-fill
	})
}

// Update processes the form submission to update an existing industry.
//
// HTTP Method: POST
// Route: /admin/industries/:id
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// URL Parameters:
//   - id: Industry ID to update
//
// Form Fields:
//   - name (required): Industry display name (e.g., "Healthcare", "Finance")
//   - icon (required): Icon class or identifier for visual representation
//   - description (required): Industry description text
//   - sort_order (required): Numeric order for displaying industries
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for sort_order)
//   - Auto-generates slug from name using makeSlug helper function (slug updates with name)
//   - Logs admin activity for audit trail
//   - Redirects to industries list on success (303 See Other)
func (h *IndustriesHandler) Update(c echo.Context) error {
	// Parse industry ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Convert sort_order from string to int64
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)

	// Update industry with form data
	_, err := h.queries.UpdateIndustry(c.Request().Context(), sqlc.UpdateIndustryParams{
		ID:          id,
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),  // Regenerate slug from updated name
		Icon:        c.FormValue("icon"),
		Description: c.FormValue("description"),
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to update industry", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log admin activity for audit trail
	logActivity(c, "updated", "industry", id, c.FormValue("name"), "Updated Industry '%s'", c.FormValue("name"))

	// Redirect to industries list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/industries")
}

// Delete removes an industry from the database.
//
// HTTP Method: DELETE
// Route: /admin/industries/:id
// Template: None (returns 200 OK with no content)
// HTMX: Used - returns HTTP 200 with no body for HTMX to handle DOM removal
//
// URL Parameters:
//   - id: Industry ID to delete
//
// Business Logic:
//   - Performs hard delete from the database (no soft delete)
//   - May fail if industry has associated content or relationships (foreign key constraints)
//   - Logs admin activity for audit trail
//   - Returns 200 OK with no content for HTMX delete handlers
func (h *IndustriesHandler) Delete(c echo.Context) error {
	// Parse industry ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Delete industry from database (hard delete)
	// This will fail if any content references this industry due to foreign key constraints
	if err := h.queries.DeleteIndustry(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete industry", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log admin activity for audit trail
	logActivity(c, "deleted", "industry", id, "", "Deleted Industry #%d", id)

	// Return 200 OK with no content for HTMX to process
	return c.NoContent(http.StatusOK)
}
