// Package admin provides HTTP handlers for the admin panel's page sections management functionality.
// This file handles the editing of predefined page sections (hero sections, content blocks, CTAs)
// that are used across different pages of the website. Each page section is identified by a unique
// PageKey and can contain headings, descriptions, buttons, and other content elements.
package admin

import (
	// Standard library imports
	"log/slog"  // Structured logging for error and debug output
	"net/http"  // HTTP status codes and request/response handling
	"strconv"   // String to integer conversion for parsing section IDs

	// Third-party framework
	"github.com/labstack/echo/v4" // Echo web framework for routing and context handling

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // Database query layer generated by sqlc
)

// PageSectionsHandler manages editable page sections for website pages.
// It provides endpoints to view and update predefined content sections such as:
//   - Hero sections (main banner content)
//   - Feature sections
//   - Call-to-action blocks
//   - Content blocks with headings, descriptions, and buttons
//
// Sections are identified by PageKey (e.g., "home_hero", "about_team") and can be
// activated/deactivated without deletion.
type PageSectionsHandler struct {
	queries *sqlc.Queries // Database query interface for page sections operations
	logger  *slog.Logger  // Structured logger for error tracking
}

// NewPageSectionsHandler creates and initializes a new PageSectionsHandler instance.
// It requires database queries interface and a logger for operation tracking.
//
// Parameters:
//   - queries: Database query layer for executing page sections operations
//   - logger: Structured logger for error and activity logging
//
// Returns a fully initialized PageSectionsHandler ready to handle HTTP requests.
func NewPageSectionsHandler(queries *sqlc.Queries, logger *slog.Logger) *PageSectionsHandler {
	return &PageSectionsHandler{queries: queries, logger: logger}
}

// List renders the page sections overview page showing all sections grouped by page.
//
// HTTP Method: GET
// Route: /admin/page-sections
// HTMX: Returns full page (not a fragment)
// Template: admin/pages/page_sections_list.html
//
// This handler retrieves all page sections from the database and organizes them by
// page identifier (PageKey) for easier navigation. Each page can have multiple sections
// (e.g., "Products" page might have: hero section, features section, CTA section).
//
// The grouping makes it easy for users to see all editable sections for each page
// at a glance and navigate to specific section editors.
//
// Returns:
//   - 200 OK with rendered HTML list on success
//   - 500 Internal Server Error if database query fails
func (h *PageSectionsHandler) List(c echo.Context) error {
	// Retrieve all page sections from database
	sections, err := h.queries.ListAllPageSections(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to load page sections", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Group sections by PageKey (e.g., "home", "products", "about")
	// This organizes sections by the page they belong to for clearer UI
	grouped := make(map[string][]sqlc.PageSection)
	for _, section := range sections {
		grouped[section.PageKey] = append(grouped[section.PageKey], section)
	}
	// Result: {"home": [hero_section, features_section], "about": [team_section], ...}

	// Render the page sections list with grouped data
	return c.Render(http.StatusOK, "admin/pages/page_sections_list.html", map[string]interface{}{
		"Title":           "Page Sections",
		"GroupedSections": grouped, // Map of page key to sections array
	})
}

// Edit renders the page section editor form for a specific section.
//
// HTTP Method: GET
// Route: /admin/page-sections/:id/edit
// HTMX: Returns full page (not a fragment)
// Template: admin/pages/page_sections_form.html
//
// This handler displays an editable form for a specific page section. The form includes
// fields for all section content:
//   - Heading: Main section title
//   - Subheading: Secondary title or tagline
//   - Description: Rich text content area
//   - Label: Section identifier or category label
//   - Primary button (text and URL)
//   - Secondary button (text and URL)
//   - Active status toggle (show/hide section)
//
// URL Parameters:
//   - id: Page section ID to edit
//
// Query Parameters:
//   - saved: Set to "1" to display a success message after form submission
//
// Returns:
//   - 200 OK with rendered HTML form on success
//   - 400 Bad Request if ID is invalid
//   - 500 Internal Server Error if database query fails
func (h *PageSectionsHandler) Edit(c echo.Context) error {
	// Parse section ID from URL parameter
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, "Invalid ID")
	}

	// Retrieve section record from database
	section, err := h.queries.GetPageSectionByID(c.Request().Context(), id)
	if err != nil {
		h.logger.Error("failed to load page section", "error", err, "id", id)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Check if this is a redirect after successful save operation
	saved := c.QueryParam("saved") == "1"

	// Render the section editor form with current section data
	return c.Render(http.StatusOK, "admin/pages/page_sections_form.html", map[string]interface{}{
		"Title":   "Edit Page Section",
		"Section": section, // Current section data for form population
		"Saved":   saved,   // Success flag to show confirmation message
	})
}

// Update processes the page section editor form submission and saves changes.
//
// HTTP Method: POST
// Route: /admin/page-sections/:id/update
// HTMX: Not used for this endpoint (standard form POST)
// Template: None (redirects to Edit handler)
//
// This handler updates all editable fields of a page section based on form data.
// It handles text content, button configurations, and the active status toggle.
//
// URL Parameters:
//   - id: Page section ID to update
//
// Form Fields:
//   - heading: Main section title
//   - subheading: Secondary title or tagline
//   - description: Rich text content (may contain HTML)
//   - label: Section identifier or category label
//   - primary_button_text: Text for primary CTA button
//   - primary_button_url: URL for primary CTA button
//   - secondary_button_text: Text for secondary CTA button
//   - secondary_button_url: URL for secondary CTA button
//   - is_active: Checkbox - whether section is visible on the website
//
// Note: The checkbox is_active converts from "on" string to boolean.
// After successful update, redirects back to the edit form with saved=1.
//
// Returns:
//   - 303 See Other redirect to /admin/page-sections/:id/edit?saved=1 on success
//   - 400 Bad Request if ID is invalid
//   - 500 Internal Server Error if database update fails
func (h *PageSectionsHandler) Update(c echo.Context) error {
	// Parse section ID from URL parameter
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, "Invalid ID")
	}

	// Update page section with all form values
	// Checkbox field: value "on" indicates checked, missing/empty indicates unchecked
	err = h.queries.UpdatePageSection(c.Request().Context(), sqlc.UpdatePageSectionParams{
		Heading:             c.FormValue("heading"),              // Main section title
		Subheading:          c.FormValue("subheading"),           // Secondary title/tagline
		Description:         c.FormValue("description"),          // Rich text content area
		Label:               c.FormValue("label"),                // Section identifier/category
		PrimaryButtonText:   c.FormValue("primary_button_text"),  // Primary CTA button text
		PrimaryButtonUrl:    c.FormValue("primary_button_url"),   // Primary CTA button URL
		SecondaryButtonText: c.FormValue("secondary_button_text"), // Secondary CTA button text
		SecondaryButtonUrl:  c.FormValue("secondary_button_url"),  // Secondary CTA button URL
		IsActive:            c.FormValue("is_active") == "on",    // Visibility toggle (checkbox to boolean)
		ID:                  id,                                  // Section ID to update
	})

	if err != nil {
		h.logger.Error("failed to update page section", "error", err, "id", id)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Redirect back to the edit form with saved parameter to show success message
	return c.Redirect(http.StatusSeeOther, "/admin/page-sections/"+c.Param("id")+"/edit?saved=1")
}
