// Package admin provides HTTP handlers for the admin panel's partner tier management.
// Partner tiers are categories/levels for organizing partners (e.g., "Platinum", "Gold", "Silver").
package admin

import (
	// Standard library imports for logging, HTTP handling, and type conversions
	"log/slog"  // Structured logging for error and info messages
	"net/http"  // HTTP status codes and request/response handling
	"strconv"   // String to integer conversions for form values and URL parameters

	// Third-party imports
	"github.com/labstack/echo/v4" // Echo web framework for HTTP routing and context

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // sqlc-generated database query methods
)

// PartnerTiersHandler manages HTTP requests for partner tier CRUD operations.
// Partner tiers are used to categorize partners into levels/categories (e.g., "Platinum", "Gold").
// It depends on database queries and structured logging.
type PartnerTiersHandler struct {
	queries *sqlc.Queries  // Database query interface generated by sqlc
	logger  *slog.Logger   // Structured logger for error tracking and debugging
}

// NewPartnerTiersHandler constructs a new PartnerTiersHandler with required dependencies.
// This constructor is called during application initialization to wire up the handler
// with database access and logging capabilities.
func NewPartnerTiersHandler(queries *sqlc.Queries, logger *slog.Logger) *PartnerTiersHandler {
	return &PartnerTiersHandler{queries: queries, logger: logger}
}

// List displays the partner tiers list page.
//
// HTTP Method: GET
// Route: /admin/partner-tiers
// Template: admin/pages/partner_tiers_list.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Business Logic:
//   - Retrieves all partner tiers from the database ordered by sort_order
//   - No filtering or pagination implemented (tiers are typically a small dataset)
//   - Tiers are displayed in order to allow admin to manage partner categories
func (h *PartnerTiersHandler) List(c echo.Context) error {
	// Fetch all partner tiers from the database (ordered by sort_order)
	items, err := h.queries.ListPartnerTiers(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list partner tiers", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the full partner tiers list page
	return c.Render(http.StatusOK, "admin/pages/partner_tiers_list.html", map[string]interface{}{
		"Title": "Partner Tiers",
		"Items": items,  // List of all partner tiers
	})
}

// New renders the form for creating a new partner tier.
//
// HTTP Method: GET
// Route: /admin/partner-tiers/new
// Template: admin/pages/partner_tiers_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Business Logic:
//   - Sets Item to nil to indicate form is in "create" mode
//   - FormAction points to POST /admin/partner-tiers for form submission
//   - No additional data needed as tier fields are simple (name, slug, description, sort_order)
func (h *PartnerTiersHandler) New(c echo.Context) error {
	// Render the partner tier form in "create" mode
	return c.Render(http.StatusOK, "admin/pages/partner_tiers_form.html", map[string]interface{}{
		"Title":      "New Partner Tier",
		"FormAction": "/admin/partner-tiers",  // POST endpoint for creating new tier
		"Item":       nil,                     // nil signals "create" mode to the template
	})
}

// Create processes the form submission to create a new partner tier.
//
// HTTP Method: POST
// Route: /admin/partner-tiers
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// Form Fields:
//   - name (required): Tier display name (e.g., "Platinum", "Gold")
//   - description (required): Tier description text
//   - sort_order (required): Numeric order for displaying tiers
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for sort_order)
//   - Auto-generates slug from name using makeSlug helper function
//   - Slug is used for URL-friendly tier identification
//   - Logs admin activity for audit trail
//   - Redirects to partner tiers list on success (303 See Other)
func (h *PartnerTiersHandler) Create(c echo.Context) error {
	// Convert sort_order from string to int64
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)

	// Create new partner tier with form data
	_, err := h.queries.CreatePartnerTier(c.Request().Context(), sqlc.CreatePartnerTierParams{
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),  // Auto-generate URL-friendly slug from name
		Description: c.FormValue("description"),
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to create partner tier", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log admin activity for audit trail (0 = no ID yet for new record)
	logActivity(c, "created", "partner_tier", 0, c.FormValue("name"), "Created Partner Tier '%s'", c.FormValue("name"))

	// Redirect to partner tiers list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/partner-tiers")
}

// Edit renders the form for editing an existing partner tier.
//
// HTTP Method: GET
// Route: /admin/partner-tiers/:id/edit
// Template: admin/pages/partner_tiers_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// URL Parameters:
//   - id: Partner tier ID to edit
//
// Business Logic:
//   - Fetches the partner tier by ID from the database
//   - Returns 404 with message if tier not found
//   - Sets Item to the existing tier data for form pre-population
//   - FormAction points to POST /admin/partner-tiers/:id for form submission
func (h *PartnerTiersHandler) Edit(c echo.Context) error {
	// Parse partner tier ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch existing partner tier data
	item, err := h.queries.GetPartnerTier(c.Request().Context(), id)
	if err != nil {
		// Return 404 with descriptive message if tier doesn't exist
		return echo.NewHTTPError(http.StatusNotFound, "Partner tier not found")
	}

	// Render the same form template as New, but with existing data
	return c.Render(http.StatusOK, "admin/pages/partner_tiers_form.html", map[string]interface{}{
		"Title":      "Edit Partner Tier",
		"FormAction": "/admin/partner-tiers/" + c.Param("id"),  // POST endpoint for updating
		"Item":       item,                                     // Existing tier data for form pre-fill
	})
}

// Update processes the form submission to update an existing partner tier.
//
// HTTP Method: POST
// Route: /admin/partner-tiers/:id
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// URL Parameters:
//   - id: Partner tier ID to update
//
// Form Fields:
//   - name (required): Tier display name (e.g., "Platinum", "Gold")
//   - description (required): Tier description text
//   - sort_order (required): Numeric order for displaying tiers
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for sort_order)
//   - Auto-generates slug from name using makeSlug helper function (slug updates with name)
//   - Logs admin activity for audit trail
//   - Redirects to partner tiers list on success (303 See Other)
func (h *PartnerTiersHandler) Update(c echo.Context) error {
	// Parse partner tier ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Convert sort_order from string to int64
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)

	// Update partner tier with form data
	_, err := h.queries.UpdatePartnerTier(c.Request().Context(), sqlc.UpdatePartnerTierParams{
		ID:          id,
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),  // Regenerate slug from updated name
		Description: c.FormValue("description"),
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to update partner tier", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log admin activity for audit trail
	logActivity(c, "updated", "partner_tier", id, c.FormValue("name"), "Updated Partner Tier '%s'", c.FormValue("name"))

	// Redirect to partner tiers list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/partner-tiers")
}

// Delete removes a partner tier from the database.
//
// HTTP Method: DELETE
// Route: /admin/partner-tiers/:id
// Template: None (returns 200 OK with no content)
// HTMX: Used - returns HTTP 200 with no body for HTMX to handle DOM removal
//
// URL Parameters:
//   - id: Partner tier ID to delete
//
// Business Logic:
//   - Performs hard delete from the database (no soft delete)
//   - May fail if tier has associated partners (foreign key constraint)
//   - Logs admin activity for audit trail
//   - Returns 200 OK with no content for HTMX delete handlers
func (h *PartnerTiersHandler) Delete(c echo.Context) error {
	// Parse partner tier ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Delete partner tier from database (hard delete)
	// This will fail if any partners reference this tier due to foreign key constraints
	if err := h.queries.DeletePartnerTier(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete partner tier", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log admin activity for audit trail
	logActivity(c, "deleted", "partner_tier", id, "", "Deleted Partner Tier #%d", id)

	// Return 200 OK with no content for HTMX to process
	return c.NoContent(http.StatusOK)
}
