// Package admin provides HTTP handlers for the admin panel's partner management features.
// This file handles CRUD operations for partners and their associated testimonials.
package admin

import (
	// Standard library imports for database operations, logging, HTTP handling, and string manipulation
	"database/sql"   // Used for handling nullable database fields (sql.NullString)
	"log/slog"       // Structured logging for error and info messages
	"net/http"       // HTTP status codes and request/response handling
	"strconv"        // String to integer conversions for form values and URL parameters
	"strings"        // String manipulation for search filtering (ToLower, Contains, TrimSpace)

	// Third-party imports
	"github.com/labstack/echo/v4" // Echo web framework for HTTP routing and context

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc"              // sqlc-generated database query methods
	"github.com/narendhupati/bluejay-cms/internal/services"    // Cache service for invalidating partner page cache
)

// PartnersHandler manages HTTP requests for partner and testimonial operations.
// It depends on database queries, structured logging, and a cache service for
// invalidating cached partner page content when data changes.
type PartnersHandler struct {
	queries *sqlc.Queries    // Database query interface generated by sqlc
	logger  *slog.Logger     // Structured logger for error tracking and debugging
	cache   *services.Cache  // Cache service to invalidate "page:partners" entries on mutations
}

// NewPartnersHandler constructs a new PartnersHandler with required dependencies.
// This constructor is called during application initialization to wire up the handler
// with database access, logging, and caching capabilities.
func NewPartnersHandler(queries *sqlc.Queries, logger *slog.Logger, cache *services.Cache) *PartnersHandler {
	return &PartnersHandler{queries: queries, logger: logger, cache: cache}
}

// List displays the partners list page with optional filtering.
//
// HTTP Method: GET
// Route: /admin/partners
// Template: admin/pages/partners_list.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Query Parameters:
//   - search: Filter by partner name (case-insensitive substring match)
//   - tier: Filter by tier ID (exact match)
//   - status: Filter by active/inactive status ("active" or "inactive")
//
// Business Logic:
//   - Retrieves all partners from the database (no pagination)
//   - Performs client-side filtering based on query parameters
//   - Loads partner tiers for the filter dropdown
//   - Filtering is done in-memory after database fetch for simplicity
//   - Case-insensitive search matches against partner name
//   - Status filter: "active" shows only is_active=1, "inactive" shows is_active=0
func (h *PartnersHandler) List(c echo.Context) error {
	// Fetch all partners from the database (includes tier name via JOIN)
	partners, err := h.queries.ListAllPartners(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list partners", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	// Load partner tiers for the filter dropdown (errors ignored - non-critical)
	tiers, _ := h.queries.ListPartnerTiers(c.Request().Context())

	// Extract filter parameters from query string
	search := strings.TrimSpace(c.QueryParam("search"))
	tierFilter := c.QueryParam("tier")
	status := c.QueryParam("status")
	hasFilters := search != "" || tierFilter != "" || status != ""

	// Convert tier filter to int64 for comparison
	var tierFilterID int64
	if tierFilter != "" {
		tierFilterID, _ = strconv.ParseInt(tierFilter, 10, 64)
	}

	// Apply in-memory filtering based on user-selected criteria
	// Each filter is AND-combined (partner must match all active filters)
	var filtered []sqlc.ListAllPartnersRow
	for _, p := range partners {
		// Name filter: case-insensitive substring match
		if search != "" && !strings.Contains(strings.ToLower(p.Name), strings.ToLower(search)) {
			continue
		}
		// Tier filter: exact ID match
		if tierFilterID > 0 && p.TierID != tierFilterID {
			continue
		}
		// Status filter: active/inactive based on is_active flag (0 or 1)
		if status == "active" && p.IsActive == 0 {
			continue
		}
		if status == "inactive" && p.IsActive != 0 {
			continue
		}
		filtered = append(filtered, p)
	}

	// Render the full partners list page with filtered results
	return c.Render(http.StatusOK, "admin/pages/partners_list.html", map[string]interface{}{
		"Title":      "Partners",
		"Items":      filtered,        // Filtered partner list
		"Tiers":      tiers,            // Available tiers for filter dropdown
		"Search":     search,           // Preserve search term in UI
		"TierFilter": tierFilterID,     // Preserve tier filter in UI
		"Status":     status,           // Preserve status filter in UI
		"HasFilters": hasFilters,       // Flag to show "clear filters" button
	})
}

// New renders the form for creating a new partner.
//
// HTTP Method: GET
// Route: /admin/partners/new
// Template: admin/pages/partners_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Business Logic:
//   - Loads all partner tiers to populate the tier selection dropdown
//   - Sets Item to nil to indicate form is in "create" mode
//   - FormAction points to POST /admin/partners for form submission
func (h *PartnersHandler) New(c echo.Context) error {
	// Load all partner tiers for the tier dropdown (errors ignored - form will handle missing data)
	tiers, _ := h.queries.ListPartnerTiers(c.Request().Context())
	return c.Render(http.StatusOK, "admin/pages/partners_form.html", map[string]interface{}{
		"Title":      "New Partner",
		"FormAction": "/admin/partners",  // POST endpoint for creating new partner
		"Item":       nil,                 // nil signals "create" mode to the template
		"Tiers":      tiers,               // Available tiers for the dropdown
	})
}

// Create processes the form submission to create a new partner.
//
// HTTP Method: POST
// Route: /admin/partners
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// Form Fields:
//   - name (required): Partner name
//   - tier_id (required): Foreign key to partner_tiers table
//   - logo_url (optional): URL to partner logo image
//   - icon (optional): Icon class or identifier
//   - website_url (optional): Partner's website URL
//   - description (optional): Partner description text
//   - display_order (required): Numeric sort order for display
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for IDs and order)
//   - Uses sql.NullString for optional fields (Valid=true only if string is non-empty)
//   - Invalidates cached partner pages after successful creation
//   - Logs admin activity for audit trail
//   - Redirects to partner list on success (303 See Other)
func (h *PartnersHandler) Create(c echo.Context) error {
	// Convert form values to appropriate types
	tierID, _ := strconv.ParseInt(c.FormValue("tier_id"), 10, 64)
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Create new partner with form data
	_, err := h.queries.CreatePartner(c.Request().Context(), sqlc.CreatePartnerParams{
		Name:         c.FormValue("name"),
		TierID:       tierID,
		// Optional fields use sql.NullString: Valid=true only when value is non-empty
		LogoUrl:      sql.NullString{String: c.FormValue("logo_url"), Valid: c.FormValue("logo_url") != ""},
		Icon:         sql.NullString{String: c.FormValue("icon"), Valid: c.FormValue("icon") != ""},
		WebsiteUrl:   sql.NullString{String: c.FormValue("website_url"), Valid: c.FormValue("website_url") != ""},
		Description:  sql.NullString{String: c.FormValue("description"), Valid: c.FormValue("description") != ""},
		DisplayOrder: order,
	})
	if err != nil {
		h.logger.Error("failed to create partner", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached partner pages since data has changed
	h.cache.DeleteByPrefix("page:partners")

	// Log admin activity for audit trail (0 = no ID yet for new record)
	logActivity(c, "created", "partner", 0, c.FormValue("name"), "Created Partner '%s'", c.FormValue("name"))

	// Redirect to partner list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/partners")
}

// Edit renders the form for editing an existing partner.
//
// HTTP Method: GET
// Route: /admin/partners/:id/edit
// Template: admin/pages/partners_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// URL Parameters:
//   - id: Partner ID to edit
//
// Business Logic:
//   - Fetches the partner by ID from the database
//   - Returns 404 if partner not found
//   - Loads all partner tiers for the tier selection dropdown
//   - Sets Item to the existing partner data for form pre-population
//   - FormAction points to POST /admin/partners/:id for form submission
func (h *PartnersHandler) Edit(c echo.Context) error {
	// Parse partner ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch existing partner data
	item, err := h.queries.GetPartner(c.Request().Context(), id)
	if err != nil {
		// Return 404 if partner doesn't exist
		return echo.NewHTTPError(http.StatusNotFound)
	}

	// Load all partner tiers for the tier dropdown
	tiers, _ := h.queries.ListPartnerTiers(c.Request().Context())

	// Render the same form template as New, but with existing data
	return c.Render(http.StatusOK, "admin/pages/partners_form.html", map[string]interface{}{
		"Title":      "Edit Partner",
		"FormAction": "/admin/partners/" + c.Param("id"),  // POST endpoint for updating
		"Item":       item,                                 // Existing partner data for form pre-fill
		"Tiers":      tiers,                                // Available tiers for the dropdown
	})
}

// Update processes the form submission to update an existing partner.
//
// HTTP Method: POST
// Route: /admin/partners/:id
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// URL Parameters:
//   - id: Partner ID to update
//
// Form Fields:
//   - name (required): Partner name
//   - tier_id (required): Foreign key to partner_tiers table
//   - logo_url (optional): URL to partner logo image
//   - icon (optional): Icon class or identifier
//   - website_url (optional): Partner's website URL
//   - description (optional): Partner description text
//   - display_order (required): Numeric sort order for display
//   - is_active (checkbox): Presence indicates active, absence indicates inactive
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for IDs and order)
//   - Checkbox handling: is_active defaults to 1 (active), set to 0 if field is empty or "0"
//   - Uses sql.NullString for optional fields (Valid=true only if string is non-empty)
//   - Invalidates cached partner pages after successful update
//   - Logs admin activity for audit trail
//   - Redirects to partner list on success (303 See Other)
func (h *PartnersHandler) Update(c echo.Context) error {
	// Parse partner ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Convert form values to appropriate types
	tierID, _ := strconv.ParseInt(c.FormValue("tier_id"), 10, 64)
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Handle is_active checkbox: unchecked checkboxes don't send values
	// Default to active (1), set to inactive (0) if field is empty or explicitly "0"
	isActive := int64(1)
	if c.FormValue("is_active") == "" || c.FormValue("is_active") == "0" {
		isActive = 0
	}

	// Update partner with form data
	_, err := h.queries.UpdatePartner(c.Request().Context(), sqlc.UpdatePartnerParams{
		Name:         c.FormValue("name"),
		TierID:       tierID,
		// Optional fields use sql.NullString: Valid=true only when value is non-empty
		LogoUrl:      sql.NullString{String: c.FormValue("logo_url"), Valid: c.FormValue("logo_url") != ""},
		Icon:         sql.NullString{String: c.FormValue("icon"), Valid: c.FormValue("icon") != ""},
		WebsiteUrl:   sql.NullString{String: c.FormValue("website_url"), Valid: c.FormValue("website_url") != ""},
		Description:  sql.NullString{String: c.FormValue("description"), Valid: c.FormValue("description") != ""},
		DisplayOrder: order,
		IsActive:     isActive,
		ID:           id,
	})
	if err != nil {
		h.logger.Error("failed to update partner", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached partner pages since data has changed
	h.cache.DeleteByPrefix("page:partners")

	// Log admin activity for audit trail
	logActivity(c, "updated", "partner", id, c.FormValue("name"), "Updated Partner '%s'", c.FormValue("name"))

	// Redirect to partner list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/partners")
}

// Delete removes a partner from the database.
//
// HTTP Method: DELETE
// Route: /admin/partners/:id
// Template: None (returns 200 OK with no content)
// HTMX: Used - returns HTTP 200 with no body for HTMX to handle DOM removal
//
// URL Parameters:
//   - id: Partner ID to delete
//
// Business Logic:
//   - Performs hard delete from the database (no soft delete)
//   - Invalidates cached partner pages after successful deletion
//   - Logs admin activity for audit trail
//   - Returns 200 OK with no content for HTMX delete handlers
//   - May fail if partner has dependent records (foreign key constraints)
func (h *PartnersHandler) Delete(c echo.Context) error {
	// Parse partner ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Delete partner from database (hard delete)
	if err := h.queries.DeletePartner(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete partner", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached partner pages since data has changed
	h.cache.DeleteByPrefix("page:partners")

	// Log admin activity for audit trail
	logActivity(c, "deleted", "partner", id, "", "Deleted Partner #%d", id)

	// Return 200 OK with no content for HTMX to process
	return c.NoContent(http.StatusOK)
}

// ========================================
// PARTNER TESTIMONIALS HANDLERS
// ========================================
// The following handlers manage testimonials associated with partners.
// Testimonials are quotes from partner representatives displayed on the public site.

// TestimonialsList displays the testimonials list page.
//
// HTTP Method: GET
// Route: /admin/partners/testimonials
// Template: admin/pages/testimonials_list.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Business Logic:
//   - Retrieves all active testimonials (may include inactive if query is ListActiveTestimonials)
//   - No filtering or pagination implemented
//   - Includes partner name via JOIN for display
func (h *PartnersHandler) TestimonialsList(c echo.Context) error {
	// Fetch all testimonials from the database (includes partner name via JOIN)
	items, err := h.queries.ListActiveTestimonials(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list testimonials", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the full testimonials list page
	return c.Render(http.StatusOK, "admin/pages/testimonials_list.html", map[string]interface{}{
		"Title": "Partner Testimonials",
		"Items": items,  // List of testimonials with partner data
	})
}

// TestimonialNew renders the form for creating a new testimonial.
//
// HTTP Method: GET
// Route: /admin/partners/testimonials/new
// Template: admin/pages/testimonials_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// Business Logic:
//   - Loads all partners to populate the partner selection dropdown
//   - Sets Item to nil to indicate form is in "create" mode
//   - FormAction points to POST /admin/partners/testimonials for form submission
func (h *PartnersHandler) TestimonialNew(c echo.Context) error {
	// Load all partners for the partner dropdown (errors ignored - form will handle missing data)
	partners, _ := h.queries.ListAllPartners(c.Request().Context())

	// Render the testimonial form in "create" mode
	return c.Render(http.StatusOK, "admin/pages/testimonials_form.html", map[string]interface{}{
		"Title":      "New Testimonial",
		"FormAction": "/admin/partners/testimonials",  // POST endpoint for creating new testimonial
		"Item":       nil,                             // nil signals "create" mode to the template
		"Partners":   partners,                        // Available partners for the dropdown
	})
}

// TestimonialCreate processes the form submission to create a new testimonial.
//
// HTTP Method: POST
// Route: /admin/partners/testimonials
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// Form Fields:
//   - partner_id (required): Foreign key to partners table
//   - quote (required): The testimonial text/quote
//   - author_name (required): Name of person giving testimonial
//   - author_title (required): Job title of the author
//   - display_order (required): Numeric sort order for display
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for IDs and order)
//   - Invalidates cached partner pages after successful creation (testimonials appear on partner pages)
//   - Logs admin activity for audit trail using author_name as identifier
//   - Redirects to testimonials list on success (303 See Other)
func (h *PartnersHandler) TestimonialCreate(c echo.Context) error {
	// Convert form values to appropriate types
	partnerID, _ := strconv.ParseInt(c.FormValue("partner_id"), 10, 64)
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Create new testimonial with form data
	_, err := h.queries.CreateTestimonial(c.Request().Context(), sqlc.CreateTestimonialParams{
		PartnerID:    partnerID,
		Quote:        c.FormValue("quote"),
		AuthorName:   c.FormValue("author_name"),
		AuthorTitle:  c.FormValue("author_title"),
		DisplayOrder: order,
	})
	if err != nil {
		h.logger.Error("failed to create testimonial", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached partner pages since testimonials appear on those pages
	h.cache.DeleteByPrefix("page:partners")

	// Log admin activity for audit trail (0 = no ID yet for new record)
	logActivity(c, "created", "partner_testimonial", 0, c.FormValue("author_name"), "Created Partner Testimonial by '%s'", c.FormValue("author_name"))

	// Redirect to testimonials list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/partners/testimonials")
}

// TestimonialEdit renders the form for editing an existing testimonial.
//
// HTTP Method: GET
// Route: /admin/partners/testimonials/:id/edit
// Template: admin/pages/testimonials_form.html (full page)
// HTMX: Returns full HTML page, not a fragment
//
// URL Parameters:
//   - id: Testimonial ID to edit
//
// Business Logic:
//   - Fetches the testimonial by ID from the database
//   - Returns 404 if testimonial not found
//   - Loads all partners for the partner selection dropdown
//   - Sets Item to the existing testimonial data for form pre-population
//   - FormAction points to POST /admin/partners/testimonials/:id for form submission
func (h *PartnersHandler) TestimonialEdit(c echo.Context) error {
	// Parse testimonial ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch existing testimonial data
	item, err := h.queries.GetTestimonial(c.Request().Context(), id)
	if err != nil {
		// Return 404 if testimonial doesn't exist
		return echo.NewHTTPError(http.StatusNotFound)
	}

	// Load all partners for the partner dropdown
	partners, _ := h.queries.ListAllPartners(c.Request().Context())

	// Render the same form template as TestimonialNew, but with existing data
	return c.Render(http.StatusOK, "admin/pages/testimonials_form.html", map[string]interface{}{
		"Title":      "Edit Testimonial",
		"FormAction": "/admin/partners/testimonials/" + c.Param("id"),  // POST endpoint for updating
		"Item":       item,                                             // Existing testimonial data for form pre-fill
		"Partners":   partners,                                         // Available partners for the dropdown
	})
}

// TestimonialUpdate processes the form submission to update an existing testimonial.
//
// HTTP Method: POST
// Route: /admin/partners/testimonials/:id
// Template: None (redirects on success)
// HTMX: Not used - standard form POST with redirect
//
// URL Parameters:
//   - id: Testimonial ID to update
//
// Form Fields:
//   - partner_id (required): Foreign key to partners table
//   - quote (required): The testimonial text/quote
//   - author_name (required): Name of person giving testimonial
//   - author_title (required): Job title of the author
//   - display_order (required): Numeric sort order for display
//   - is_active (checkbox): Presence indicates active, absence indicates inactive
//
// Business Logic:
//   - Converts form string values to appropriate types (int64 for IDs and order)
//   - Checkbox handling: is_active defaults to 1 (active), set to 0 if field is empty
//   - Invalidates cached partner pages after successful update (testimonials appear on partner pages)
//   - Logs admin activity for audit trail using author_name as identifier
//   - Redirects to testimonials list on success (303 See Other)
func (h *PartnersHandler) TestimonialUpdate(c echo.Context) error {
	// Parse testimonial ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Convert form values to appropriate types
	partnerID, _ := strconv.ParseInt(c.FormValue("partner_id"), 10, 64)
	order, _ := strconv.ParseInt(c.FormValue("display_order"), 10, 64)

	// Handle is_active checkbox: unchecked checkboxes don't send values
	// Default to active (1), set to inactive (0) if field is empty
	isActive := int64(1)
	if c.FormValue("is_active") == "" {
		isActive = 0
	}

	// Update testimonial with form data
	_, err := h.queries.UpdateTestimonial(c.Request().Context(), sqlc.UpdateTestimonialParams{
		PartnerID:    partnerID,
		Quote:        c.FormValue("quote"),
		AuthorName:   c.FormValue("author_name"),
		AuthorTitle:  c.FormValue("author_title"),
		DisplayOrder: order,
		IsActive:     isActive,
		ID:           id,
	})
	if err != nil {
		h.logger.Error("failed to update testimonial", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached partner pages since testimonials appear on those pages
	h.cache.DeleteByPrefix("page:partners")

	// Log admin activity for audit trail
	logActivity(c, "updated", "partner_testimonial", id, c.FormValue("author_name"), "Updated Partner Testimonial by '%s'", c.FormValue("author_name"))

	// Redirect to testimonials list with 303 See Other status
	return c.Redirect(http.StatusSeeOther, "/admin/partners/testimonials")
}

// TestimonialDelete removes a testimonial from the database.
//
// HTTP Method: DELETE
// Route: /admin/partners/testimonials/:id
// Template: None (returns 200 OK with no content)
// HTMX: Used - returns HTTP 200 with no body for HTMX to handle DOM removal
//
// URL Parameters:
//   - id: Testimonial ID to delete
//
// Business Logic:
//   - Performs hard delete from the database (no soft delete)
//   - Invalidates cached partner pages after successful deletion (testimonials appear on partner pages)
//   - Logs admin activity for audit trail
//   - Returns 200 OK with no content for HTMX delete handlers
func (h *PartnersHandler) TestimonialDelete(c echo.Context) error {
	// Parse testimonial ID from URL parameter
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Delete testimonial from database (hard delete)
	if err := h.queries.DeleteTestimonial(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete testimonial", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Invalidate cached partner pages since testimonials appear on those pages
	h.cache.DeleteByPrefix("page:partners")

	// Log admin activity for audit trail
	logActivity(c, "deleted", "partner_testimonial", id, "", "Deleted Partner Testimonial #%d", id)

	// Return 200 OK with no content for HTMX to process
	return c.NoContent(http.StatusOK)
}
