// Package admin provides HTTP handlers for the admin panel product management functionality.
// This file contains handlers for managing product categories including listing, creating,
// editing, updating, and deleting categories. Categories organize products and appear in
// navigation and filtering throughout the CMS.
package admin

import (
	"database/sql" // Used for nullable database types (sql.NullString)
	"log/slog"     // Structured logging for error messages
	"net/http"     // HTTP status codes
	"regexp"       // Regular expressions for slug generation
	"strconv"      // String to integer conversion for form values and URL parameters
	"strings"      // String manipulation for slug generation

	"github.com/labstack/echo/v4"                 // Echo web framework for routing and context
	"github.com/narendhupati/bluejay-cms/db/sqlc" // sqlc-generated database queries
)

// slugRegexp is a compiled regular expression that matches any character
// that is NOT a lowercase letter, digit, or hyphen. Used for cleaning slugs.
var slugRegexp = regexp.MustCompile(`[^a-z0-9-]+`)

// makeSlug converts a string into a URL-friendly slug format.
// It performs the following transformations:
//   1. Converts to lowercase
//   2. Trims whitespace from ends
//   3. Replaces spaces with hyphens
//   4. Removes all characters except a-z, 0-9, and hyphens
//
// Example: "Product Category Name" -> "product-category-name"
//
// This function is used to generate slugs from category and product names
// for use in URLs throughout the frontend.
func makeSlug(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.ReplaceAll(s, " ", "-")
	s = slugRegexp.ReplaceAllString(s, "")
	return s
}

// ProductCategoriesHandler handles HTTP requests for product category management.
// Categories are used to organize products and provide navigation/filtering functionality.
// All handlers return full HTML pages (not fragments) except for delete operations.
type ProductCategoriesHandler struct {
	queries *sqlc.Queries // Database queries generated by sqlc
	logger  *slog.Logger  // Structured logger for error reporting
}

// NewProductCategoriesHandler creates and returns a new ProductCategoriesHandler instance.
// This constructor is typically called during application initialization when wiring up handlers.
func NewProductCategoriesHandler(queries *sqlc.Queries, logger *slog.Logger) *ProductCategoriesHandler {
	return &ProductCategoriesHandler{queries: queries, logger: logger}
}

// List handles GET requests to /admin/product-categories
// Renders the product categories list page showing all categories.
//
// Template: admin/pages/product_categories_list.html (full page render)
// HTMX: This endpoint returns a full HTML page, not a fragment
//
// The list displays category name, slug, icon, sort order, and action buttons.
// Categories are typically ordered by sort_order field.
func (h *ProductCategoriesHandler) List(c echo.Context) error {
	// Fetch all product categories from database
	items, err := h.queries.ListProductCategories(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list product categories", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Render the category list page
	return c.Render(http.StatusOK, "admin/pages/product_categories_list.html", map[string]interface{}{
		"Title": "Product Categories",
		"Items": items,
	})
}

// New handles GET requests to /admin/product-categories/new
// Renders the category creation form.
//
// Template: admin/pages/product_categories_form.html (full page render)
// HTMX: This endpoint returns a full HTML page, not a fragment
//
// The form includes fields for name, description, icon, image URL, and sort order.
func (h *ProductCategoriesHandler) New(c echo.Context) error {
	// Render the form template with no existing item (Item: nil indicates new category)
	return c.Render(http.StatusOK, "admin/pages/product_categories_form.html", map[string]interface{}{
		"Title":      "New Product Category",
		"FormAction": "/admin/product-categories", // POST to this endpoint for creation
		"Item":       nil,                         // No existing category data
	})
}

// Create handles POST requests to /admin/product-categories
// Processes the category creation form submission and saves the new category to the database.
//
// Form Fields:
//   - name: Required category name
//   - description: Category description text
//   - icon: Icon identifier or class name (e.g., "fa-box", "icon-electronics")
//   - image_url: Optional category image/banner URL
//   - sort_order: Display order (lower numbers appear first)
//
// On Success: Redirects to /admin/product-categories (HTTP 303 See Other)
// On Error: Returns HTTP error with appropriate status code
//
// Side Effects:
//   - Auto-generates slug from name using makeSlug helper
//   - Logs activity to audit trail
func (h *ProductCategoriesHandler) Create(c echo.Context) error {
	// Parse numeric and optional form values
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)
	imageUrl := c.FormValue("image_url")

	// Insert new category into database
	_, err := h.queries.CreateProductCategory(c.Request().Context(), sqlc.CreateProductCategoryParams{
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")), // Auto-generate URL-friendly slug from name
		Description: c.FormValue("description"),
		Icon:        c.FormValue("icon"),
		ImageUrl:    sql.NullString{String: imageUrl, Valid: imageUrl != ""}, // Only store if provided
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to create product category", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log this action to the admin activity log for audit trail
	logActivity(c, "created", "product_category", 0, c.FormValue("name"), "Created Product Category '%s'", c.FormValue("name"))

	// Redirect back to category list page after successful creation
	return c.Redirect(http.StatusSeeOther, "/admin/product-categories")
}

// Edit handles GET requests to /admin/product-categories/:id/edit
// Renders the category edit form pre-populated with existing category data.
//
// URL Parameters:
//   - id: Category ID to edit
//
// Template: admin/pages/product_categories_form.html (full page render)
// HTMX: This endpoint returns a full HTML page, not a fragment
//
// Returns HTTP 404 if category ID is not found.
// The form is identical to the New form but pre-filled with existing values.
func (h *ProductCategoriesHandler) Edit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Fetch the existing category to edit
	item, err := h.queries.GetProductCategory(c.Request().Context(), id)
	if err != nil {
		return echo.NewHTTPError(http.StatusNotFound, "Category not found")
	}

	// Render the form with existing category data
	return c.Render(http.StatusOK, "admin/pages/product_categories_form.html", map[string]interface{}{
		"Title":      "Edit Product Category",
		"FormAction": "/admin/product-categories/" + c.Param("id"), // POST to this URL for update
		"Item":       item,                                         // Pre-fill form with existing data
	})
}

// Update handles POST requests to /admin/product-categories/:id
// Processes the category update form submission and updates the existing category in the database.
//
// URL Parameters:
//   - id: Category ID to update
//
// Form Fields: Same as Create handler (see Create documentation)
//
// On Success: Redirects to /admin/product-categories (HTTP 303 See Other)
// On Error: Returns HTTP error with appropriate status code
//
// Special Handling:
//   - Regenerates slug from name in case the name was changed
//
// Side Effects:
//   - Logs activity to audit trail
func (h *ProductCategoriesHandler) Update(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Parse form values
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)
	imageUrl := c.FormValue("image_url")

	// Update the category record with new values
	_, err := h.queries.UpdateProductCategory(c.Request().Context(), sqlc.UpdateProductCategoryParams{
		ID:          id,
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")), // Regenerate slug in case name changed
		Description: c.FormValue("description"),
		Icon:        c.FormValue("icon"),
		ImageUrl:    sql.NullString{String: imageUrl, Valid: imageUrl != ""}, // Only store if provided
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to update product category", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log update to audit trail
	logActivity(c, "updated", "product_category", id, c.FormValue("name"), "Updated Product Category '%s'", c.FormValue("name"))

	// Redirect back to category list
	return c.Redirect(http.StatusSeeOther, "/admin/product-categories")
}

// Delete handles DELETE requests to /admin/product-categories/:id
// Permanently deletes a category from the database.
//
// URL Parameters:
//   - id: Category ID to delete
//
// HTMX: Returns either an empty response (HTTP 204 No Content) on success,
// or a text error message (HTTP 409 Conflict) if deletion is blocked by foreign key.
//
// Important: Categories cannot be deleted if they still have products assigned to them.
// The database foreign key constraint will prevent deletion and return a helpful error message.
//
// Side Effects:
//   - Logs deletion to audit trail (only if successful)
func (h *ProductCategoriesHandler) Delete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)

	// Attempt to delete the category from database
	if err := h.queries.DeleteProductCategory(c.Request().Context(), id); err != nil {
		// Check if deletion failed due to foreign key constraint (products still assigned)
		if strings.Contains(err.Error(), "FOREIGN KEY constraint failed") {
			return c.String(http.StatusConflict, "Cannot delete this category because it still has products assigned to it. Please reassign or remove those products first.")
		}
		h.logger.Error("failed to delete product category", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}

	// Log deletion to audit trail
	logActivity(c, "deleted", "product_category", id, "", "Deleted Product Category #%d", id)

	// Return empty 204 response (HTMX will remove the row)
	return c.NoContent(http.StatusOK)
}
