// Package admin provides HTTP handlers for the admin panel content management features.
// This file contains handlers for managing Whitepaper Topics — categories for organizing whitepapers.
package admin

import (
	// Standard library imports
	"database/sql" // Used for nullable SQL types (NullString)
	"log/slog"     // Structured logging for error tracking and debugging
	"net/http"     // HTTP status codes for responses
	"strconv"      // String to integer conversions for route params and form values

	// Third-party imports
	"github.com/labstack/echo/v4" // Echo web framework for HTTP routing and context handling

	// Internal imports
	"github.com/narendhupati/bluejay-cms/db/sqlc" // Generated SQL queries from sqlc
)

// WhitepaperTopicsHandler handles all HTTP requests for whitepaper topics management in the admin panel.
// It manages CRUD operations for topics used to categorize and filter whitepapers.
type WhitepaperTopicsHandler struct {
	queries *sqlc.Queries // Database query interface generated by sqlc
	logger  *slog.Logger  // Structured logger for error tracking
	// Note: No cache service - topic changes are less frequent and don't require cache invalidation
}

// NewWhitepaperTopicsHandler creates and initializes a new WhitepaperTopicsHandler.
// Parameters:
//   - queries: sqlc-generated database query interface
//   - logger: structured logger for error logging
//
// Returns a fully initialized WhitepaperTopicsHandler ready to handle HTTP requests.
func NewWhitepaperTopicsHandler(queries *sqlc.Queries, logger *slog.Logger) *WhitepaperTopicsHandler {
	return &WhitepaperTopicsHandler{queries: queries, logger: logger}
}

// List displays all whitepaper topics with whitepaper counts.
//
// HTTP Method: GET
// Route: /admin/whitepaper-topics
// Template: admin/pages/whitepaper_topics_list.html (full page render)
// HTMX: No - returns full page
//
// This handler retrieves all topics with a count of associated whitepapers.
// Topics are used for categorization and filtering on the public whitepaper library.
func (h *WhitepaperTopicsHandler) List(c echo.Context) error {
	items, err := h.queries.ListWhitepaperTopicsWithCount(c.Request().Context())
	if err != nil {
		h.logger.Error("failed to list whitepaper topics", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	return c.Render(http.StatusOK, "admin/pages/whitepaper_topics_list.html", map[string]interface{}{
		"Title": "Whitepaper Topics",
		"Items": items,
	})
}

// New displays the form for creating a new whitepaper topic.
//
// HTTP Method: GET
// Route: /admin/whitepaper-topics/new
// Template: admin/pages/whitepaper_topics_form.html (full page render)
// HTMX: No - returns full page
//
// This handler renders an empty topic creation form. The form submits to
// the Create handler via POST /admin/whitepaper-topics.
func (h *WhitepaperTopicsHandler) New(c echo.Context) error {
	return c.Render(http.StatusOK, "admin/pages/whitepaper_topics_form.html", map[string]interface{}{
		"Title":      "New Whitepaper Topic",
		"FormAction": "/admin/whitepaper-topics",
		"Item":       nil,
	})
}

// Create handles whitepaper topic creation.
//
// HTTP Method: POST
// Route: /admin/whitepaper-topics
// HTMX: No - performs redirect after success
// Template: None - redirects to /admin/whitepaper-topics on success
//
// Form Fields:
//   - name: Topic name (required)
//   - slug: URL slug (auto-generated from name using makeSlug)
//   - color_hex: Hex color code for topic badge/tag display (e.g., "#FF5733")
//   - icon: Icon identifier or class name for topic visual
//   - description: Optional description of the topic
//   - sort_order: Display order for topic sorting (integer)
//
// Business Logic:
//   - Auto-generates slug from name (using makeSlug helper from common.go)
//   - Logs activity for audit trail
func (h *WhitepaperTopicsHandler) Create(c echo.Context) error {
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)
	desc := c.FormValue("description")
	_, err := h.queries.CreateWhitepaperTopic(c.Request().Context(), sqlc.CreateWhitepaperTopicParams{
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),
		ColorHex:    c.FormValue("color_hex"),
		Icon:        c.FormValue("icon"),
		Description: sql.NullString{String: desc, Valid: desc != ""},
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to create whitepaper topic", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "created", "whitepaper_topic", 0, c.FormValue("name"), "Created Whitepaper Topic '%s'", c.FormValue("name"))
	return c.Redirect(http.StatusSeeOther, "/admin/whitepaper-topics")
}

// Edit displays the form for editing a whitepaper topic.
//
// HTTP Method: GET
// Route: /admin/whitepaper-topics/:id/edit
// Template: admin/pages/whitepaper_topics_form.html (full page render)
// HTMX: No - returns full page
//
// Route Parameters:
//   - id: Topic ID (int64)
//
// This handler loads an existing topic and renders the edit form.
// The form submits to the Update handler via POST /admin/whitepaper-topics/:id.
func (h *WhitepaperTopicsHandler) Edit(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	item, err := h.queries.GetWhitepaperTopic(c.Request().Context(), id)
	if err != nil {
		return echo.NewHTTPError(http.StatusNotFound, "Topic not found")
	}
	return c.Render(http.StatusOK, "admin/pages/whitepaper_topics_form.html", map[string]interface{}{
		"Title":      "Edit Whitepaper Topic",
		"FormAction": "/admin/whitepaper-topics/" + c.Param("id"),
		"Item":       item,
	})
}

// Update handles whitepaper topic updates.
//
// HTTP Method: POST
// Route: /admin/whitepaper-topics/:id
// HTMX: No - performs redirect after success
// Template: None - redirects to /admin/whitepaper-topics on success
//
// Route Parameters:
//   - id: Topic ID (int64)
//
// Form Fields: Same as Create handler (see Create documentation)
//
// Business Logic:
//   - Auto-generates slug from name
//   - Logs activity for audit trail
func (h *WhitepaperTopicsHandler) Update(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	sortOrder, _ := strconv.ParseInt(c.FormValue("sort_order"), 10, 64)
	desc := c.FormValue("description")
	_, err := h.queries.UpdateWhitepaperTopic(c.Request().Context(), sqlc.UpdateWhitepaperTopicParams{
		ID:          id,
		Name:        c.FormValue("name"),
		Slug:        makeSlug(c.FormValue("name")),
		ColorHex:    c.FormValue("color_hex"),
		Icon:        c.FormValue("icon"),
		Description: sql.NullString{String: desc, Valid: desc != ""},
		SortOrder:   sortOrder,
	})
	if err != nil {
		h.logger.Error("failed to update whitepaper topic", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "updated", "whitepaper_topic", id, c.FormValue("name"), "Updated Whitepaper Topic '%s'", c.FormValue("name"))
	return c.Redirect(http.StatusSeeOther, "/admin/whitepaper-topics")
}

// Delete handles whitepaper topic deletion.
//
// HTTP Method: DELETE
// Route: /admin/whitepaper-topics/:id
// HTMX: Yes - triggered by hx-delete on delete button
// Template: None - returns HTTP 200 OK
//
// Route Parameters:
//   - id: Topic ID (int64)
//
// Business Logic:
//   - Deletes topic record (will fail if whitepapers reference this topic due to foreign key)
//   - Logs activity for audit trail
//   - Returns 200 OK for HTMX compatibility (HTMX removes element from DOM)
func (h *WhitepaperTopicsHandler) Delete(c echo.Context) error {
	id, _ := strconv.ParseInt(c.Param("id"), 10, 64)
	if err := h.queries.DeleteWhitepaperTopic(c.Request().Context(), id); err != nil {
		h.logger.Error("failed to delete whitepaper topic", "error", err)
		return echo.NewHTTPError(http.StatusInternalServerError)
	}
	logActivity(c, "deleted", "whitepaper_topic", id, "", "Deleted Whitepaper Topic #%d", id)
	return c.NoContent(http.StatusOK)
}
