-- ====================================================================
-- ACTIVITY LOG QUERIES
-- ====================================================================
-- This file manages audit trail queries for tracking admin user actions
-- throughout the CMS. All create/update/delete operations should be logged
-- to provide accountability and change history.
--
-- Managed entity:
-- - activity_log: stores admin actions with context (who, what, when, where)
-- ====================================================================

-- name: CreateActivityLog :exec
-- sqlc annotation: :exec returns no data, only error or success
-- Purpose: Records a new activity log entry when admins perform actions
-- Parameters (6 positional):
--   1. user_id (INTEGER): ID of admin user performing the action
--   2. action (TEXT): type of action (e.g., "created", "updated", "deleted")
--   3. resource_type (TEXT): entity being modified (e.g., "blog_post", "product")
--   4. resource_id (INTEGER): ID of the modified resource
--   5. resource_title (TEXT): human-readable title of modified resource
--   6. description (TEXT): detailed description of the action
-- Return type: none (exec only returns error status)
-- Note: created_at timestamp is auto-generated by database
INSERT INTO activity_log (user_id, action, resource_type, resource_id, resource_title, description)
VALUES (?, ?, ?, ?, ?, ?);

-- name: ListActivityLogs :many
-- sqlc annotation: :many returns slice of activity_log rows
-- Purpose: Retrieves paginated, filtered activity log entries for admin dashboard
-- Parameters (named parameters using @ prefix):
--   @filter_action (TEXT): filter by action type (empty string = no filter)
--   @filter_search (TEXT): search term for description field (empty = no filter)
--   @page_limit (INTEGER): number of results per page
--   @page_offset (INTEGER): pagination offset (page_number * page_limit)
-- Return type: slice of activity_log rows
-- Complex WHERE logic:
--   - CAST to TEXT handles nullable/empty filter parameters safely
--   - Empty string check allows "no filter" without complex null handling
--   - LIKE with wildcards enables partial text search in descriptions
-- Note: Always ordered by created_at DESC to show newest actions first
SELECT * FROM activity_log
WHERE
    -- Filter by action type if provided, otherwise include all actions
    (CAST(@filter_action AS TEXT) = '' OR action = @filter_action)
    -- Filter by search term in description if provided
    AND (CAST(@filter_search AS TEXT) = '' OR description LIKE '%' || @filter_search || '%')
ORDER BY created_at DESC
LIMIT @page_limit OFFSET @page_offset;

-- name: CountActivityLogs :one
-- sqlc annotation: :one returns single integer count
-- Purpose: Counts total activity logs matching filters (for pagination UI)
-- Parameters (named):
--   @filter_action (TEXT): same filter as ListActivityLogs
--   @filter_search (TEXT): same search filter as ListActivityLogs
-- Return type: single integer COUNT(*) value
-- Note: WHERE clause MUST match ListActivityLogs exactly for accurate pagination
SELECT COUNT(*) FROM activity_log
WHERE
    -- Same filter logic as ListActivityLogs for consistency
    (CAST(@filter_action AS TEXT) = '' OR action = @filter_action)
    AND (CAST(@filter_search AS TEXT) = '' OR description LIKE '%' || @filter_search || '%');
