// Package main is the entry point for the Bluejay CMS server application.
// It initializes and starts an HTTP server that provides both a public-facing
// website and an administrative backend for managing content. The server uses
// Echo framework for routing, SQLite for data persistence, and html/template
// with HTMX for server-side rendering with dynamic client interactions.
package main

import (
	// Standard library imports for core functionality
	"context" // Used for graceful shutdown with timeout context
	"log/slog" // Structured logging throughout the application
	"net/http" // HTTP constants and server types
	"os"       // OS signals for graceful shutdown, environment, and file operations
	"os/signal" // Signal handling for interrupt/termination signals
	"time"     // Time utilities for timeouts, rate limiting, and timestamps

	// Third-party Echo web framework and middleware
	"github.com/labstack/echo/v4"            // High-performance HTTP router and framework
	"github.com/labstack/echo/v4/middleware" // Built-in Echo middleware (Gzip compression)

	// Internal packages - database layer
	"github.com/narendhupati/bluejay-cms/db/sqlc" // Type-safe SQL query code generated by sqlc
	"github.com/narendhupati/bluejay-cms/internal/database" // Database initialization and migrations

	// Internal packages - HTTP handlers (separated by public vs admin access)
	adminHandlers "github.com/narendhupati/bluejay-cms/internal/handlers/admin"   // Admin panel CRUD handlers
	publicHandlers "github.com/narendhupati/bluejay-cms/internal/handlers/public" // Public-facing content handlers

	// Internal packages - middleware, services, and template rendering
	customMiddleware "github.com/narendhupati/bluejay-cms/internal/middleware" // Custom middleware (auth, logging, security)
	"github.com/narendhupati/bluejay-cms/internal/services"                    // Business logic services (cache, uploads, etc.)
	"github.com/narendhupati/bluejay-cms/internal/templates"                   // Template rendering engine wrapper
)

// main is the application entry point. It performs the following initialization sequence:
// 1. Sets up structured JSON logging
// 2. Initializes SQLite database connection and runs migrations
// 3. Configures session management
// 4. Sets up Echo web server with middleware stack
// 5. Initializes business logic services (products, uploads, cache, activity logging)
// 6. Registers all public and admin route handlers
// 7. Starts HTTP server on port 28090
// 8. Waits for OS interrupt signal for graceful shutdown
//
// The server runs indefinitely until terminated, handling both public website
// requests and admin panel operations through a single HTTP server instance.
func main() {
	// Initialize structured JSON logger for production-ready logging
	// All logs are written to stdout in JSON format at INFO level and above
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))

	// Initialize SQLite database connection
	// Database file "bluejay.db" is created in the current working directory if it doesn't exist
	dbPath := "bluejay.db"
	if v := os.Getenv("DB_PATH"); v != "" {
		dbPath = v
	}
	db, err := database.InitDB(database.Config{
		Path: dbPath,
	})
	if err != nil {
		logger.Error("failed to initialize database", "error", err)
		os.Exit(1)
	}
	// Ensure database connection is closed when main exits
	defer database.Close(db)

	// Run database migrations to ensure schema is up-to-date
	// Migrations are SQL files in db/migrations directory, executed in order
	if err := database.RunMigrations(db, "db/migrations"); err != nil {
		logger.Error("failed to run migrations", "error", err)
		os.Exit(1)
	}

	// Initialize sqlc-generated query interface for type-safe database operations
	// All database queries are defined in db/queries/*.sql and compiled to Go code
	queries := sqlc.New(db)

	// Initialize session store with encryption key for secure cookie-based sessions
	// WARNING: This secret should be replaced with a secure random string in production
	// The secret must be at least 32 characters for proper AES encryption
	customMiddleware.InitSessionStore("change-this-secret-in-production-minimum-32-chars")

	// Create new Echo web framework instance
	e := echo.New()
	// Hide the Echo startup banner for cleaner logs
	e.HideBanner = true

	// Configure template renderer for server-side HTML rendering
	// Templates are loaded from the "templates" directory
	// Used by both admin panel and public pages
	e.Renderer = templates.NewRenderer("templates")

	// Apply middleware stack (executed in order for each request):
	// 1. Recovery - catches panics and returns 500 errors gracefully
	e.Use(customMiddleware.Recovery(logger))
	// 2. Logging - logs all HTTP requests with method, path, status, and latency
	e.Use(customMiddleware.Logging(logger))
	// 3. Gzip - compresses responses for faster transfers
	e.Use(middleware.Gzip())
	// 4. SecurityHeaders - adds security headers (CSP, X-Frame-Options, etc.)
	e.Use(customMiddleware.SecurityHeaders())
	// 5. SessionMiddleware - manages user sessions via encrypted cookies
	e.Use(customMiddleware.SessionMiddleware())

	// Serve static files (CSS, JS, images) from the public directory
	// Accessible at URLs like /public/css/style.css
	e.Static("/public", "public")

	// Initialize business logic services used across multiple handlers
	// These services provide reusable functionality and maintain separation of concerns

	// ProductService - handles product-related business logic like slug generation
	productSvc := services.NewProductService(queries)

	// UploadService - manages file uploads, validation, and storage
	// Files are stored in "public/uploads" directory
	uploadSvc := services.NewUploadService("public/uploads")

	// Cache - in-memory cache for frequently accessed data to reduce database queries
	// Used for settings, categories, and other relatively static content
	appCache := services.NewCache()

	// ActivityLogService - tracks user actions in the admin panel for audit trail
	// Logs events like content creation, updates, and deletions
	activitySvc := services.NewActivityLogService(queries, logger)

	// Inject activity log service into admin handlers so all admin actions are logged
	// This global injection allows handlers to log activities without tight coupling
	adminHandlers.SetActivityLogService(activitySvc)

	// ═══════════════════════════════════════════════════════════════════════════
	// PUBLIC ROUTES - accessible to all visitors without authentication
	// ═══════════════════════════════════════════════════════════════════════════

	// Create route group for all public pages (empty prefix means root level)
	publicGroup := e.Group("")
	// Load site settings (logo, title, meta tags) into context for every public request
	// This middleware makes settings available to all public templates
	publicGroup.Use(customMiddleware.SettingsLoader(queries))

	// Homepage route - displays hero sections, stats, testimonials, and CTAs
	homeHandler := publicHandlers.NewHomeHandler(queries, logger)
	publicGroup.GET("/", homeHandler.ShowHomePage)

	// Health check endpoint - returns JSON status for monitoring/load balancers
	// Used by infrastructure to verify the application is running
	publicGroup.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{
			"status": "ok",
			"time":   time.Now().Format(time.RFC3339),
		})
	})

	// ─────────────────────────────────────────────────────────────────────────
	// Public Product Routes (Phase 3)
	// ─────────────────────────────────────────────────────────────────────────
	// Product catalog with search, category filtering, and detail pages

	productsHandler := publicHandlers.NewProductsHandler(queries, logger, productSvc, appCache)

	// GET /products - main product listing page with optional filters
	publicGroup.GET("/products", productsHandler.ProductsList)

	// GET /products/search - HTMX endpoint for typeahead product search
	// Returns HTML fragment with matching products for dynamic updates
	publicGroup.GET("/products/search", productsHandler.ProductSearch)

	// GET /products/:category - filtered product list by category slug
	publicGroup.GET("/products/:category", productsHandler.ProductsByCategory)

	// GET /products/:category/:slug - individual product detail page
	// Shows specs, features, certifications, images, and downloads
	publicGroup.GET("/products/:category/:slug", productsHandler.ProductDetail)

	// ─────────────────────────────────────────────────────────────────────────
	// Public Solution Routes (Phase 4)
	// ─────────────────────────────────────────────────────────────────────────
	// Industry solutions with stats, challenges, associated products, and CTAs

	solutionsHandler := publicHandlers.NewSolutionsHandler(queries, logger, appCache)

	// GET /solutions - listing of all industry solutions
	publicGroup.GET("/solutions", solutionsHandler.SolutionsList)

	// GET /solutions/:slug - individual solution detail page
	// Displays stats, challenges addressed, related products, and call-to-action buttons
	publicGroup.GET("/solutions/:slug", solutionsHandler.SolutionDetail)

	// ─────────────────────────────────────────────────────────────────────────
	// Public Blog Routes (Phase 5)
	// ─────────────────────────────────────────────────────────────────────────
	// Blog posts with categories, authors, tags, and related products

	blogHandler := publicHandlers.NewBlogHandler(queries, logger, appCache)

	// GET /blog - blog post listing with filtering by category, author, and tag
	publicGroup.GET("/blog", blogHandler.BlogListing)

	// GET /blog/:slug - individual blog post detail page
	// Shows rich content, author info, related products, and tags
	publicGroup.GET("/blog/:slug", blogHandler.BlogPost)

	// ─────────────────────────────────────────────────────────────────────────
	// Static file serving for user uploads
	// ─────────────────────────────────────────────────────────────────────────
	// Serves uploaded images, PDFs, and other media files
	// Accessible at URLs like /uploads/images/product-photo.jpg
	e.Static("/uploads", "public/uploads")

	// ═══════════════════════════════════════════════════════════════════════════
	// ADMIN ROUTES - authentication and protected admin panel
	// ═══════════════════════════════════════════════════════════════════════════

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Authentication Routes (no auth required)
	// ─────────────────────────────────────────────────────────────────────────
	// Login/logout endpoints that don't require existing authentication

	adminAuthGroup := e.Group("/admin")
	authHandler := adminHandlers.NewAuthHandler(queries, logger)

	// GET /admin/login - displays login form
	adminAuthGroup.GET("/login", authHandler.ShowLoginPage)

	// POST /admin/login - processes login credentials and creates session
	adminAuthGroup.POST("/login", authHandler.LoginSubmit)

	// POST /admin/logout - destroys session and redirects to login
	adminAuthGroup.POST("/logout", authHandler.Logout)

	// ─────────────────────────────────────────────────────────────────────────
	// Protected Admin Routes - require authentication
	// ─────────────────────────────────────────────────────────────────────────
	// All routes in this group check for valid session before allowing access
	// RequireAuth middleware redirects unauthenticated users to /admin/login

	adminGroup := e.Group("/admin", customMiddleware.RequireAuth())

	// Dashboard - main admin panel landing page with stats and recent activity
	dashboardHandler := adminHandlers.NewDashboardHandler(queries, logger)
	adminGroup.GET("/dashboard", dashboardHandler.ShowDashboard)

	// ─────────────────────────────────────────────────────────────────────────
	// Master Table CRUD Routes (Phase 2)
	// ─────────────────────────────────────────────────────────────────────────
	// Management interfaces for foundational taxonomy and classification data

	// Product Categories - organize products into hierarchical categories
	pcHandler := adminHandlers.NewProductCategoriesHandler(queries, logger)
	adminGroup.GET("/product-categories", pcHandler.List)           // List all categories
	adminGroup.GET("/product-categories/new", pcHandler.New)        // Show creation form
	adminGroup.POST("/product-categories", pcHandler.Create)        // Process new category
	adminGroup.GET("/product-categories/:id/edit", pcHandler.Edit)  // Show edit form
	adminGroup.POST("/product-categories/:id", pcHandler.Update)    // Process updates
	adminGroup.DELETE("/product-categories/:id", pcHandler.Delete)  // Delete category (HTMX)

	// Blog Categories - classify blog posts by topic
	bcHandler := adminHandlers.NewBlogCategoriesHandler(queries, logger)
	adminGroup.GET("/blog-categories", bcHandler.List)
	adminGroup.GET("/blog-categories/new", bcHandler.New)
	adminGroup.POST("/blog-categories", bcHandler.Create)
	adminGroup.GET("/blog-categories/:id/edit", bcHandler.Edit)
	adminGroup.POST("/blog-categories/:id", bcHandler.Update)
	adminGroup.DELETE("/blog-categories/:id", bcHandler.Delete)

	// Blog Authors - manage author profiles with bio and photo
	baHandler := adminHandlers.NewBlogAuthorsHandler(queries, logger)
	adminGroup.GET("/blog-authors", baHandler.List)
	adminGroup.GET("/blog-authors/new", baHandler.New)
	adminGroup.POST("/blog-authors", baHandler.Create)
	adminGroup.GET("/blog-authors/:id/edit", baHandler.Edit)
	adminGroup.POST("/blog-authors/:id", baHandler.Update)
	adminGroup.DELETE("/blog-authors/:id", baHandler.Delete)

	// Industries - define target industries for solutions and case studies
	indHandler := adminHandlers.NewIndustriesHandler(queries, logger)
	adminGroup.GET("/industries", indHandler.List)
	adminGroup.GET("/industries/new", indHandler.New)
	adminGroup.POST("/industries", indHandler.Create)
	adminGroup.GET("/industries/:id/edit", indHandler.Edit)
	adminGroup.POST("/industries/:id", indHandler.Update)
	adminGroup.DELETE("/industries/:id", indHandler.Delete)

	// Partner Tiers - classification levels for business partners
	ptHandler := adminHandlers.NewPartnerTiersHandler(queries, logger)
	adminGroup.GET("/partner-tiers", ptHandler.List)
	adminGroup.GET("/partner-tiers/new", ptHandler.New)
	adminGroup.POST("/partner-tiers", ptHandler.Create)
	adminGroup.GET("/partner-tiers/:id/edit", ptHandler.Edit)
	adminGroup.POST("/partner-tiers/:id", ptHandler.Update)
	adminGroup.DELETE("/partner-tiers/:id", ptHandler.Delete)

	// Whitepaper Topics - categorize whitepapers by subject area
	wtHandler := adminHandlers.NewWhitepaperTopicsHandler(queries, logger)
	adminGroup.GET("/whitepaper-topics", wtHandler.List)
	adminGroup.GET("/whitepaper-topics/new", wtHandler.New)
	adminGroup.POST("/whitepaper-topics", wtHandler.Create)
	adminGroup.GET("/whitepaper-topics/:id/edit", wtHandler.Edit)
	adminGroup.POST("/whitepaper-topics/:id", wtHandler.Update)
	adminGroup.DELETE("/whitepaper-topics/:id", wtHandler.Delete)

	// ─────────────────────────────────────────────────────────────────────────
	// Site-Wide Configuration Routes
	// ─────────────────────────────────────────────────────────────────────────
	// Global settings affecting header, footer, and general site behavior

	// Header Management - configure logo, navigation, and header content
	headerHandler := adminHandlers.NewHeaderHandler(queries, logger)
	adminGroup.GET("/header", headerHandler.Edit)
	adminGroup.POST("/header", headerHandler.Update)

	// Footer Management - configure footer links, copyright, and social media
	footerHandler := adminHandlers.NewFooterHandler(queries, logger)
	adminGroup.GET("/footer", footerHandler.Edit)
	adminGroup.POST("/footer", footerHandler.Update)

	// Global Settings - site name, SEO defaults, contact info, analytics
	settingsHandler := adminHandlers.NewSettingsHandler(queries, logger)
	adminGroup.GET("/settings", settingsHandler.Edit)
	adminGroup.POST("/settings", settingsHandler.Update)

	// Page Sections - manage reusable content blocks across pages
	psHandler := adminHandlers.NewPageSectionsHandler(queries, logger)
	adminGroup.GET("/page-sections", psHandler.List)
	adminGroup.GET("/page-sections/:id/edit", psHandler.Edit)
	adminGroup.POST("/page-sections/:id", psHandler.Update)

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Product Management Routes (Phase 3)
	// ─────────────────────────────────────────────────────────────────────────
	// Full CRUD interface for products with image uploads and cache invalidation

	adminProductsHandler := adminHandlers.NewProductsHandler(queries, logger, uploadSvc, appCache)
	adminGroup.GET("/products", adminProductsHandler.List)           // List all products with search/filter
	adminGroup.GET("/products/new", adminProductsHandler.New)        // Show product creation form
	adminGroup.POST("/products", adminProductsHandler.Create)        // Process new product with image upload
	adminGroup.GET("/products/:id/edit", adminProductsHandler.Edit)  // Show edit form with existing data
	adminGroup.POST("/products/:id", adminProductsHandler.Update)    // Update product, invalidate cache
	adminGroup.DELETE("/products/:id", adminProductsHandler.Delete)  // Delete product (HTMX response)

	// ─────────────────────────────────────────────────────────────────────────
	// Product Sub-Entity Routes (Phase 3)
	// ─────────────────────────────────────────────────────────────────────────
	// HTMX endpoints for managing product details: specs, features, certs, etc.
	// These routes return HTML fragments for in-page updates without full reload

	pdHandler := adminHandlers.NewProductDetailsHandler(queries, logger, uploadSvc)

	// Technical Specifications - key/value pairs (e.g., "Weight: 2.5kg")
	adminGroup.GET("/products/:id/specs", pdHandler.ListSpecs)             // HTMX: render specs list
	adminGroup.POST("/products/:id/specs", pdHandler.AddSpec)              // HTMX: add new spec
	adminGroup.DELETE("/products/:id/specs", pdHandler.DeleteSpecs)              // HTMX: bulk delete specs
	adminGroup.DELETE("/products/:id/specs/:spec_id", pdHandler.DeleteSpec)       // HTMX: delete single spec

	// Features - bullet points highlighting product capabilities
	adminGroup.GET("/products/:id/features", pdHandler.ListFeatures)       // HTMX: render features list
	adminGroup.POST("/products/:id/features", pdHandler.AddFeature)        // HTMX: add new feature
	adminGroup.DELETE("/products/:id/features", pdHandler.DeleteFeatures)                // HTMX: bulk delete features
	adminGroup.DELETE("/products/:id/features/:feature_id", pdHandler.DeleteFeature)     // HTMX: delete single feature
	adminGroup.POST("/products/:id/features/:feature_id", pdHandler.UpdateFeature)        // HTMX: update single feature

	// Certifications - compliance badges and industry certifications
	adminGroup.GET("/products/:id/certifications", pdHandler.ListCertifications)       // HTMX: render certs list
	adminGroup.POST("/products/:id/certifications", pdHandler.AddCertification)        // HTMX: add new cert
	adminGroup.DELETE("/products/:id/certifications", pdHandler.DeleteCertifications)            // HTMX: bulk delete certs
	adminGroup.DELETE("/products/:id/certifications/:cert_id", pdHandler.DeleteCertification)   // HTMX: delete single cert

	// Downloads - datasheets, manuals, CAD files
	adminGroup.GET("/products/:id/downloads", pdHandler.ListDownloads)                     // HTMX: render downloads list
	adminGroup.POST("/products/:id/downloads", pdHandler.AddDownload)                      // HTMX: upload new file
	adminGroup.DELETE("/products/:id/downloads/:download_id", pdHandler.DeleteDownload)    // HTMX: delete specific file

	// Product Images - photo gallery for product detail pages
	adminGroup.GET("/products/:id/images", pdHandler.ListImages)                   // HTMX: render image gallery
	adminGroup.POST("/products/:id/images", pdHandler.AddImage)                    // HTMX: upload new image
	adminGroup.DELETE("/products/:id/images/:image_id", pdHandler.DeleteImage)     // HTMX: delete specific image

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Blog Management Routes (Phase 5)
	// ─────────────────────────────────────────────────────────────────────────
	// Blog post editor with Trix WYSIWYG, tag management, and product linking

	adminBlogPostsHandler := adminHandlers.NewBlogPostsHandler(queries, logger, appCache)
	adminGroup.GET("/blog/posts", adminBlogPostsHandler.List)           // List posts with filters
	adminGroup.GET("/blog/posts/new", adminBlogPostsHandler.New)        // Show post editor (Trix)
	adminGroup.POST("/blog/posts", adminBlogPostsHandler.Create)        // Save new post with tags
	adminGroup.GET("/blog/posts/:id/edit", adminBlogPostsHandler.Edit)  // Edit existing post
	adminGroup.POST("/blog/posts/:id", adminBlogPostsHandler.Update)    // Update post content
	adminGroup.DELETE("/blog/posts/:id", adminBlogPostsHandler.Delete)  // Delete post (HTMX)
	// HTMX endpoint: search products to link in blog post
	adminGroup.GET("/blog/products/search", adminBlogPostsHandler.SearchProducts)

	// Blog Tags - manage and create tags for blog posts
	adminBlogTagsHandler := adminHandlers.NewBlogTagsHandler(queries, logger)
	adminGroup.GET("/blog/tags", adminBlogTagsHandler.List)                     // List all tags
	adminGroup.POST("/blog/tags", adminBlogTagsHandler.Create)                  // Create new tag
	adminGroup.GET("/blog/tags/search", adminBlogTagsHandler.Search)            // HTMX: tag autocomplete
	adminGroup.POST("/blog/tags/quick-create", adminBlogTagsHandler.QuickCreate) // HTMX: inline tag creation
	adminGroup.DELETE("/blog/tags/:id", adminBlogTagsHandler.Delete)            // Delete tag (HTMX)

	// ─────────────────────────────────────────────────────────────────────────
	// Public Whitepaper Routes (Phase 8)
	// ─────────────────────────────────────────────────────────────────────────
	// Gated content with lead capture forms before download

	whitepapersHandler := publicHandlers.NewWhitepapersHandler(queries, logger, appCache)
	publicGroup.GET("/whitepapers", whitepapersHandler.WhitepapersList)                   // List whitepapers
	publicGroup.GET("/whitepapers/:slug", whitepapersHandler.WhitepaperDetail)            // Detail with download form
	publicGroup.POST("/whitepapers/:slug/download", whitepapersHandler.WhitepaperDownload) // Process form, log download

	// ─────────────────────────────────────────────────────────────────────────
	// Public Contact Routes (Phase 8)
	// ─────────────────────────────────────────────────────────────────────────
	// Contact form with rate limiting to prevent spam

	contactHandler := publicHandlers.NewContactHandler(queries, logger, appCache)
	// Rate limiter: maximum 5 submissions per hour per IP address
	contactLimiter := customMiddleware.NewRateLimiter(5, time.Hour)
	publicGroup.GET("/contact", contactHandler.ShowContactPage)       // Display contact form and offices
	// Contact form submission with rate limiting middleware applied
	publicGroup.POST("/contact/submit", contactHandler.SubmitContactForm, contactLimiter.Middleware())

	// ─────────────────────────────────────────────────────────────────────────
	// Public About & Partners Routes (Phase 7)
	// ─────────────────────────────────────────────────────────────────────────

	// About page - company overview, mission/vision/values, milestones, certifications
	aboutHandler := publicHandlers.NewAboutHandler(queries, logger, appCache)
	publicGroup.GET("/about", aboutHandler.AboutPage)

	// Partners page - partner directory with tier filtering and testimonials
	partnersPageHandler := publicHandlers.NewPartnersHandler(queries, logger, appCache)
	publicGroup.GET("/partners", partnersPageHandler.PartnersPage)

	// ─────────────────────────────────────────────────────────────────────────
	// Search Routes (Phase 9)
	// ─────────────────────────────────────────────────────────────────────────
	// Full-text search across products, blog posts, solutions, and case studies

	searchHandler := publicHandlers.NewSearchHandler(db, logger)
	publicGroup.GET("/search", searchHandler.SearchPage)           // Search results page
	publicGroup.GET("/search/suggest", searchHandler.SearchSuggest) // HTMX: autocomplete suggestions

	// ─────────────────────────────────────────────────────────────────────────
	// SEO Routes (Phase 9)
	// ─────────────────────────────────────────────────────────────────────────
	// XML sitemap and robots.txt for search engine optimization

	sitemapHandler := publicHandlers.NewSitemapHandler(queries, logger, "https://bluejaylabs.com")
	publicGroup.GET("/sitemap.xml", sitemapHandler.Sitemap)    // Dynamic XML sitemap of all public pages
	publicGroup.GET("/robots.txt", sitemapHandler.RobotsTxt)   // Robots.txt with crawl directives

	// ─────────────────────────────────────────────────────────────────────────
	// Public Case Study Routes (Phase 6)
	// ─────────────────────────────────────────────────────────────────────────
	// Success stories with metrics, challenges, and associated products

	caseStudiesHandler := publicHandlers.NewCaseStudiesHandler(queries, logger, appCache)
	publicGroup.GET("/case-studies", caseStudiesHandler.CaseStudiesList)         // List all case studies
	publicGroup.GET("/case-studies/:slug", caseStudiesHandler.CaseStudyDetail)   // Individual case study detail

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Case Study Management Routes (Phase 6)
	// ─────────────────────────────────────────────────────────────────────────
	// Case study editor with product linking and metrics tracking

	adminCaseStudiesHandler := adminHandlers.NewCaseStudiesHandler(queries, logger, appCache)
	adminGroup.GET("/case-studies", adminCaseStudiesHandler.List)              // List case studies
	adminGroup.GET("/case-studies/new", adminCaseStudiesHandler.New)           // Create form
	adminGroup.POST("/case-studies", adminCaseStudiesHandler.Create)           // Process creation
	adminGroup.GET("/case-studies/:id/edit", adminCaseStudiesHandler.Edit)     // Edit form
	adminGroup.POST("/case-studies/:id", adminCaseStudiesHandler.Update)       // Process update
	adminGroup.DELETE("/case-studies/:id", adminCaseStudiesHandler.Delete)     // Delete (HTMX)

	// Sub-entity management via HTMX
	adminGroup.POST("/case-studies/:id/products", adminCaseStudiesHandler.AddProduct)                    // Link product
	adminGroup.DELETE("/case-studies/:id/products/:productId", adminCaseStudiesHandler.RemoveProduct)    // Unlink product
	adminGroup.POST("/case-studies/:id/metrics", adminCaseStudiesHandler.AddMetric)                      // Add success metric
	adminGroup.DELETE("/case-studies/:id/metrics/:metricId", adminCaseStudiesHandler.DeleteMetric)       // Delete metric

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Solution Management Routes (Phase 4)
	// ─────────────────────────────────────────────────────────────────────────
	// Solution editor with stats, challenges, products, and CTAs

	adminSolutionsHandler := adminHandlers.NewSolutionsHandler(queries, logger, appCache)
	adminGroup.GET("/solutions", adminSolutionsHandler.List)              // List solutions
	adminGroup.GET("/solutions/new", adminSolutionsHandler.New)           // Create form
	adminGroup.POST("/solutions", adminSolutionsHandler.Create)           // Process creation
	adminGroup.GET("/solutions/:id/edit", adminSolutionsHandler.Edit)     // Edit form
	adminGroup.POST("/solutions/:id", adminSolutionsHandler.Update)       // Process update
	adminGroup.DELETE("/solutions/:id", adminSolutionsHandler.Delete)     // Delete (HTMX)

	// Sub-entity management via HTMX
	adminGroup.POST("/solutions/:id/stats", adminSolutionsHandler.AddStat)                            // Add statistic
	adminGroup.DELETE("/solutions/:id/stats/:statId", adminSolutionsHandler.DeleteStat)               // Delete stat
	adminGroup.POST("/solutions/:id/challenges", adminSolutionsHandler.AddChallenge)                  // Add challenge
	adminGroup.DELETE("/solutions/:id/challenges/:challengeId", adminSolutionsHandler.DeleteChallenge) // Delete challenge
	adminGroup.POST("/solutions/:id/products", adminSolutionsHandler.AddProduct)                      // Link product
	adminGroup.DELETE("/solutions/:id/products/:productId", adminSolutionsHandler.RemoveProduct)      // Unlink product
	adminGroup.POST("/solutions/:id/ctas", adminSolutionsHandler.AddCTA)                              // Add CTA button
	adminGroup.DELETE("/solutions/:id/ctas/:ctaId", adminSolutionsHandler.DeleteCTA)                  // Delete CTA

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Whitepaper Management Routes (Phase 8)
	// ─────────────────────────────────────────────────────────────────────────
	// Whitepaper CRUD with PDF upload and download tracking

	adminWhitepapersHandler := adminHandlers.NewWhitepapersHandler(queries, logger, appCache)
	adminGroup.GET("/whitepapers", adminWhitepapersHandler.List)              // List whitepapers
	adminGroup.GET("/whitepapers/new", adminWhitepapersHandler.New)           // Create form
	adminGroup.POST("/whitepapers", adminWhitepapersHandler.Create)           // Upload PDF, process
	adminGroup.GET("/whitepapers/:id/edit", adminWhitepapersHandler.Edit)     // Edit form
	adminGroup.POST("/whitepapers/:id", adminWhitepapersHandler.Update)       // Update metadata
	adminGroup.DELETE("/whitepapers/:id", adminWhitepapersHandler.Delete)     // Delete (HTMX)
	adminGroup.GET("/whitepapers/:id/downloads", adminWhitepapersHandler.Downloads) // View download analytics

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Homepage Management Routes (Phase 9)
	// ─────────────────────────────────────────────────────────────────────────
	// Manage homepage components: heroes, stats, testimonials, CTAs, and settings

	homepageAdminHandler := adminHandlers.NewHomepageHandler(queries, logger)

	// Hero sections - large banner images with headlines and CTAs
	adminGroup.GET("/homepage/heroes", homepageAdminHandler.HeroesList)              // List heroes
	adminGroup.GET("/homepage/heroes/new", homepageAdminHandler.HeroNew)             // Create form
	adminGroup.POST("/homepage/heroes", homepageAdminHandler.HeroCreate)             // Process creation
	adminGroup.GET("/homepage/heroes/:id/edit", homepageAdminHandler.HeroEdit)       // Edit form
	adminGroup.POST("/homepage/heroes/:id", homepageAdminHandler.HeroUpdate)         // Update
	adminGroup.DELETE("/homepage/heroes/:id", homepageAdminHandler.HeroDelete)       // Delete (HTMX)

	// Statistics - impressive numbers to highlight company achievements
	adminGroup.GET("/homepage/stats", homepageAdminHandler.StatsList)                // List stats
	adminGroup.GET("/homepage/stats/new", homepageAdminHandler.StatNew)              // Create form
	adminGroup.POST("/homepage/stats", homepageAdminHandler.StatCreate)              // Process creation
	adminGroup.GET("/homepage/stats/:id/edit", homepageAdminHandler.StatEdit)        // Edit form
	adminGroup.POST("/homepage/stats/:id", homepageAdminHandler.StatUpdate)          // Update
	adminGroup.DELETE("/homepage/stats/:id", homepageAdminHandler.StatDelete)        // Delete (HTMX)

	// Testimonials - customer quotes with attribution
	adminGroup.GET("/homepage/testimonials", homepageAdminHandler.TestimonialsList)              // List testimonials
	adminGroup.GET("/homepage/testimonials/new", homepageAdminHandler.TestimonialNew)            // Create form
	adminGroup.POST("/homepage/testimonials", homepageAdminHandler.TestimonialCreate)            // Process creation
	adminGroup.GET("/homepage/testimonials/:id/edit", homepageAdminHandler.TestimonialEdit)      // Edit form
	adminGroup.POST("/homepage/testimonials/:id", homepageAdminHandler.TestimonialUpdate)        // Update
	adminGroup.DELETE("/homepage/testimonials/:id", homepageAdminHandler.TestimonialDelete)      // Delete (HTMX)

	// Call-to-Action buttons - conversion-focused buttons with links
	adminGroup.GET("/homepage/cta", homepageAdminHandler.CTAList)                    // List CTAs
	adminGroup.GET("/homepage/cta/new", homepageAdminHandler.CTANew)                 // Create form
	adminGroup.POST("/homepage/cta", homepageAdminHandler.CTACreate)                 // Process creation
	adminGroup.GET("/homepage/cta/:id/edit", homepageAdminHandler.CTAEdit)           // Edit form
	adminGroup.POST("/homepage/cta/:id", homepageAdminHandler.CTAUpdate)             // Update
	adminGroup.DELETE("/homepage/cta/:id", homepageAdminHandler.CTADelete)           // Delete (HTMX)

	// Homepage-specific settings (meta tags, feature flags, etc.)
	adminGroup.GET("/homepage/settings", homepageAdminHandler.Settings)              // Edit settings form
	adminGroup.POST("/homepage/settings", homepageAdminHandler.UpdateSettings)       // Update settings

	// ─────────────────────────────────────────────────────────────────────────
	// Section-Specific Settings Routes
	// ─────────────────────────────────────────────────────────────────────────
	// Configure meta tags, titles, and descriptions for each major site section

	sectionSettingsHandler := adminHandlers.NewSectionSettingsHandler(queries, logger)

	// About section settings - SEO and page-level configuration
	adminGroup.GET("/about/settings", sectionSettingsHandler.AboutSettings)
	adminGroup.POST("/about/settings", sectionSettingsHandler.UpdateAboutSettings)

	// Products section settings
	adminGroup.GET("/products/settings", sectionSettingsHandler.ProductsSettings)
	adminGroup.POST("/products/settings", sectionSettingsHandler.UpdateProductsSettings)

	// Solutions section settings
	adminGroup.GET("/solutions/settings", sectionSettingsHandler.SolutionsSettings)
	adminGroup.POST("/solutions/settings", sectionSettingsHandler.UpdateSolutionsSettings)

	// Blog section settings
	adminGroup.GET("/blog/settings", sectionSettingsHandler.BlogSettings)
	adminGroup.POST("/blog/settings", sectionSettingsHandler.UpdateBlogSettings)

	// ─────────────────────────────────────────────────────────────────────────
	// Admin About Page Management Routes (Phase 7)
	// ─────────────────────────────────────────────────────────────────────────
	// Manage all components of the About page

	adminAboutHandler := adminHandlers.NewAboutHandler(queries, logger, appCache)

	// Company overview - main about content with rich text editor
	adminGroup.GET("/about/overview", adminAboutHandler.OverviewEdit)
	adminGroup.POST("/about/overview", adminAboutHandler.OverviewUpdate)

	// Mission, Vision, Values - core company statements
	adminGroup.GET("/about/mvv", adminAboutHandler.MVVEdit)
	adminGroup.POST("/about/mvv", adminAboutHandler.MVVUpdate)

	// Core Values - individual value items with icons
	adminGroup.GET("/about/values", adminAboutHandler.CoreValuesList)
	adminGroup.GET("/about/values/new", adminAboutHandler.CoreValueNew)
	adminGroup.POST("/about/values", adminAboutHandler.CoreValueCreate)
	adminGroup.GET("/about/values/:id/edit", adminAboutHandler.CoreValueEdit)
	adminGroup.POST("/about/values/:id", adminAboutHandler.CoreValueUpdate)
	adminGroup.DELETE("/about/values/:id", adminAboutHandler.CoreValueDelete)

	// Company Milestones - timeline of achievements
	adminGroup.GET("/about/milestones", adminAboutHandler.MilestonesList)
	adminGroup.GET("/about/milestones/new", adminAboutHandler.MilestoneNew)
	adminGroup.POST("/about/milestones", adminAboutHandler.MilestoneCreate)
	adminGroup.GET("/about/milestones/:id/edit", adminAboutHandler.MilestoneEdit)
	adminGroup.POST("/about/milestones/:id", adminAboutHandler.MilestoneUpdate)
	adminGroup.DELETE("/about/milestones/:id", adminAboutHandler.MilestoneDelete)

	// Company Certifications - quality and compliance badges
	adminGroup.GET("/about/certifications", adminAboutHandler.CertificationsList)
	adminGroup.GET("/about/certifications/new", adminAboutHandler.CertificationNew)
	adminGroup.POST("/about/certifications", adminAboutHandler.CertificationCreate)
	adminGroup.GET("/about/certifications/:id/edit", adminAboutHandler.CertificationEdit)
	adminGroup.POST("/about/certifications/:id", adminAboutHandler.CertificationUpdate)
	adminGroup.DELETE("/about/certifications/:id", adminAboutHandler.CertificationDelete)

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Partners Management Routes (Phase 7)
	// ─────────────────────────────────────────────────────────────────────────
	// Manage partner companies and their testimonials

	adminPartnersHandler := adminHandlers.NewPartnersHandler(queries, logger, appCache)

	// Partner companies - directory with logos, tiers, and descriptions
	adminGroup.GET("/partners", adminPartnersHandler.List)
	adminGroup.GET("/partners/new", adminPartnersHandler.New)
	adminGroup.POST("/partners", adminPartnersHandler.Create)
	adminGroup.GET("/partners/:id/edit", adminPartnersHandler.Edit)
	adminGroup.POST("/partners/:id", adminPartnersHandler.Update)
	adminGroup.DELETE("/partners/:id", adminPartnersHandler.Delete)

	// Partner testimonials - quotes from partner organizations
	adminGroup.GET("/partners/testimonials", adminPartnersHandler.TestimonialsList)
	adminGroup.GET("/partners/testimonials/new", adminPartnersHandler.TestimonialNew)
	adminGroup.POST("/partners/testimonials", adminPartnersHandler.TestimonialCreate)
	adminGroup.GET("/partners/testimonials/:id/edit", adminPartnersHandler.TestimonialEdit)
	adminGroup.POST("/partners/testimonials/:id", adminPartnersHandler.TestimonialUpdate)
	adminGroup.DELETE("/partners/testimonials/:id", adminPartnersHandler.TestimonialDelete)

	// ─────────────────────────────────────────────────────────────────────────
	// Media Library Routes (Phase 18)
	// ─────────────────────────────────────────────────────────────────────────
	// Centralized media management with upload, browsing, and metadata editing

	mediaHandler := adminHandlers.NewMediaHandler(queries, logger, "public/uploads")
	adminGroup.GET("/media", mediaHandler.List)               // Main media library page
	adminGroup.POST("/media/upload", mediaHandler.Upload)     // Upload new media file
	adminGroup.GET("/media/browse", mediaHandler.Browse)      // HTMX: modal browser for image selection
	adminGroup.GET("/media/:id", mediaHandler.GetFile)        // Get media file details
	adminGroup.PUT("/media/:id", mediaHandler.UpdateAltText)  // Update alt text for accessibility
	adminGroup.DELETE("/media/:id", mediaHandler.Delete)      // Delete media file (HTMX)

	// ─────────────────────────────────────────────────────────────────────────
	// Navigation Management Routes (Phase 19)
	// ─────────────────────────────────────────────────────────────────────────
	// Visual menu builder with drag-and-drop reordering via HTMX

	navHandler := adminHandlers.NewNavigationHandler(queries, logger)
	adminGroup.GET("/navigation", navHandler.List)                        // List all menus
	adminGroup.POST("/navigation", navHandler.Create)                     // Create new menu
	adminGroup.GET("/navigation/:id", navHandler.Edit)                    // Menu editor interface
	adminGroup.POST("/navigation/:id/settings", navHandler.UpdateMenu)    // Update menu settings
	adminGroup.POST("/navigation/:id/items", navHandler.AddItem)          // Add menu item (HTMX)
	adminGroup.POST("/navigation/items/:id", navHandler.UpdateItem)       // Update item (HTMX)
	adminGroup.DELETE("/navigation/items/:id", navHandler.DeleteItem)     // Delete item (HTMX)
	adminGroup.DELETE("/navigation/:id", navHandler.DeleteMenu)           // Delete entire menu (HTMX)
	adminGroup.POST("/navigation/:id/reorder", navHandler.Reorder)        // Reorder items (HTMX drag-drop)

	// ─────────────────────────────────────────────────────────────────────────
	// Activity Log Routes (Phase 20)
	// ─────────────────────────────────────────────────────────────────────────
	// Audit trail of all admin actions for security and accountability

	activityHandler := adminHandlers.NewActivityHandler(queries, logger)
	adminGroup.GET("/activity", activityHandler.List)  // View activity log with filtering

	// ─────────────────────────────────────────────────────────────────────────
	// Admin Contact Management Routes (Phase 8)
	// ─────────────────────────────────────────────────────────────────────────
	// Manage contact form submissions and office locations

	adminContactHandler := adminHandlers.NewAdminContactHandler(queries, logger, appCache)

	// Contact form submissions - inbox-style interface
	adminGroup.GET("/contact/submissions", adminContactHandler.ListSubmissions)                   // List all submissions
	adminGroup.GET("/contact/submissions/:id", adminContactHandler.ViewSubmission)                // View single submission
	adminGroup.POST("/contact/submissions/:id/status", adminContactHandler.UpdateSubmissionStatus) // Mark read/unread (HTMX)
	adminGroup.POST("/contact/submissions/bulk-mark-read", adminContactHandler.BulkMarkRead)      // Bulk mark read (HTMX)
	adminGroup.DELETE("/contact/submissions/:id", adminContactHandler.DeleteSubmission)           // Delete submission (HTMX)

	// Office locations - physical office addresses displayed on contact page
	adminGroup.GET("/contact/offices", adminContactHandler.ListOffices)
	adminGroup.GET("/contact/offices/new", adminContactHandler.NewOffice)
	adminGroup.POST("/contact/offices", adminContactHandler.CreateOffice)
	adminGroup.GET("/contact/offices/:id/edit", adminContactHandler.EditOffice)
	adminGroup.POST("/contact/offices/:id", adminContactHandler.UpdateOffice)
	adminGroup.DELETE("/contact/offices/:id", adminContactHandler.DeleteOffice)

	// ═══════════════════════════════════════════════════════════════════════════
	// SERVER STARTUP AND GRACEFUL SHUTDOWN
	// ═══════════════════════════════════════════════════════════════════════════

	// Start HTTP server in a goroutine so it doesn't block signal handling
	// The server listens on port 28090 for all incoming HTTP requests
	port := "28090"
	if v := os.Getenv("PORT"); v != "" {
		port = v
	}
	go func() {
		logger.Info("starting server", "port", port)
		// Start returns an error when server stops (normal shutdown or fatal error)
		if err := e.Start(":" + port); err != nil && err != http.ErrServerClosed {
			// Log fatal errors (http.ErrServerClosed is expected during graceful shutdown)
			logger.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	// Set up signal handling for graceful shutdown
	// Create buffered channel to receive OS signals (buffer prevents blocking)
	quit := make(chan os.Signal, 1)
	// Register to receive interrupt signals (Ctrl+C, SIGINT, SIGTERM)
	signal.Notify(quit, os.Interrupt)
	// Block here until we receive a signal
	<-quit

	// Graceful shutdown sequence begins
	logger.Info("shutting down server")

	// Create context with 10-second timeout for shutdown operations
	// This gives active requests time to complete before forced termination
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Attempt graceful shutdown: stop accepting new connections, wait for active requests
	// If timeout expires, server forcefully closes remaining connections
	if err := e.Shutdown(ctx); err != nil {
		logger.Error("server shutdown error", "error", err)
	}

	logger.Info("server stopped")
}
